title: Team Carriger
# Include external resources
resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css

background: center / cover no-repeat url("/background.png") fixed
views:
    # System Overview tab
  - title: Overview
    id: overview
    cards:
        # Card for status bits.
      - type: entities
        title: People
        show_header_toggle: false
        entities:
          - person.brett
          - person.liz
      - type: entity-filter
        title: Home Status
        show_header_toggle: false
        entities:
          - cover.garage_door
          - lock.front_door
          - binary_sensor.livingroom_door_opened
          - binary_sensor.living_room_window
          - binary_sensor.garage_entry_opened
          - binary_sensor.sliding_glass_door_opened
          - binary_sensor.garage_door_back
        state_filter:
          - "on"
      - type: alarm-panel
        name: House Alarm
        show_header_toggle: false
        entity: alarm_control_panel.alarm_panel
        # Garage Door Card
      - type: entities
        title: Doors
        show_header_toggle: false
        entities:
          - cover.garage_door
          - lock.front_door
        #HVAC control
      - type: thermostat
        entity: climate.hvac
      - type: entities
        title: Media Control
        show_header_toggle: false
        entities:
          - type: weblink
            name: Sonarr
            url: https://sonarr.teamcarriger.club
            icon: mdi:television-box
          - type: weblink
            name: Radarr
            url: https://radarr.teamcarriger.club
            icon: mdi:library-movie
    # Main Level 
  - title: Main Level
    id: house_main
    cards:
      - type: entities
        title: Living room
        show_header_toggle: false
        entities:
          - light.main_livingroom
          - light.jayhawk_candle
          - light.livingroom_entry
          - sensor.hvac_humidity
          - sensor.hvac_temperature
          - binary_sensor.livingroom_door_opened
          - binary_sensor.living_room_window
          - switch.livingroom_subwoofer
      - type: media-control
        entity: media_player.livingroom_media
      - type: entities
        title: Kitchen
        show_header_toggle: false
        entities:
          - fan.kitchen_fan
          - light.cabinet_led
            name: Under Cabinet LED
          - light.kitchen_sink
            name: Kitchen Sink Light
          - light.kitchen_lamp
            name: "Kitchen overhead Light"
          - light.kitchen_fan
            name: "Kitchen Fan Light"
          - sensor.kitchen_leak
          - sensor.kitchen_humidity
          - sensor.kitchen_pressure
          - sensor.kitchen_temp
          - sensor.garage_entry_temperature
          - binary_sensor.garage_entry_opened
          - binary_sensor.sliding_glass_door_opened
          - binary_sensor.kitchen_motion

  - title: Upstairs
    id: house_upstairs
    cards:
      - type: entities
        title: Master Bed
        show_header_toggle: false
        entities:
          - fan.master_fan
          - light.master_fan_light
            name: "Master Bedroom Light"
          - switch.master_tv
            name: "Master Bedroom TV"
          - light.liz_headboard
          - light.brett_headboard
          - binary_sensor.master_bed_window
          - sensor.master_bed_window_temp
      - type: media-control
        entity: media_player.master_tv
      - type: entities
        title: Emi Room
        show_header_toggle: false
        entities:
          - fan.emi_fan
          - light.emi_fan_light
          - light.emi_star_lamp
          - binary_sensor.emi_motion
          - sensor.emi_temp
        camera_image: camera.amcrest_camera
      - type: entities
        title: Main Bath
        show_header_toggle: false
        entities:
          - light.main_bath_vanity
          - light.main_bath_vent_light
          - switch.main_bath_fan
          - binary_sensor.main_bath_motion
          - sensor.bathroom_vent_humidity
          - sensor.bathroom_vent_pressure
          - sensor.bathroom_vent_temperature
          - sensor.bathroom_vent_voc
          - binary_sensor.main_bath_vent_needed
      - type: entities
        title: Hallway
        show_header_toggle: false
        entities:
          - light.hallway
          - binary_sensor.hallway_motion_combine
          - sensor.hallway_motion_temp
          - binary_sensor.hall_window_opened
          - sensor.hall_window_temperature
          
    # Basement view
  - title: Basement
    id: house_basement
    cards:
      - type: media-control
        entity: media_player.projector_media
      - type: entities
        title: Office
        show_header_toggle: false
        entities:
          - switch.off_4k_mon
          - switch.off_computron3000
          - switch.office_heater
          - binary_sensor.off_sts_motion
          - sensor.office_computer_power
          - sensor.office_humidity
          - sensor.office_pressure
          - sensor.office_temperature
      - type: entities
        title: Printer
        show_header_toggle: false
        entities:
          - binary_sensor.octoprint_printing
          - binary_sensor.octoprint_printing_error
          - sensor.octoprint_actual_bed_temp
          - sensor.octoprint_target_bed_temp
          - sensor.octoprint_actual_tool0_temp
          - sensor.octoprint_target_tool0_temp
          - sensor.octoprint_current_state
          - sensor.octoprint_job_percentage
          - sensor.octoprint_time_remaining
      - type: entities
        # Title of the entities card
        title: Laundry Room
        show_header_toggle: false
        entities:
          - switch.laundry_room_litter_box
          - binary_sensor.laundry_motion_1
          - binary_sensor.laundry_motion_2
          - binary_sensor.laundry_motion_3
          - binary_sensor.laundry_room_cat_detection
          - sensor.laundry_temp
          - sensor.laundry_humidity
          - sensor.laundry_pressure
          
  - title: Other
    id: house_other
    cards:
      - type: entities
        title: Attic
        show_header_toggle: false
        entities:
          - sensor.attic_humidity
          - sensor.attic_pressure
          - sensor.attic_temp
        # Add front porch
      - type: entities
        title: "Front Porch"
        show_header_toggle: false
        entities:
          - light.porch_light
      - type: entities
        title: Garage
        show_header_toggle: false
        entities:
          - binary_sensor.garage_motion_board
          - binary_sensor.garage_door_back
          - sensor.network_power_useage
          - sensor.garage_pressure
          - sensor.garage_temperature
          - sensor.garage_humidity
  - title: Cameras
    id: house_camera
    cards:
      - type: picture-glance
        title: Emi Room
        entities: []
        camera_image: camera.amcrest_camera
        camera_view: live
        # Add front porch
      - type: picture-glance
        title: "Front Porch"
        entities: []
        camera_image: camera.front_porch
        camera_view: live
      - type: picture-glance
        title: Backyard
        entities: []
        camera_image: camera.backyard
        camera_view: live
      - type: picture-glance
        title: Garage
        entities: []
        camera_image: camera.garage
        camera_view: live
      - type: picture-glance
        title: Garage Board
        entities: []
        camera_image: camera.ttgocam01
        camera_view: live
      - type: picture-glance
        title: OctoPrint
        entities: []
        camera_image: camera.octoprint
        camera_view: live
  - title: Plants
    id: plants
    cards:
      - type: plant-status
        entity: plant.cedars
      - type: plant-status
        entity: plant.trees
  - title: System
    id: house_system
    cards:
      - type: iframe
        url: https://192.168.1.243:3000/d/cYqIkiIZk/internet-speed?orgId=1&from=1565952833350&to=1565963633350
      - type: entities
        title: Network
        show_header_toggle: false
        entities:
          - sensor.speedtest_download
          - sensor.speedtest_upload
          - sensor.speedtest_ping
          - sensor.vpn_down
          - sensor.vpn_up
          - type: divider
          - sensor.radarr_movies
          - sensor.radarr_upcoming
          - type: divider
          - sensor.sonarr_series
          - sensor.sonarr_upcoming
          - sensor.sonarr_wanted
          - type: divider
          - sensor.deluge_down_speed
          - sensor.deluge_up_speed
      - type: entities
        title: Virtual Server
        show_header_toggle: false
        entities:
          - sensor.virtualserver_generic_memory_data_available_memory
          - sensor.virtualserver_generic_memory_data_used_memory
          - sensor.virtualserver_intel_core_i7_2600_clocks_cpu_core_1
          - sensor.virtualserver_intel_core_i7_2600_clocks_cpu_core_2
          - sensor.virtualserver_intel_core_i7_2600_clocks_cpu_core_3
          - sensor.virtualserver_intel_core_i7_2600_clocks_cpu_core_4
          - type: divider
          - sensor.virtualserver_intel_core_i7_2600_temperatures_cpu_core_1
          - sensor.virtualserver_intel_core_i7_2600_temperatures_cpu_core_2
          - sensor.virtualserver_intel_core_i7_2600_temperatures_cpu_core_3
          - sensor.virtualserver_intel_core_i7_2600_temperatures_cpu_core_4
          - sensor.virtualserver_intel_core_i7_2600_temperatures_cpu_package
          - sensor.virtualserver_wdc_wd10ezex_08wn4a0_temperatures_temperature
          - sensor.virtualserver_wdc_wd5000aakx_753ca1_temperatures_temperature
          - sensor.virtualserver_st1000dm010_2ep102_temperatures_temperature
          - type: divider
          - sensor.virtualserver_st1000dm010_2ep102_load_used_space
      - type: entities
        title: Virtual Server
        show_header_toggle: false
        entities:
          - sensor.frankenserver_generic_memory_data_available_memory
          - sensor.frankenserver_generic_memory_data_used_memory
          - sensor.frankenserver_intel_core_i3_6100_clocks_cpu_core_1
          - sensor.frankenserver_intel_core_i3_6100_clocks_cpu_core_2
          - type: divider
          - sensor.frankenserver_intel_core_i3_6100_temperatures_cpu_core_1
          - sensor.frankenserver_intel_core_i3_6100_temperatures_cpu_core_2
          - sensor.frankenserver_intel_core_i3_6100_temperatures_cpu_package
          - sensor.frankenserver_wdc_wd20ears_00s8b1_temperatures_temperature
          - sensor.frankenserver_wdc_wd20ears_00s8b1_temperatures_temperature_2
          - sensor.frankenserver_wdc_wd20earx_00pasb0_temperatures_temperature
          - sensor.frankenserver_wdc_wd20earx_00pasb0_temperatures_temperature_2
          - sensor.frankenserver_wdc_wd20ezrx_00d8pb0_temperatures_temperature
          - type: divider
          - sensor.frankenserver_generic_hard_disk_load_used_space
          - sensor.frankenserver_generic_hard_disk_load_used_space_2
          - type: divider
          - switch.off_frankenserver
      - type: entities
        title: HVAC Status
        show_header_toggle: false
        entities:
          - binary_sensor.house_sts_hvac_run
          - binary_sensor.house_sts_hum_passive_req
          - binary_sensor.house_sts_hum_passive_run
          - binary_sensor.house_sts_hum_active_req
          - sensor.hvac_humidity
          - sensor.hvac_target_humidity
          - switch.humidifier

  - title: Calibration
    id: house_calibration
    cards:
      - type: entities
        title: HVAC
        show_header_toggle: false
        entities:
          - entity: input_number.hvac_home_ac_temp
            name: "Home AC Temp"
          - entity: input_number.hvac_away_ac_temp
            name: "Away AC temp"
          - entity: input_number.hvac_overnight_ac_temp
            name: "Overnight AC Temp"
          - entity: input_number.hvac_vacation_ac_temp
            name: "Vacation AC Temp"
          - type: divider
          - entity: input_number.hvac_home_heat_temp
            name: "Home heat temp"
          - entity: input_number.hvac_away_heat_temp
            name: "Away heat temp"
          - entity: input_number.hvac_overnight_heat_temp
            name: "Overnight heat temp"
          - entity: input_number.hvac_vacation_heat_temp
            name: "Vacation heat temp"
          - type: divider
          - entity: input_number.hvac_humidity_max
            name: "Max humidity"
          - type: divider
#          - entity: input_number.hvac_AC_enable_temp
#            name: "AC enable temp"
          - entity: input_number.hvac_heat_enable_temp
            name: "Heat enable temp"  
      - type: entities
        title: Office
        show_header_toggle: false
        entities:
          - entity: input_number.office_heater_thresh
            name: "Office heater threshold"
      - type: entities
        title: "Main Bath"
        show_header_toggle: false
        entities:
          - entity: input_number.main_bath_humidity_thresh
            name: "Vent humidity threshold"
