title: Team Carriger
# Include external resources
resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css

background: center / cover no-repeat url("/background.png") fixed
views:
    # System Overview tab
  - title: Overview
    id: overview
    icon: mdi:home-assistant
    cards:
      - type: alarm-panel
        name: House Alarm
        show_header_toggle: false
        entity: alarm_control_panel.alarm_panel
        # Card for status bits.
      - type: entities
        title: People
        show_header_toggle: false
        entities:
          - device_tracker.google_maps_108379141181739394475
          - device_tracker.google_maps_116842525089175776476
      - type: entity-filter
        title: Home Status
        show_header_toggle: false
        entities:
          - cover.garage_door
          - lock.front_door
          - binary_sensor.livingroom_door_opened
          - binary_sensor.living_room_window
          - binary_sensor.garage_entry_opened
          - binary_sensor.sliding_glass_door_opened
          - binary_sensor.garage_door_back
        state_filter:
          - "on"
        show_empty: false
        # Garage Door Card
      - type: entities
        title: Doors
        show_header_toggle: false
        entities:
          - cover.garage_door
          - lock.front_door
      - type: entities
        title: Rapture Alert
        show_header_toggle: false
        entities:
          - sensor.us_coronavirus_confirmed
          - sensor.us_coronavirus_current
          - sensor.us_coronavirus_deaths
          - sensor.us_coronavirus_recovered
#      - type: vertical-stack
#        title: Mail Today
#        cards:
#          - type: picture-glance
#            camera_image: camera.mail_usps
#            entities: []
#          - type: entity-filter
#            state_filter:
#              - operator: '>'
#                value: '0'
#            entities:
#              - entity: sensor.mail_usps_mail
#                name: USPS Mail
#              - entity: sensor.mail_usps_packages
#                name: USPS Packages
#              - entity: sensor.fedex_packages
#                name: FedEx Packages
#              - sensor.mail_ups_packages
#              - sensor.mail_packages_in_transit
#              - sensor.mail_packages_delivered
#              - entity: sensor.mail_updated
#                state_filter:
#                  - operator: regex
#                    value: 20
    # Main Level 
  - title: Main Level
    id: house_main
    icon: mdi:home-floor-1
    cards:
      - type: entities
        title: Living room
        show_header_toggle: false
        entities:
          - light.main_livingroom
          - light.jayhawk_candle
          - light.livingroom_entry
          - sensor.hvac_humidity
          - sensor.hvac_temperature
          - binary_sensor.livingroom_door_opened
          - binary_sensor.living_room_window
          - switch.livingroom_subwoofer
      - type: media-control
        entity: media_player.livingroom_media
      - type: entities
        title: Kitchen
        show_header_toggle: false
        entities:
          - fan.kitchen_fan
          - light.cabinet_led
          - light.kitchen_sink
          - light.kitchen_lamp
          - light.kitchen_fan
          - binary_sensor.kitchen_leak
          - sensor.garage_entry_temperature
          - binary_sensor.garage_entry_opened
          - binary_sensor.sliding_glass_door_opened
          - binary_sensor.kitchen_motion

  - title: Upstairs
    id: house_upstairs
    icon: mdi:home-floor-2
    cards:
      - type: entities
        title: Master Bed
        show_header_toggle: false
        entities:
          - fan.master_fan
          - light.master_fan_light
          - switch.master_tv
          - light.liz_headboard
          - light.brett_headboard
          - binary_sensor.master_bed_window
          - sensor.master_bed_window_temp
      - type: media-control
        entity: media_player.master_tv
      - type: entities
        title: Emi Room
        show_header_toggle: false
        entities:
          - fan.emi_fan
          - light.emi_fan_light
          - light.emi_star_lamp
          - binary_sensor.emi_motion
          - sensor.emi_temp
        camera_image: camera.amcrest_camera
      - type: entities
        title: Nursery Room
        show_header_toggle: false
        entities:
          - fan.nursery_fan
          - light.nursery_fan_light
      - type: entities
        title: Main Bath
        show_header_toggle: false
        entities:
          - light.main_bath_vanity
          - light.main_bath_vent_light
          - switch.main_bath_fan
          - binary_sensor.main_bath_motion
          - sensor.bathroom_vent_humidity
          - sensor.bathroom_vent_pressure
          - sensor.bathroom_vent_temperature
          - sensor.bathroom_vent_voc
          - binary_sensor.main_bath_vent_needed
      - type: entities
        title: Hallway
        show_header_toggle: false
        entities:
          - light.hallway
          - binary_sensor.hallway_motion_combine
          - sensor.hall_motion_temp
          - sensor.hall_motion_temp_2
          - binary_sensor.hall_window_opened
          - sensor.hall_window_temperature
          
    # Basement view
  - title: Basement
    id: house_basement
    icon: mdi:home-floor-negative-1
    cards:
      - type: entities
        title: Main Basement
        show_header_toggle: false
        entities:
          - light.basemet_dimmer
          - light.basement_stair_light
          - light.shelf_light_combine
      - type: media-control
        entity: media_player.projector_media
      - type: entities
        title: Office
        show_header_toggle: false
        entities:
          - switch.off_4k_mon
          - switch.off_computron3000
          - binary_sensor.off_sts_motion
          - sensor.office_computer_power
          - sensor.office_humidity
          - sensor.office_pressure
          - climate.office_climate
      - type: entities
        title: Printer
        show_header_toggle: false
        entities:
          - binary_sensor.octoprint_printing
          - binary_sensor.octoprint_printing_error
          - sensor.octoprint_actual_bed_temp
          - sensor.octoprint_target_bed_temp
          - sensor.octoprint_actual_tool0_temp
          - sensor.octoprint_target_tool0_temp
          - sensor.octoprint_current_state
          - sensor.octoprint_job_percentage
          - sensor.octoprint_time_remaining
      - type: entities
        # Title of the entities card
        title: Laundry Room
        show_header_toggle: false
        entities:
          - switch.laundry_room_litter_box
          - binary_sensor.cat_motion_combine_2
          - sensor.laundry_temp
          - sensor.laundry_humidity
          - sensor.laundry_pressure
          
  - title: Other
    id: house_other
    icon: mdi:home-floor-0
    cards:
      - type: thermostat
        entity: climate.hvac_local
      - type: entities
        title: Attic
        show_header_toggle: false
        entities:
          - sensor.attic_humidity
          - sensor.attic_pressure
          - sensor.attic_temp
        # Add front porch
      - type: entities
        title: "Front Porch"
        show_header_toggle: false
        entities:
          - light.porch_light
          - light.garage_ext_1
          - light.garage_ext_2
      - type: entities
        title: Garage
        show_header_toggle: false
        entities:
          - binary_sensor.garage_motion_board
          - binary_sensor.garage_door_back
          - sensor.network_power_useage
          - sensor.garage_pressure
          - sensor.garage_temperature
          - sensor.garage_humidity
  - title: Cameras
    id: house_camera
    icon: mdi:cctv
    cards:
      - type: picture-glance
        title: Emi Room
        entities: []
        camera_image: camera.emi_camera
        camera_view: live
        # Add front porch
      - type: picture-glance
        title: "Front Porch"
        entities: []
        camera_image: camera.frontdoor
        camera_view: live
      - type: picture-glance
        title: "Front Porch"
        entities: []
        camera_image: camera.front_porch
        camera_view: live
      - type: picture-glance
        title: Backyard
        entities: []
        camera_image: camera.backyard
        camera_view: live
      - type: picture-glance
        title: Garage
        entities: []
        camera_image: camera.garage
        camera_view: live
      - type: picture-glance
        title: OctoPrint
        entities: []
        camera_image: camera.octoprint
        camera_view: live
  - title: Plants
    id: plants
    icon: mdi:flower-outline
    cards:
      - type: plant-status
        entity: plant.trees
      - type: plant-status
        entity: plant.hydrangea
      - type: entities
        title: Mini-tank
        show_header_toggle: false
        entities:
          - light.air_pump
          - light.bed_pump
          - light.heater
          - input_boolean.feed_mini_tank
          - sensor.bed_probe_c
          - sensor.tank_probe_c
          - sensor.minitank_humidity
          - sensor.minitank_pressure
          - sensor.minitank_temperature
          - light.tank_light
      - type: entities
        title: Irragation
        show_header_toggle: false
        entities:
          - switch.irr_master
          - switch.irr_zone1
          - switch.irr_zone2
          - sensor.water_flow
        
  - title: System
    id: house_system
    icon: mdi:lan
    cards:
      - type: history-graph
        title: 'House Temperatures'
        entities:
          - sensor.hvac_temperature
          - sensor.garage_entry_temperature
          - sensor.emi_temp
          - sensor.bathroom_vent_temperature
          - sensor.hall_motion_temp
          - sensor.hall_motion_temp_2
          - sensor.laundry_temp
          - sensor.garage_temperature
      - type: entities
        title: Network
        show_header_toggle: false
        entities:
          - sensor.speedtest_download
          - sensor.speedtest_upload
          - sensor.speedtest_ping
          - sensor.vpn_down
          - sensor.vpn_up
          - type: divider
          - sensor.radarr_movies
          - sensor.radarr_upcoming
          - type: divider
          - sensor.sonarr_series
          - sensor.sonarr_upcoming
          - sensor.sonarr_wanted
          - type: divider
          - sensor.qbittorrent_down_speed
          - sensor.qbittorrent_up_speed
          - sensor.qbittorrent_status

      - type: entities
        title: HVAC Status
        show_header_toggle: false
        entities:
          - binary_sensor.house_sts_hvac_run
          - binary_sensor.house_sts_hum_passive_req
          - binary_sensor.house_sts_hum_passive_run
          - binary_sensor.house_sts_hum_active_req
          - sensor.hvac_humidity
          - sensor.hvac_target_humidity
          - switch.humidifier

  - title: Calibration
    id: house_calibration
    icon: mdi:brain
    cards:
      - type: entities
        title: HVAC
        show_header_toggle: false
        entities:
          - entity: input_number.hvac_home_ac_temp
            name: "Home AC Temp"
          - entity: input_number.hvac_away_ac_temp
            name: "Away AC temp"
          - entity: input_number.hvac_overnight_ac_temp
            name: "Overnight AC Temp"
          - entity: input_number.hvac_vacation_ac_temp
            name: "Vacation AC Temp"
          - type: divider
          - entity: input_number.hvac_home_heat_temp
            name: "Home heat temp"
          - entity: input_number.hvac_away_heat_temp
            name: "Away heat temp"
          - entity: input_number.hvac_overnight_heat_temp
            name: "Overnight heat temp"
          - entity: input_number.hvac_vacation_heat_temp
            name: "Vacation heat temp"
          - type: divider
          - entity: input_number.hvac_humidity_max
            name: "Max humidity"
          - type: divider
          - entity: input_number.hvac_ac_enable_temp
            name: "AC enable temp"
          - entity: input_number.hvac_heat_enable_temp
            name: "Heat enable temp"  
      - type: entities
        title: Office
        show_header_toggle: false
        entities:
          - entity: input_number.office_heater_thresh
            name: "Office heater threshold"
      - type: entities
        title: "Main Bath"
        show_header_toggle: false
        entities:
          - entity: input_number.main_bath_humidity_thresh
            name: "Vent humidity threshold"
