- platform: mqtt
  schema: json
  name: 'Porch Light'
  state_topic: "porch_light" 
  command_topic: "porch_light/set"
  color_temp: true
  brightness: true
  rgb: true
  white_value: true
  effect: false
  optimistic: false
  
- platform: mqtt
  name: 'garage_ext_1'
  state_topic: "hawirelesslink/light/ledvance_a19_rgbw_00060a5e_1/state" 
  command_topic: "/HAwirelesslink/return/light/ledvance_a19_rgbw_00060a5e_1/state"
  brightness_state_topic: "hawirelesslink/light/ledvance_a19_rgbw_00060a5e_1/brightness"
  brightness_command_topic: "/HAwirelesslink/return/light/ledvance_a19_rgbw_00060a5e_1/brightness"
  payload_on: "on"
  payload_off: "off"
  rgb_state_topic: "hawirelesslink/light/ledvance_a19_rgbw_00060a5e_1/rgb_color"
  rgb_command_topic: "/HAwirelesslink/return/light/ledvance_a19_rgbw_00060a5e_1/rgb_color"
  rgb_command_template: "{{ '%02x%02x%02x' | format(red, green, blue)}}"
  optimistic: false

- platform: mqtt
  name: 'garage_ext_2'
  state_topic: "hawirelesslink/light/ledvance_a19_rgbw_00061a28_1/state" 
  command_topic: "/HAwirelesslink/return/light/ledvance_a19_rgbw_00061a28_1/state"
  brightness_state_topic: "hawirelesslink/light/ledvance_a19_rgbw_00061a28_1/brightness"
  brightness_command_topic: "/HAwirelesslink/return/light/ledvance_a19_rgbw_00061a28_1/brightness"
  payload_on: "on"
  payload_off: "off"
  rgb_state_topic: "hawirelesslink/light/ledvance_a19_rgbw_00061a28_1/rgb_color"
  rgb_command_topic: "/HAwirelesslink/return/light/ledvance_a19_rgbw_00061a28_1/rgb_color"
  rgb_command_template: "{{ '%02x%02x%02x' | format(red, green, blue)}}"
  optimistic: false
