- platform: mqtt
  schema: json
  name: 'Porch Light'
  state_topic: "porch_light" 
  command_topic: "porch_light/set"
  color_temp: true
  brightness: true
  rgb: true
  white_value: true
  effect: false
  optimistic: false
