- platform : mqtt
  name: "Cabinet_LED"
  state_topic: "/Cabinet_LED/relay/switch"
  command_topic: "/Cabinet_LED/gpio/12"
  payload_on: "1"
  payload_off: "0"
  retain: true

- platform: mqtt
  name: "kitchen_sink"
  state_topic: "zigbee2mqtt/0xb0ce1814031e3554"
  availability_topic: "zigbee2mqtt/bridge/state"
  brightness: true
  schema: "json"
  command_topic: "zigbee2mqtt/0xb0ce1814031e3554/set"

- platform: mqtt
  name: "kitchen_fan"
  state_topic: "zigbee2mqtt/0x0022a3000016d039"
  availability_topic: "zigbee2mqtt/bridge/state"
  brightness: true
  schema: "json"
  command_topic: "zigbee2mqtt/0x0022a3000016d039/set"
