- platform: mqtt
  name: "Emi Temp"
  state_topic: "smartthings/Emi Monitor/temperature"
  unit_of_measurement: "°F"

- platform: mqtt
  name: "Emi Humidity"
  state_topic: "smartthings/Emi Monitor/humidity"
  unit_of_measurement: "%"
