- platform: mqtt
  name: "Network Power useage"
  state_topic: "hawirelesslink/switch/aeotec_zw096_smart_switch_6_switch/power_consumption"
  unit_of_measurement: "W"

- platform: mqtt
  name: "Garage outlet Power useage"
  state_topic: "hawirelesslink/sensor/aeotec_zw096_smart_switch_6_power/power_consumption"
  unit_of_measurement: "W"
