- platform: mqtt
  state_topic: /garage/enviroment/Temperature
  name: "Garage Temperature"
  unit_of_measurement: "°C"
  retain: true
- platform: mqtt
  state_topic: /garage/enviroment/Pressure
  name: "Garage Pressure"
  unit_of_measurement: "P"
  retain: true
- platform: mqtt
  name: "Garage Energy"
  state_topic: "smartthings/Garage Switch/power"
  unit_of_measurement: "W"
  retain: true
 

