- platform: mqtt
  state_topic: /garage/enviroment/Temperature
  name: "Garage Temperature"
  unit_of_measurement: "°C"

- platform: mqtt
  state_topic: /garage/enviroment/Pressure
  name: "Garage Pressure"
  unit_of_measurement: "P"

- platform: mqtt
  name: "Garage Energy"
  state_topic: "smartthings/Garage Switch/power"
  unit_of_measurement: "W"

 

