- platform: mqtt
  name: "Hallway Motion Temp"
  state_topic: "smartthings/hall_motion/temperature"
  unit_of_measurement: "°F"

- platform: mqtt
  name: "Hallway Motion Temp 2"
  state_topic: "smartthings/hall_motion_2/temperature"
  unit_of_measurement: "°F"
