- platform: darksky
  api_key: eccf5f65e6dce657df3792d7e362f0db
  forecast:
    - 0
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - temperature
    - apparent_temperature
    - humidity
    - temperature_high
    - temperature_low

- platform: template
  sensors:
    timeday:
      value_template: >-
        {% if is_state('binary_sensor.house_wake_for_work', 'on') or is_state('binary_sensor.house_weekend_wakeup', 'on') %}
          {{ "morning" }}
        {% elif is_state('binary_sensor.afternoon', 'on') %} 
          {{ "afternoon" }}
        {% elif is_state('binary_sensor.evening', 'on') %}
          {{ "evening" }}
        {% else %}
          {{ "night" }}
        {% endif %}

- platform: openhardwaremonitor
  host: 192.168.1.229
  
- platform: openhardwaremonitor
  host: 192.168.1.186

- platform: uptime
  unit_of_measurement: minutes

- platform: mqtt
  name: "Attic Temp"
  state_topic: "/Attic_Sensor/Attic/Temperature"
  unit_of_measurement: "°C"

- platform: mqtt
  name: "Attic Pressure"
  state_topic: "/Attic_Sensor/Attic/Pressure"
  unit_of_measurement: "hPa"

- platform: mqtt
  name: "Attic Humidity"
  state_topic: "/Attic_Sensor/Attic/Humidity"
  unit_of_measurement: "%"
  
- platform: random
  name: house_rand_0_100
  minimum: 0
  maximum: 100

- platform: flunearyou

- platform: radarr
  api_key: e9550bffc3584c27a8fadfea761e7167
  host: 192.168.1.3
  monitored_conditions:
    - upcoming
    - movies
    - status
  days: 7
  
- platform: sonarr
  api_key: f5daad9766934d8394b07efe7f501c52
  host: 192.168.1.3
  monitored_conditions:
    - upcoming
    - series
    - wanted
  days: 7

- platform: template
  sensors:
    hvac_target_humidity:
      unit_of_measurement: "%"
      value_template: >-
        {% if ((0.0049*states('sensor.dark_sky_overnight_low_temperature')|float+0.2668)*100) > states('input_number.hvac_humidity_max')|float %}
          {{ states('input_number.hvac_humidity_max')|float }}
        {% else %} 
          {{ (0.0049*states('sensor.dark_sky_overnight_low_temperature')|float+0.2668)*100 }}
        {% endif %}
  
- platform: template
  sensors:
    hvac_fan_state:
      value_template: >-
        {{ states.climate.hvac.attributes.fan }}

- platform: template
  sensors:
    hvac_current_humidity:
      unit_of_measurement: "%"
      value_template: >-
        {{ states.climate.hvac.attributes.current_humidity }}
  
- platform: deluge
  host: 192.168.1.3
  username: Fire
  password: Poop
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'
    
- platform: mqtt
  name: "VPN down"
  state_topic: "hawirelesslink/sensor/speedtest_download/state"
  unit_of_measurement: "Mbit/s"
  
- platform: mqtt
  name: "VPN up"
  state_topic: "hawirelesslink/sensor/speedtest_upload/state"
  unit_of_measurement: "Mbit/s"
  
- platform: zestimate
  api_key: !secret ZILLOW
  zpid: 
    - 24680932

- platform: template
  sensors:
    house_status:
      value_template: >-
        {% if is_state('binary_sensor.house_sts_occupants', 'on') %}
          {{ "Occupied" }}
        {% elif is_state('binary_sensor.house_sts_guest', 'on') %} 
          {{ "Guest mode" }}
        {% elif is_state('binary_sensor.house_sts_vacation', 'on') %}
          {{ "Vacation" }}
        {% else %}
          {{ "Away" }}
        {% endif %}
