- platform: mqtt
  name: "kitchen_leak"
  state_topic: "/Kitchen_Leak/moisture_sensor/Analog"

- platform: mqtt
  name: "kitchen_temp"
  state_topic: "/Kitchen_Leak/under_cabinet/Temperature"
  unit_of_measurement: "°C"
  
- platform: mqtt
  name: "kitchen_humidity"
  state_topic: "/Kitchen_Leak/under_cabinet/Humidity"
  unit_of_measurement: "%"
  
- platform: mqtt
  name: "kitchen_pressure"
  state_topic: "/Kitchen_Leak/under_cabinet/Pressure"
  unit_of_measurement: "P"
  
- platform: mqtt
  name: "kitchen_fan_state"
  state_topic: "zigbee2mqtt/0x0022a3000016d039"
  value_template: "{{ value_json.fan_mode }}"
  
- platform: mqtt
  name: "kitchen_fan_speed"
  state_topic: "zigbee2mqtt/0x0022a3000016d039"
  value_template: "{{ value_json.fan_mode }}"
  
