- platform: mqtt
  name: "kitchen_leak"
  state_topic: "/Kitchen_Leak/moisture_sensor/Analog"

- platform: mqtt
  name: "kitchen_temp"
  state_topic: "/Kitchen_Leak/under_cabinet/Temperature"
  unit_of_measurement: "°C"
  
- platform: mqtt
  name: "kitchen_humidity"
  state_topic: "/Kitchen_Leak/under_cabinet/Humidity"
  unit_of_measurement: "%"
  
- platform: mqtt
  name: "kitchen_pressure"
  state_topic: "/Kitchen_Leak/under_cabinet/Pressure"
  unit_of_measurement: "P"
  
- platform: mqtt
  name: "kitchen_fan_speed"
  state_topic: "hawirelesslink/fan/king_of_fans_inc_hdc52eastwindfan_0016d039_1_514/speed"
  
- platform: mqtt
  name: sliding_glass_door_temperature
  state_topic: "hawirelesslink/sensor/centralite_3315_s_0e4974b8_1_1026/state"
  unit_of_measurement: "°F"
  
- platform: mqtt
  name: garage_entry_temperature
  state_topic: "hawirelesslink/sensor/centralite_3320l_0e259d4b_1_1026/state"
  unit_of_measurement: "°F"
