- platform: mqtt
  name: "Bathroom Vent Temperature"
  state_topic: "/Attic_Sensor/Vent/Temperature"
  unit_of_measurement: "Â°C"

- platform: mqtt
  name: "Bathroom Vent Pressure"
  state_topic: "/Attic_Sensor/Vent/Pressure"
  unit_of_measurement: "P"

- platform: mqtt
  name: "Bathroom Vent Humidity"
  state_topic: "/Attic_Sensor/Vent/Humidity"
  unit_of_measurement: "%"

- platform: mqtt
  name: "Bathroom Vent VOC"
  state_topic: "/Attic_Sensor/Vent/Gas"
  unit_of_measurement: "Î©"

- platform: template
  sensors:
    main_bath_target_humidity:
      value_template: >-
        {% if is_state('binary_sensor.house_sts_dte_cheap', 'on') and is_state('binary_sensor.house_sts_hvac_cool_req', 'on') %}
          {{ 90 }}
        {% elif is_state('binary_sensor.house_sts_hvac_shut', 'off') or is_state('binary_sensor.house_sts_hvac_cool_req', 'on') %}
          {{ (states('sensor.hvac_humidity')|float+states('input_number.main_bath_humidity_thresh')|float) }}
        {% elif (states('sensor.hvac_humidity')|float+states('input_number.main_bath_humidity_thresh')|float) > (states('input_number.hvac_humidity_max'))|float %}
          {{ (states('input_number.hvac_humidity_max')|float+states('input_number.main_bath_humidity_thresh')|float) }}
        {% else %}
          {{ (states('sensor.hvac_target_humidity')|float+states('input_number.main_bath_humidity_thresh')|float) }}
        {% endif %}
      unit_of_measurement: "%"
