- platform: mqtt
  name: "Office Temperature"
  state_topic: "/Office/enviroment/Temperature"
  unit_of_measurement: "°C"

- platform: mqtt
  name: "Office Pressure"
  state_topic: "/Office/enviroment/Pressure"
  unit_of_measurement: "P"

- platform: mqtt
  name: "Office Humidity"
  state_topic: "/Office/enviroment/Humidity"
  unit_of_measurement: "%"
