- platform: template
  sensors:
    cedar_moisture_combine:
      unit_of_measurement: "%"
      value_template: >-
        {{ (states('sensor.soil_moisture_1')|float + states('sensor.soil_moisture_2')|float) /2 }}
        
- platform: template
  sensors:
    tree_moisture_combine:
      unit_of_measurement: "%"
      value_template: >-
        {{ (states('sensor.soil_moisture_3')|float + states('sensor.soil_moisture_4')|float) /2 }}
