- platform: template
  sensors:
    emi_room_motion:
      value_template: >-
        {{ is_state('sensor.emi_motion', 'on') }}
      delay_on:
        seconds: 1
      delay_off:
        minutes: 30
