- platform: mqtt # Garage door sensor
  state_topic: "/garage/garage_door_feedback/garage_door_feedback"
  name: "garage_door_bin_raw"
  payload_on: "1"
  payload_off: "0"
  force_update: true
  
- platform: template # Garage door sensor filtered
  sensors:
    garage_door_bin:
      value_template: >-
        {{ is_state('binary_sensor.garage_door_bin_raw', 'on') }}
      delay_on:
        seconds: 1
      delay_off:
        seconds: 1
