- platform: template
  sensors:
    hallway_motion_combine:
      value_template: >-
        {{ is_state('binary_sensor.hallway_motion', 'on')
           or is_state('binary_sensor.hallway_motion_2', 'on') }}
      delay_off:
        minutes: 5
        
- platform: mqtt
  name: "hallway_motion"
  state_topic: "smartthings/hall_motion/motion"
  payload_on: "active"
  payload_off: "inactive"
  retain: true

- platform: mqtt
  name: "hallway_motion_2"
  state_topic: "smartthings/hall_motion_2/motion"
  payload_on: "active"
  payload_off: "inactive"
  retain: true
