- platform: template
  sensors:
    house_sts_occupants:
      value_template: >-
        {{ is_state('group.occupants', 'home') }}
- platform: template
  sensors:
    house_sts_guest:
      value_template: >-
        {{ states.calendar.guest_mode_visitor.state == 'on'
           or states.calendar.guest_mode_date.state == 'on' }}
- platform: template
  sensors:
    house_sts_vacation:
      value_template: >-
        {{ states.calendar.vacation_mode.state == 'on' }}
- platform: template
  sensors:
    house_sts_incoming:
      value_template: >-
        {{ is_state('device_tracker.google_maps_116842525089175776476', 'homecoming')
           or is_state('device_tracker.google_maps_108379141181739394475', 'homecoming') }}
- platform: template
  sensors:
    house_sts_dte_cheap:
      value_template: >-
        {{ states.calendar.dte_cheap.state == 'on' }}
        
- platform: template
  sensors:
    house_sts_jayhawks:
      value_template: >-
        {{ states.calendar.football__kuathleticscom.state == 'on'
           or states.calendar.mens_basketball__kuathleticscom.state == 'on'
           or states.calendar.volleyball__kuathleticscom.state == 'on' }}

- platform: template
  sensors:
    house_boot_complete:
      value_template: >-
        {{ states('sensor.uptime')|float > 5 }}
