- platform: template
  sensors:
    kitchen_fan_state:
      value_template: >-
        {{ not is_state('sensor.kitchen_fan_speed', 'off') }}
        
- platform: mqtt # Sliding Glass Door
  state_topic: "hawirelesslink/binary_sensor/centralite_3315_s_0e4974b8_1_1280/state"
  name: sliding_glass_door_opened
  payload_on: "on"
  payload_off: "off"

- platform: mqtt # Garage Door Entry
  state_topic: "hawirelesslink/binary_sensor/centralite_3320l_0e259d4b_1_1280/state"
  name: garage_entry_opened
  payload_on: "on"
  payload_off: "off"
