#- platform: mqtt # Sliding Glass Door
#  state_topic: "hawirelesslink/binary_sensor/centralite_3315_s_0e4974b8_1_1280/state"
#  name: sliding_glass_door_opened
#  payload_on: "on"
#  payload_off: "off"
  
- platform: template
  sensors:
    sliding_glass_door_opened:
      friendly_name: "Sliding Glass Door"
      value_template: >-
        {{ is_state('binary_sensor.sliding_glass_door', 'on') }}

- platform: mqtt # Garage Door Entry
  state_topic: "hawirelesslink/binary_sensor/centralite_3320l_0e259d4b_1_1280/state"
  name: garage_entry_opened
  payload_on: "on"
  payload_off: "off"

- platform: mqtt # Kitchen fan state
  state_topic: "hawirelesslink/fan/king_of_fans_inc_hdc52eastwindfan_0016d039_1_514/state"
  name: kitchen_fan_state
  payload_on: "on"
  payload_off: "off"

- platform: mqtt # Kitchen motion
  state_topic: "hawirelesslink/sensor/jasco_products_26931_smart_motion_switch_burglar/state"
  name: kitchen_motion
  payload_on: "8"
  payload_off: "0"
