- platform: template
  sensors:
    main_bath_vent_needed:
      value_template: >-
        {{ (states('sensor.bathroom_vent_humidity')|float > states('sensor.main_bath_target_humidity')|float) and is_state('binary_sensor.main_bath_vent_motion','on') }}
      delay_off:
        minutes: 5
        
#- platform: template
#  sensors:
#    main_bath_vent_needed:
#      value_template: >-
#        {{ (states('sensor.bathroom_vent_humidity')|float > states('sensor.main_bath_target_humidity')|float
#           or is_state('light.main_bath_vent_light','on')) and is_state('binary_sensor.main_bath_vent_motion','on') }}
#      delay_off:
#        minutes: 5

  - platform: mqtt # Bath motion
    state_topic: "hawirelesslink/sensor/jasco_products_26931_smart_motion_switch_burglar_3/state"
    name: kitchen_motion
    payload_on: "8"
    payload_off: "0"


- platform: template
  sensors:
    main_bath_vent_motion:
      value_template: >-
        {{ is_state('binary_sensor.main_bath_motion','on') }}
      delay_off:
        minutes: 20
