- platform: mqtt
  state_topic: "/Office/motion_sensor/Switch"
  name: "off_sts_motion_raw"
  payload_on: "1"
  payload_off: "0"

- platform: template
  sensors:
    off_sts_motion:
      value_template: >-
        {{ is_state('binary_sensor.off_sts_motion_raw', 'on') }}
      delay_off:
        minutes: 15
