- platform: tod
  name: early_morning
  after: '05:30'
  before: '08:00'

- platform: tod
  name: morning
  after: '8:00'
  before: '12:00'

- platform: tod
  name: afternoon
  after: '12:00'
  before: sunset
  before_offset: '-01:00'
    
- platform: tod
  name: evening
  after: sunset
  after_offset: '-01:00'
  before: '23:59'

- platform: tod
  name: night
  after: '00:01'
  before: '05:30'

- platform: workday
  name: workday_raw
  country: US
  province: MI
  workdays: [mon, tue, wed, thu, fri]

- platform: template
  sensors:
    house_time_liz_work_exception:
      value_template: >-
        {{ as_timestamp(states.calendar.liz_work_exception.attributes.start_time) - as_timestamp(now()) > -60 and as_timestamp(states.calendar.liz_work_exception.attributes.start_time) - as_timestamp(now()) < 7200 }}

- platform: template
  sensors:
    house_time_workday_combine:
      value_template: >-
        {{ is_state('binary_sensor.workday_raw', 'on') 
           or is_state('binary_sensor.house_time_liz_work_exception', 'on')}}  

- platform: template
  sensors:
    work_wakeup_time:
      value_template: >-
        {{ is_state('binary_sensor.early_morning', 'on') 
           or is_state('binary_sensor.house_time_liz_work_exception', 'on')  }}  

- platform: template
  sensors:
    house_wake_for_work:
      value_template: >-
        {{ is_state('binary_sensor.house_time_workday_combine', 'on') 
           and is_state('binary_sensor.work_wakeup_time', 'on')  }}   
