- platform: template
  covers:
    garage_door:
      friendly_name: "Garage Door"
      value_template: "{{ is_state('binary_sensor.garage_door_bin', 'on') }}"
      open_cover:
        service: mqtt.publish
        data:
          {
            "topic": "/garage/gpio/16",
            "payload": "1"
          }
      close_cover:
        service: mqtt.publish
        data:
          {
            "topic": "/garage/gpio/16",
            "payload": "1"
          }
