- platform: template
  covers:
    garage_door:
      friendly_name: "Garage Door"
      value_template: "{{ is_state('binary_sensor.garage_door', 'on') }}"
      open_cover:
        service: script.garage_door_open
      close_cover:
        service: script.garage_door_close
