


light:
  - platform: esp32_rmt_led_strip
    chipset: WS2811
    pin: ${pin}
    num_leds: 768
    rgb_order: grb
    name: screen_led
    id: screen_led
    max_refresh_rate: 16ms
    internal: true


display:
  - platform: addressable_light
    id: led_matrix_32x16_display
    addressable_light_id: screen_led
    width: 32
    height: 24
    pixel_mapper: |-
      int iMatrixOffset = 0;
      if (y < 8) {
        iMatrixOffset = 0;
      } else if ( y >= 8 and y < 16 ) {
        iMatrixOffset = 256;
      } else {
        iMatrixOffset = 512;
      }
      if (x % 2 == 0) {
        return (x * 8) + (y % 8) + iMatrixOffset;
      }
      return (x * 8) + iMatrixOffset + (7 - (y % 8));
    rotation: 270°
    update_interval: 16ms
    pages:
      - id: page1    
        lambda: |-
          it.fill(COLOR_OFF);
      - id: page2    
        lambda: |-          
          it.image(0, 0, id(jayhawk));
      - id: page3    
        lambda: |-          
          it.image(0, 0, id(chiefs));

image:
  defaults:
    type: rgb
    transparency: alpha_channel
    resize: 32x24
  images:
    - file: "jayhawk.png"
      id: jayhawk
    - file: "chiefs.png"
      id: chiefs

switch:
  - platform: template
    name: "jayhawk"
    turn_on_action:
      - display.page.show: page2
      - component.update: screen_led
    turn_off_action:
      - display.page.show_next: page1
      - component.update: screen_led
  - platform: template
    name: "chiefs"
    turn_on_action:
      - display.page.show: page3
      - component.update: screen_led
    turn_off_action:
      - display.page.show_next: page1
      - component.update: screen_led
