sensor:   
  - platform: vl53l0x
    name: curtain_${index}_${motor}_sensor
    id: curtain_${index}_${motor}_sensor
    address: 0x3${motor}
    update_interval: 1s
    long_range: false
    enable_pin:
      max6956: max6956_1
      number: 8
      mode:
        output: true
    i2c_id: i2c_channel
    internal: false
  - platform: template
    name: curtain_${index}_${motor}_percent
    id: curtain_${index}_${motor}_percent
    lambda: |-
      return curtain_${index}_${motor}_sensor.state / (curtain_${index}_${motor}_max.state - curtain_${index}_${motor}_min.state);

binary_sensor:
  - platform: template
    name: curtain_${index}_${motor}_closed
    id: curtain_${index}_${motor}_closed
    lambda: |-
      if (curtain_${index}_${motor}_percent.state > 0.98) {
        return true;
      } else {
        return false;
      }
  - platform: template
    name: curtain_${index}_${motor}_open
    id: curtain_${index}_${motor}_open
    lambda: |-
      if (curtain_${index}_${motor}_percent.state < 0.02) {
        return true;
      } else {
        return false;
      }


number:
  - platform: template
    name: curtain_${index}_${motor}_max
    id: curtain_${index}_${motor}_max
    min: 0
    max: 5000
    restore_value: true
  - platform: template
    name: curtain_${index}_${motor}_min
    id: curtain_${index}_${motor}_min
    min: 0
    max: 5000
    restore_value: true


cover:
  - platform: feedback
    name: curtain_${index}_${motor}

    open_action:
      - switch.turn_on: mot${motor}go${index}
    open_duration: 2.1min
    open_endstop: curtain_${index}_${motor}_open

    close_action:
      - switch.turn_on: mot${motor}dir${index}
      - switch.turn_on: mot${motor}go${index}
    close_duration: 2min
    close_endstop: curtain_${index}_${motor}_closed

    stop_action:
      - switch.turn_on: mot${motor}dir${index}
      - switch.turn_on: mot${motor}go${index}
