sensor:   
  - platform: vl53l0x
    name: curtain_${index}_${motor}
    address: 0x3${motor}
    update_interval: 1s
    long_range: false
    enable_pin: out${motor}_${index}
    i2c_id: i2c_channel 
