  motorboarad: !include
    file: packages/motorboard.yaml
    vars:
      index: 0

ethernet:
  type: W5500
  clk_pin: GPIO14
  mosi_pin: GPIO12
  miso_pin: GPIO13
  cs_pin: GPIO21
  interrupt_pin: GPIO11
  reset_pin: GPIO10
  clock_speed: 25Mhz
