pca9685:
  -id: motor_controller${index}
  frequency: 500
  address: 0x4${index}

output:
  - platform: pca9685
    id: mot1en${index}
    channel: 0
  - platform: pca9685
    id: mot1dir{index}
    channel: 1
  - platform: pca9685
    id: mot2en{index}
    channel: 2
  - platform: pca9685
    id: mot2dir{index}
    channel: 3
  - platform: pca9685
    id: mot3en{index}
    channel: 4
  - platform: pca9685
    id: mot3dir{index}
    channel: 5
  - platform: pca9685
    id: mot4en{index}
    channel: 6
  - platform: pca9685
    id: mot4dir{index}
    channel: 7
  - platform: pca9685
    id: sleep{index}
    channel: 8
  - platform: pca9685
    id: out4{index}
    channel: 12
  - platform: pca9685
    id: out3{index}
    channel: 13
  - platform: pca9685
    id: out2{index}
    channel: 14
  - platform: pca9685
    id: out1{index}
    channel: 15
