

pcf8574:
  - id: 'pcf8574_hub_${index}'
    address: 0x2${index}
    pcf8575: false
    i2c_id: i2c_channel  

switch:
  - platform: gpio
    name: mot1go${index}
    id: mot1go${index}
    pin:
      pcf8574: pcf8574_hub_${index}
      number: 2
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: mot1back${index}
    id: mot1back${index}
    pin:
      pcf8574: pcf8574_hub_${index}
      number: 3
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: mot2go${index}
    id: mot2go${index}
    pin:
      pcf8574: pcf8574_hub_${index}
      number: 4
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: mot2back${index}
    id: mot2back${index}
    pin:
      pcf8574: pcf8574_hub_${index}
      number: 5
      mode:
        output: true
      inverted: true
