

pcf8574:
  - id: 'pcf8574_hub'
    address: 0x21
    pcf8575: true
    i2c_id: i2c_channel  

output:
  - platform: pcf8574
    id: mot1en_${index}
    channel: 0
  - platform: pcf8574
    id: mot1dir_${index}
    channel: 1
  - platform: pcf8574
    id: mot2en_${index}
    channel: 2
  - platform: pcf8574
    id: mot2dir_${index}
    channel: 3

switch:
  - platform: output
    name: mot1go${index}
    id: mot1go${index}
    output: mot1en_${index}
  - platform: output
    name: mot1dir${index}
    id: mot1dir${index}
    output: mot1dir_${index}
