packages:
  light_effects: !include 
    file: light_effects.yam
    vars:
      devicename: ${name}
light:
  - platform: partition
    name: ${name}
    id: ${name}
    segments:
      - id: ${parent}
        from: ${start}
        to: ${end}
