light:
  - platform: partition
    name: ${name}
    id: ${name}
    segments:
      - id: ${parent}
        from: ${start}
        to: ${end}
    effects:
      - addressable_fireworks:
          name: Fireworks
          update_interval: 32ms
          spark_probability: 75%
          use_random_color: true
          fade_out_rate: 125
      - addressable_twinkle:
          name: twinkle
          twinkle_probability: 10%
          progress_interval: 64ms
      - addressable_color_wipe:
          name: Christmas stripes
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              num_leds: 50
            - red: 0%
              green: 100%
              blue: 0%
              num_leds: 50
          add_led_interval: 100ms
          reverse: False
      - addressable_color_wipe:
          name: Independence Day
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              num_leds: 20
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 20
            - red: 0%
              green: 0%
              blue: 100%
              num_leds: 20
          add_led_interval: 33ms
          reverse: false
