packages:
  light_effects: !include 
    file: light_effects.yaml
    vars:
      devicename: ${name}
light:
  - platform: partition
    name: ${name}
    id: ${name}
    segments:
      - id: ${parent}
        from: ${start}
        to: ${end}
    effects:
      - addressable_twinkle:
          name: twinkle
          twinkle_probability: 10%
          progress_interval: 64ms
