packages:
  eth: !include ethernet.yaml

esphome:
  name: ${devicename}
  friendly_name: ${devicename}
  
  
esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz


# Enable logging
logger:
  hardware_uart: USB_SERIAL_JTAG


# Enable Home Assistant API
api:
  encryption:
    key: !secret ENC_KEY

ota:
  platform: esphome
  password: !secret OTA_PW
  
i2c:
   - id: i2c_channel
     sda: GPIO05
     scl: GPIO04
   - id: audio_i2c
     sda: GPIO08
     scl: GPIO18
