packages:
  eth: !include ethernet.yaml
  va_adf: !include 
    file: voice-adf-pipeline.yaml
    vars:
      devicename: ${devicename}
  voice: !include 
    file: voice.yaml
    vars:
      devicename: ${devicename}
  va_board: !include 
    file: va_board.yaml
    vars:
      devicename: ${devicename}

esphome:
  name: ${devicename}
  friendly_name: ${devicename}
  
esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    version: 4.4.8
    platform_version: 5.4.0
    sdkconfig_options:
      CONFIG_ESP32_S3_BOX_BOARD: "y"

psram:
  mode: octal
  speed: 80MHz


# Enable logging
logger:
  hardware_uart: USB_SERIAL_JTAG


# Enable Home Assistant API
api:
  encryption:
    key: !secret ENC_KEY

ota:
  platform: esphome
  password: !secret OTA_PW
  
i2c:
   - id: i2c_channel
     sda: GPIO05
     scl: GPIO04
   - id: audio_i2c
     sda: GPIO08
     scl: GPIO18
