packages:
  eth: !include ethernet.yaml
  va_adf: !include 
    file: voice_non-adf.yaml
    vars:
      devicename: ${devicename}
  voice: !include 
    file: voice.yaml
    vars:
      devicename: ${devicename}
  va_board: !include 
    file: va_board.yaml
    vars:
      devicename: ${devicename}

esphome:
  name: ${devicename}
  friendly_name: ${devicename}
  
esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz


# Enable logging
logger:
  hardware_uart: USB_CDC
  level: debug
  logs:
    voice_assistant: VERY_VERBOSE


# Enable Home Assistant API
api:
  encryption:
    key: !secret ENC_KEY

ota:
  platform: esphome
  password: !secret OTA_PW
  
i2c:
   - id: i2c_channel
     sda: GPIO05
     scl: GPIO04
   - id: audio_i2c
     sda: GPIO08
     scl: GPIO18
