packages:
  porchplot: !include 
    file: valve_remote.yaml
    vars:
      name: porch_plot_valve
  gardenplot: !include 
    file: valve_remote.yaml
    vars:
      name: garden_valve


sprinkler:
  - id: back_irr
    main_switch: "Backyard Irrigation"
    auto_advance_switch: "Auto advance BYI"
    multiplier_number: "Backyard Irrigation Multiplier"
    valves:
      - valve_switch: "Garden"
        run_duration: "Garden Valve Runtime"
        valve_switch_id: garden_valve
        pump_switch_id: irr_main_pump
      - valve_switch: "Porch Plot"
        run_duration: "Porch Plot Runtime"
        valve_switch_id: porch_plot_valve
        pump_switch_id: irr_main_pump

sensor:
  - platform: honeywellabp2_i2c
    pressure:
      name: "Tank Pressure"
      id: "tank_press"  
      min_pressure: 0
      max_pressure: 5
      transfer_function: "A"
    temperature:
      name: "Pressure Temp"
  - platform: template
    name: "Tank Height"
    id: tank_h        
    lambda: return (27.6799 * id(tank_press).state);
  - platform: template
    name: "Tank Volume"
    id: tank_vol
    lambda: return (4 * id(tank_per).state);
    device_class: volume_storage
  - platform: template
    name: "Tank Percentage"
    lambda: return (100 * id(tank_h).state / 40.55);
    id: tank_per
    device_class: humidity

# Individual outputs
switch:
  - platform: gpio
    name: "Rainbarrel Pump"
    id: irr_main_pump
    on_turn_on:
    - lambda: !lambda |-
        if (id(fert_swi).state) {
          id(irr_main_sol).turn_on();
        } else {
          id(irr_fert_sol).turn_on();
        }
    on_turn_off:
    - switch.turn_off: irr_main_sol
    - switch.turn_off: irr_fert_sol
    pin:
      pcf8574: pcf8574_hub
      # Use pin number 0
      number: 4
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true
    internal: true
  - platform: gpio
    name: "Rainbarrel Fert Sol"
    id: irr_fert_sol
    pin:
      pcf8574: pcf8574_hub
      # Use pin number 0
      number: 5
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true
    internal: true
  - platform: gpio
    name: "rainbarrel relay 3"
    pin:
      pcf8574: pcf8574_hub
      # Use pin number 0
      number: 6
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true
    internal: true
  - platform: gpio
    name: "Rainbarrel Sol"
    id: irr_main_sol
    pin:
      pcf8574: pcf8574_hub
      # Use pin number 0
      number: 7
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true
    internal: true
  - platform: template
    name: "Fertilizer Switch"
    id: fert_swi
    optimistic: true
      
pcf8574:
  - id: 'pcf8574_hub'
    address: 0x27
    pcf8575: false
