packages:
  porchplot: !include 
    file: valve_remote.yaml
    vars:
      name: porch_plot_valve
  gardenplot: !include 
    file: valve_remote.yaml
    vars:
      name: garden_valve
  fenceplot: !include 
    file: valve_remote.yaml
    vars:
      name: fence_valve
  porchrailplot: !include 
    file: valve_remote.yaml
    vars:
      name: porch_rail_valve
      
sprinkler:
  - id: back_irr
    main_switch: "Backyard Irrigation"
    auto_advance_switch: "Auto advance BYI"
    multiplier_number: "Backyard Irrigation Multiplier"
    valves:
      - valve_switch: "Garden"
        run_duration_number: "Garden time"
        valve_switch_id: garden_valve
        pump_switch_id: irr_main_pump
      - valve_switch: "Porch Plot"
        run_duration_number: "Porch plot time"
        valve_switch_id: porch_plot_valve
        pump_switch_id: irr_main_pump
      - valve_switch: "Porch Rail"
        run_duration_number: "Porch rail time"
        valve_switch_id: porch_rail_valve
        pump_switch_id: irr_main_pump
      - valve_switch: "Fence Plot"
        run_duration_number: "Fence plot time"
        valve_switch_id: fence_valve
        pump_switch_id: irr_main_pump


ads1115:
  - address: 0x48
sensor:
  - platform: ads1115
    device_class: "pressure"
    unit_of_measurement: "psi"
    multiplexer: 'A0_GND'
    gain: 6.144
    sample_rate: 16
    name: "Tank Pressure Raw"
    id: tank_press
    update_interval: 15s
    filters:
      - calibrate_linear:
          - 0.5 -> 0.0
          - 2.5 -> 2.5
          - 4.5 -> 5
      - median:
          window_size: 17
          send_every: 4
          send_first_at: 3
  - platform: template
    name: "Tank Height"
    id: tank_h
    device_class: "distance"
    unit_of_measurement: "in"        
    lambda: return (id(tank_press).state * 27.7076);
  - platform: template
    name: "Tank Volume"
    id: tank_vol
    unit_of_measurement: "gal"
    lambda: return (4 * id(tank_per).state);
    device_class: volume_storage
  - platform: template
    name: "Tank Percentage"
    lambda: return (100 * id(tank_h).state / 40.55);
    id: tank_per
    unit_of_measurement: "%"
  - platform: pulse_counter
    pin: GPIO18
    unit_of_measurement: 'gallon/min'
    name: 'Flow Rate'
    filters:
      - lambda: return x * (1.0 / (3.785 * 330.0));



# Individual outputs
switch:
  - platform: gpio
    name: "Rainbarrel Pump"
    id: irr_main_pump
    on_turn_on:
    - lambda: !lambda |-
        if (id(fert_swi).state) {
          id(irr_fert_sol).turn_on();
        } else {
          id(irr_main_sol).turn_on();
        }
    on_turn_off:
    - switch.turn_off: irr_main_sol
    - switch.turn_off: irr_fert_sol
    pin:
      pcf8574: pcf8574_hub
      # Use pin number 0
      number: 4
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true
    internal: true
  - platform: gpio
    name: "Rainbarrel Fert Sol"
    id: irr_fert_sol
    pin:
      pcf8574: pcf8574_hub
      # Use pin number 0
      number: 5
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true
    internal: true
  - platform: gpio
    name: "Rainbarrel Hose Fill"
    id: irr_barrel_fill
    pin:
      pcf8574: pcf8574_hub
      # Use pin number 0
      number: 7
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true
    internal: true
  - platform: gpio
    name: "Rainbarrel Sol"
    id: irr_main_sol
    pin:
      pcf8574: pcf8574_hub
      # Use pin number 0
      number: 6
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true
    internal: true
  - platform: template
    name: "Fertilizer Switch"
    id: fert_swi
    optimistic: true
      
pcf8574:
  - id: 'pcf8574_hub'
    address: 0x27
    pcf8575: false
