esphome:
  name: ${name}
  friendly_name: ${name}

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret AP
  password: !secret APPW
  
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret ENC_KEY

ota:
  platform: esphome
  password: !secret OTA_PW

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_1
    on_press:
      then:
        - light.toggle: ${name}_light

  - platform: status
    name: ${name}_status

output:
  - platform: gpio
    pin: GPIO12
    id: ${name}_relay

light:
  - platform: binary
    name: ${name}_light
    id: ${name}_light
    output: ${name}_relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
