packages:
  string_light: !include 
    file: packages/add_light.yaml
    vars:
      pin: GPIO48
      length: 12
      color_line: GRB
      name: ${devicename}_status

switch:
  - platform: template
    name: "Template Switch"
    turn_on_action:
      - micro_wake_word.start:
    turn_off_action:
      - micro_wake_word.stop:

sensor:
  - platform: bme280_i2c
    temperature:
      name: ${devicename}_Temperature
      oversampling: 16x
    pressure:
      name: ${devicename}_Pressure
    humidity:
      name: ${devicename}_Humidity
    address: 0x77
    update_interval: 60s
  - platform: veml7700
    address: 0x10
    update_interval: 60s
    ambient_light: ${devicename}_Ambient_Light
    full_spectrum: ${devicename}_Full_Spectrum
    infrared: ${devicename}_Infrared
    ambient_light_counts: ${devicename}_AMB_LIGHT_COUNT
    full_spectrum_counts: ${devicename}_FS_COUNT
