external_components:
  - source:
      type: git
      url: https://github.com/gnumpi/esphome_audio
      ref: main
    components: [ adf_pipeline, i2s_audio ]

i2s_audio:
  i2s_lrclk_pin: GPIO45
  i2s_bclk_pin: GPIO17
  i2s_mclk_pin: GPIO02
  id: i2s_shared
  access_mode: duplex

adf_pipeline:
  - platform: i2s_audio
    type: audio_out
    id: adf_i2s_out
    i2s_audio_id: i2s_shared
    i2s_dout_pin: GPIO15
    adf_alc: false
    dac:
      model: es8311
      address: 0x18
      i2c_id: audio_i2c
    sample_rate: 16000
    bits_per_sample: 16bit
    fixed_settings: true

  - platform: i2s_audio
    type: audio_in
    id: adf_i2s_in
    i2s_audio_id: i2s_shared
    i2s_din_pin: GPIO14
    pdm: false
    adc:
      model: es7210
      address: 0x40
      i2c_id: audio_i2c
    bits_per_sample: 16bit
    fixed_settings: true

microphone:
  - platform: adf_pipeline
    id: external_mic
    keep_pipeline_alive: true
    pipeline:
      - adf_i2s_in
      - resampler
      - self

media_player:
  - platform: adf_pipeline
    id: ${devicename}_media
    name: ${devicename}_media
    internal: false
    keep_pipeline_alive: true
    pipeline:
      - self
      - resampler
      - adf_i2s_out

