external_components:
  - source: github://pr#5230
    components: esp_adf
    refresh: 0s

esp_adf:

microphone:
  - platform: esp_adf
    id: external_mic

speaker:
  - platform: esp_adf
    id: ${devicename}_speaker

