packages:
  light_effects: !include
    file: light_effects.yaml
    vars:
      devicename: ${name}
  voice_light_effects: !include
    file: voice_light_effects.yaml
    vars:
      devicename: ${name}

light:
  - platform: esp32_rmt_led_strip
    chipset: WS2812
    pin: ${pin}
    num_leds: ${length}
    channel_colors: ${color_line}
    internal: true
    name: ${name}
    id: ${name}
    use_dma: false
    rmt_symbols: 96
