external_components:
  - source: github://pr#5230
    components: esp_adf

esp_adf:
  board: esp32s3box

speaker:
  - platform: esp_adf
    id: ${devicename}_speaker

microphone:
  - platform: esp_adf
    id: external_mic

voice_assistant:
  microphone: external_mic
  speaker: ${devicename}_speaker
  use_wake_word: true

micro_wake_word:
  models:
    - model: okay_nabu
  on_wake_word_detected:
    - voice_assistant.start:
    - light.turn_on:
        id: ${devicename}_status

switch:
  - platform: template
    name: "Template Switch"
    turn_on_action:
      - micro_wake_word.start:
    turn_off_action:
      - micro_wake_word.stop:
