external_components:
  - source: github://pr#5230
    components: esp_adf
    refresh: 0s

esp_adf:

speaker:
  - platform: esp_adf
    id: ${devicename}_speaker

microphone:
  - platform: esp_adf
    id: external_mic

voice_assistant:
  microphone: external_mic
  speaker: ${devicename}_speaker
  use_wake_word: true

micro_wake_word:
  models:
    - okay_nabu
  on_wake_word_detected:
    - voice_assistant.start:
    - light.turn_on:
        id: ${devicename}_status
