packages:
  light_effects: !include 
    file: light_effects.yaml
    vars:
      devicename: ${name}

light:
  - platform: esp32_rmt_led_strip
    chipset: WS2812
    pin: ${pin}
    num_leds: ${length}
    rgb_order: ${color_line}
    internal: true 
    rmt_symbols: 48
    use_dma: true
    name: ${name}
    id: ${name}
    effects:
      - addressable_color_wipe:
          name: voice_listen
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 3
              gradient: true
            - red: 0%
              green: 9%
              blue: 90%
              num_leds: 9
              gradient: true
          add_led_interval: 100ms
          reverse: False
      - addressable_color_wipe:
          name: voice_thinking
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 3
              gradient: true
            - red: 0%
              green: 9%
              blue: 90%
              num_leds: 3
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 3
              gradient: true
            - red: 0%
              green: 9%
              blue: 90%
              num_leds: 3
              gradient: true
          add_led_interval: 50ms
          reverse: False
      - addressable_color_wipe:
          name: voice_replying
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 3
              gradient: true
            - red: 0%
              green: 9%
              blue: 90%
              num_leds: 3
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 3
              gradient: true
            - red: 0%
              green: 9%
              blue: 90%
              num_leds: 3
              gradient: true
          add_led_interval: 50ms
          reverse: true
      - addressable_color_wipe:
          name: timer_tick
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 3
              gradient: true
            - red: 100%
              green: 0%
              blue: 0%
              num_leds: 3
          add_led_interval: 1s
          reverse: true
      - addressable_color_wipe:
          name: timer_ring
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 3
              gradient: true
            - red: 0%
              green: 90%
              blue: 9%
              num_leds: 3
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 3
              gradient: true
            - red: 0%
              green: 90%
              blue: 9%
              num_leds: 3
              gradient: true
          add_led_interval: 50ms
          reverse: false
