packages:
  light_effects: !include 
    file: light_effects.yaml
    vars:
      devicename: ${name}

light:
  - platform: esp32_rmt_led_strip
    chipset: WS2812
    pin: ${pin}
    num_leds: ${length}
    rgb_order: ${color_line}
    name: ${name}
    id: ${name}
    effects:
      - addressable_color_wipe:
          name: voice_listen
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 3
              gradient: true
            - red: 0%
              green: 9%
              blue: 90%
              num_leds: 9
              gradient: true
          add_led_interval: 100ms
          reverse: False
      - addressable_color_wipe:
          name: voice_thinking
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 3
              gradient: true
            - red: 0%
              green: 9%
              blue: 90%
              num_leds: 3
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 3
              gradient: true
            - red: 0%
              green: 9%
              blue: 90%
              num_leds: 3
              gradient: true
          add_led_interval: 50ms
          reverse: False
      - addressable_color_wipe:
          name: Christmas stripes
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              num_leds: 50
            - red: 0%
              green: 100%
              blue: 0%
      name: Rainbow
          lambda: |-

            if (initial_run) {
              it.all() = Color(0, 0, 0);
            }
            
            uint8_t led_change = 24; //(higher is more change) the difference in hue for each led down the strip
            float speed = 4; //(lower is faster) the speed the first led colour changes at (therefore affecting all)
            unsigned long time = millis() / speed;
            int repetitions = time / 1529;
            uint16_t hue = time - (1529 * repetitions);
            
            for (int i = 0; i < it.size(); i++) {
              if (hue >= 0 && hue < 255) {
                uint8_t green = hue;
                it[i] = Color(255, green, 0);
              } else if (hue >= 255 && hue < 510) {
                uint8_t red = hue - 255;
                it[i] = Color((255 - red), 255, 0);
              } else if (hue >= 510 && hue < 765) {
                uint8_t blue = hue - 510;
                it[i] = Color(0, 255, blue);
              } else if (hue >= 765 && hue < 1020) {
                uint8_t green = hue - 765;
                it[i] = Color(0, (255 - green), 255);
              } else if (hue >= 1020 && hue < 1275) {
                uint8_t red = hue - 1020;
                it[i] = Color(red, 0, 255);
              } else if (hue >= 1275 && hue < 1530) {
                uint8_t blue = hue - 1275;
                it[i] = Color(255, 0, (255 - blue));
              }
              hue+=led_change;
              if (hue >= 1530) {
                hue-=1530;
              }
            }
