voice_assistant:
  microphone: external_mic
  speaker: ${devicename}_speaker
  use_wake_word: false

micro_wake_word:
  microphone: external_mic
  models:
    - okay_nabu
  on_wake_word_detected:
    - voice_assistant.start:
    - light.turn_on:
        id: ${devicename}_status
