external_components:
  - source: github://rpatel3001/esphome@es7210
    components: [ es7210 ]

i2s_audio:
  i2s_lrclk_pin: GPIO45
  i2s_bclk_pin: GPIO17
  i2s_mclk_pin: GPIO02
  id: audio_bus

audio_dac:
  - platform: es8311
    id: es8311_dac
    bits_per_sample: 16bit
    sample_rate: 16000
    i2c_id: audio_i2c

es7210:
  i2c_id: audio_i2c

#speaker:
#  - platform: i2s_audio
#    i2s_audio_id: audio_bus
#    id: ${devicename}_speaker
#    i2s_dout_pin: GPIO15
#    dac_type: external
#    sample_rate: 16000
#    bits_per_sample: 16bit
#    channel: mono
#    audio_dac: es8311_dac

media_player:
  - platform: i2s_audio
    name: Media Player
    id: ext_speaker
    dac_type: external
    i2s_dout_pin: GPIO15

microphone:
  - platform: i2s_audio
    id: external_mic
    adc_type: external
    pdm: false
    i2s_din_pin: GPIO16
    bits_per_sample: 16bit


switch:
  - platform: template
    name: "Template Switch"
    turn_on_action:
      - micro_wake_word.start:
    turn_off_action:
      - micro_wake_word.stop:
