packages:
  voice_light_effects: !include
    file: voice_light_effects.yaml
    vars:
      devicename: ${name}
light:
  - platform: partition
    name: ${name}
    id: ${name}
    restore_mode: RESTORE_DEFAULT_OFF
    segments:
      - id: ${parent}
        from: ${start}
        to: ${end}
