- platform: template
  fans:
    emi_fan:
      friendly_name: Emi fan"
      value_template: "{{ states('binary_sensor.emi_fan_state') }}"
      speed_template: "{{ states('sensor.emi_fan_speed')|replace('\"','') }}"
      turn_on:
        service:  mqtt.publish
        data_template:
            topic: "/HAwirelesslink/return/fan/king_of_fans_inc_hbuniversalcfremote_0020d37b_1_514/state"
            payload: 'on'
      turn_off:
        service:  mqtt.publish
        data_template:
            topic: "/HAwirelesslink/return/fan/king_of_fans_inc_hbuniversalcfremote_0020d37b_1_514/state"
            payload: 'off'
      set_speed:
        service: mqtt.publish
        data_template:
            topic: "/HAwirelesslink/return/fan/king_of_fans_inc_hbuniversalcfremote_0020d37b_1_514/speed"
            payload: '{{ speed }}'
      speeds:
        - 'low'
        - 'medium'
        - 'high'
        - 'on'
        - 'auto'
        - 'smart'
        - 'off'
        
        
