- platform: wake_on_lan
  name: off_4k_mon
  mac_address: "a0:6a:44:23:f6:99"
  host: 192.168.1.221
  broadcast_address: 192.168.1.209

- platform: wake_on_lan
  name: off_computron3000
  mac_address: "40:16:7e:e8:dc:7b"
  host: 192.168.1.107

- platform: wake_on_lan
  name: off_frankenserver
  mac_address: "30:5a:3a:7b:8d:eb"
  host: 192.168.1.108

- platform : mqtt
  name: "Office Heater"
  state_topic: "/Office_Heater/relay/switch"
  command_topic: "/Office_Heater/gpio/12"
  payload_on: "1"
  payload_off: "0"
  retain: true

- platform : mqtt
  name: "Humidifier"
  state_topic: "/laundry_room/humidifier/Switch"
  command_topic: "/laundry_room/mcpgpio/3"
  state_on: "1"
  state_off: "0"
  payload_on: "0"
  payload_off: "1"
  retain: true
  
- platform : mqtt
  name: "laundry_room_litter_box"
  state_topic: "/laundry_room/litter_box/Switch"
  command_topic: "/laundry_room/mcpgpio/2"
  state_on: "1"
  state_off: "0"
  payload_on: "0"
  payload_off: "1"
  retain: true

- platform : mqtt
  name: "xmas_lights"
  state_topic: "hawirelesslink/switch/xmaslights/state"
  command_topic: "/HAwirelesslink/return/switch/xmaslights/state"
  state_on: "on"
  state_off: "off"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform : mqtt
  name: "main_bath_fan"
  state_topic: "hawirelesslink/switch/main_bath_fan/state"
  command_topic: "/HAwirelesslink/return/switch/main_bath_fan/state"
  state_on: "on"
  state_off: "off"
  payload_on: "on"
  payload_off: "off"
  retain: true
