esphomeyaml:
  name: garage
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret AP
  password: !secret APPW

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret OTA_PW

ota:
  password: !secret OTA_PW

i2c:
  sda: D2
  scl: D1
  scan: False
  
mcp23017:
  - id: 'mcp23017_hub'
    address: 0x20
    
ads1115:
  - address: 0x48
  - id: ads1115_1
  
ads1115:
  - address: 0x49
  - id: ads1115_2
  
sensor:
  - platform: bme280
    temperature:
      name: "Garage Temperature"
      oversampling: 16x
    pressure:
      name: "Garage Pressure"
    humidity:
      name: "Garage Humidity"
    address: 0x77
    update_interval: 60s
