esphomeyaml:
  name: master_bed_rgbw
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret AP
  password: !secret APPW

mqtt:
  broker: 192.168.1.243
  username: MQTT_UN
  password: MQTT_PW

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret AP_PW

ota:
  password: !secret OTA_PW

output:
  pin:
    number: D1
    inverted: True
    mode: OUTPUT

light:
  - platform: rgbw
    name: "Brett Headboard"
    red: D1
    green: D2
    blue: D3
    white: D4
  - platform: rgbw
    name: "Liz Headboard"
    red: D5
    green: D6
    blue: D7
    white: D8
