esphomeyaml:
  name: mini_aquarium
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: '!secret AP'
  password: '!secret APPW'

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: '!secret OTA_PW'

ota:
  password: '!secret OTA_PW'
