- platform: kodi
  name: projector_kodi
  host: 192.168.1.250
  username: !secret KODI_USR
  password: !secret KODI_PW

- platform: androidtv
  name: projector_shield
  host: 192.168.1.250
  adb_server_ip: 127.0.0.1
  adb_server_port: 5037
  
- platform: pjlink
  name: projector
  host: 192.168.1.177

- platform: universal
  name: livingroom_media
  children:
    - media_player.projector_kodi
    - media_player.projector_shield
    - media_player.projector
