esphomeyaml:
  name: backyard_bluetooth
  platform: ESP32
  board: esp32cam

wifi:
  ssid: !secret AP
  password: !secret APPW

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret AP_PW

ota:
  password: !secret OTA_PW
 
  
esp32_ble_tracker:

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  # Image settings
  name: back_esp
