substitutions:
  devicename: waveshare-test

packages:
  base_board: !include 
    file: packages/Waveshare-ESP32-S3-ETH-PoE.yaml
    vars:
      devicename: ${devicename}
  string_light: !include 
    file: packages/add_light.yaml
    vars:
      pin: GPIO16
      length: 825
      color_line: RGB
      name: rb_string
  string_light_part: !include 
    file: packages/partition_light.yaml
    vars:
      name: decklight
      parent: rb_string
      start: 1
      end: 428
  string_light_part2: !include 
    file: packages/partition_light.yaml
    vars:
      name: backyard_eave
      parent: rb_string
      start: 783
      end: 803
  irrigation: !include packages/rain_barrel_irrigation.yaml
  string_light_part3: !include 
    file: packages/partition_light.yaml
    vars:
      name: ext_back_window
      parent: rb_string
      start: 429
      end: 782
  
i2c:
   sda: GPIO21
   scl: GPIO17

sensor:
  - platform: bmp280_i2c
    temperature:
      name: "rainbarrel Temperature"
      oversampling: 16x
    pressure:
      name: "rainbarrel Pressure"
    address: 0x76
    update_interval: 60s 
