esphome:
  name: "emporiavuehome"
  friendly_name: Emporia Home Energy Monitor

#external_components:
#  - source: github://emporia-vue-local/esphome@vue3
#    components:
#      - emporia_vue
      
esp32:
  board: esp32dev
  framework:
    type: esp-idf
    
preferences:
  # the default of 1min is far too short--flash chip is rated
  # for approx 100k writes.
  flash_write_interval: "48h"   

api:
  encryption:
    key: !secret ENC_KEY

ota:
  platform: esphome
  password: !secret OTA_PW

logger:
  logs:
    sensor: INFO

ethernet:
  type: RTL8201
  mdc_pin: GPIO32
  mdio_pin: GPIO33
  clk_mode: GPIO0_IN

light:
  - platform: status_led
    id: wifi_led
    pin:
      number: 2
      ignore_strapping_warning: true
    restore_mode: RESTORE_DEFAULT_ON


i2c:
  sda: 5
  scl: 18
#  scan: false
#  frequency: 400kHz  # IMPORTANT: Handle Failed to read from sensor due to I2C error 3
#  timeout: 1ms # IMPORTANT: Handle Failed to read from sensor due to I2C error 3
  id: i2c_a

switch:
  - platform: restart
    name: Restart  

time:
  - platform: homeassistant
    id: homeassistant_time


