esphome:
  name: garage-sensor
  friendly_name: Garage Sensor

esp32:
  board: seeed_xiao_esp32c3
  variant: esp32c3
  framework:
    type: arduino

# Enable Home Assistant API
api:
  encryption:
    key: "thisisasecret:)"

ota:
  password: "thisisasecret:)"

wifi:
  ssid: !secret AP
  password: !secret APPW

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "thisisasecret:)"
    password: "thisisasecret:)"

captive_portal:

switch:
  - platform: gpio
    pin: 2
    name: "Garage poort open/dicht"
