esphome:
  name: garage-sensor
  friendly_name: Garage Sensor

esp32:
  board: seeed_xiao_esp32c3
  variant: esp32c3
  framework:
    type: arduino

# Enable Home Assistant API
api:
  encryption:
    key: !secret ENC_KEY

ota:
  password: !secret OTA_PW

wifi:
  ssid: !secret AP
  password: !secret APPW

switch:
  - platform: gpio
    pin: 2
    name: "Garage poort open/dicht"
