esphome:
  name: front_garden
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret AP
  password: !secret APPW
  power_save_mode: none

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret AP_PW

ota:
  password: !secret OTA_PW


i2c:
   sda: GPIO21
   scl: GPIO22
    
pcf8574:
  - id: 'pcf8574_hub'
    address: 0x27
    pcf8575: True
    
ads1115:
  - id: ads1115_1
    address: 0x48
  - id: ads1115_2
    address: 0x49
    
sensor:
  - platform: bme280
    temperature:
      name: front_garden_temp
      oversampling: 16x
    humidity:
      name: front_garden_humidity
    address: 0x76
    pressure:
      name: front_garden_pressure
    update_interval: 60s
  - platform: ads1115_1
    multiplexer: 'A0_GND'
    gain: 6.144
    name: "ADS1115 Channel A10-GND"
    internal: true
  - platform: ads1115_1
    multiplexer: 'A1_GND'
    gain: 6.144
    name: "ADS1115 Channel A11-GND"
    internal: true
  - platform: ads1115_1
    multiplexer: 'A2_GND'
    gain: 6.144
    name: "ADS1115 Channel A12-GND"
    internal: true
    - platform: ads1115_1
    multiplexer: 'A3_GND'
    gain: 6.144
    name: "ADS1115 Channel A13-GND"
    internal: true
  - platform: ads1115_1
    multiplexer: 'A0_GND'
    gain: 6.144
    name: "ADS1115 Channel A20-GND"
    internal: true
  - platform: ads1115_1
    multiplexer: 'A1_GND'
    gain: 6.144
    name: "ADS1115 Channel A21-GND"
    internal: true
  - platform: ads1115_1
    multiplexer: 'A2_GND'
    gain: 6.144
    name: "ADS1115 Channel A22-GND"
    internal: true
    - platform: ads1115_1
    multiplexer: 'A3_GND'
    gain: 6.144
    name: "ADS1115 Channel A23-GND"
    internal: true
  - platform: pulse_counter
    pin: 27
    name: "front_water_flow"
    icon: mdi:hydro-power
    unit_of_measurement: 'l/m'
    update_interval: 30s
    filters:
      - multiply: 0.0222
    
    
light:
  - platform: fastled_clockless
    chipset: WS2811
    pin: GPIO16
    num_leds: 1
    rgb_order: RGB
    name: "Livingroom Window Ext Light"
    id: front_garden
    
    
switch:
  - platform: gpio
    name: irr_master
    id: irr_master
    icon: mdi:watering-can
    pin:
      mcp23017: mcp23017_hub
      number: 1
      mode: OUTPUT
      inverted: true
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: irr_zone1
    icon: mdi:watering-can
    id: irr1
    pin:
      mcp23017: mcp23017_hub
      number: 2
      mode: OUTPUT
      inverted: true
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: irr_zone2
    icon: mdi:watering-can
    id: irr2
    pin:
      mcp23017: mcp23017_hub
      number: 3
      mode: OUTPUT
      inverted: true
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: irr_zone3
    icon: mdi:watering-can
    id: irr3
    pin:
      mcp23017: mcp23017_hub
      number: 4
      mode: OUTPUT
      inverted: true
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: irr_zone4
    icon: mdi:watering-can
    id: irr4
    pin:
      mcp23017: mcp23017_hub
      number: 5
      mode: OUTPUT
      inverted: true
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: irr_zone5
    icon: mdi:watering-can
    id: irr5
    pin:
      mcp23017: mcp23017_hub
      number: 6
      mode: OUTPUT
      inverted: true
    restore_mode: ALWAYS_OFF
