esphome:
  name: garage
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret AP
  password: !secret APPW
  use_address: 192.168.2.100

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret OTA_PW

ota:
  password: !secret OTA_PW

i2c:
  sda: 21
  scl: 22
  scan: False
  
mcp23017:
  - id: 'mcp23017_hub'
    address: 0x20
    
ads1115:
  - id: ads1115_1
    address: 0x48
  - id: ads1115_2
    address: 0x49  
  
sensor:
  - platform: bme280
    temperature:
      name: "Garage Temperature"
      oversampling: 16x
      id: temp
    pressure:
      name: "Garage Pressure"
    humidity:
      name: "Garage Humidity"
      id: hum
    address: 0x76
    update_interval: 60s
  - platform: ads1115
    multiplexer: 'A0_GND'
    ads1115_id: ads1115_1
    gain: 6.144
    name: "Soil Moisture 1"
  - platform: ads1115
    multiplexer: 'A1_GND'
    ads1115_id: ads1115_1
    gain: 6.144
    name: "Soil Moisture 2"
  - platform: ads1115
    multiplexer: 'A2_GND'
    ads1115_id: ads1115_1
    gain: 6.144
    name: "Soil Moisture 3"
  - platform: ads1115
    multiplexer: 'A3_GND'
    ads1115_id: ads1115_1
    gain: 6.144
    name: "Soil Moisture 4"
  - platform: ads1115
    multiplexer: 'A0_GND'
    ads1115_id: ads1115_2
    gain: 6.144
    name: "Soil Moisture 5"
  - platform: ads1115
    multiplexer: 'A1_GND'
    ads1115_id: ads1115_2
    gain: 6.144
    name: "Soil Moisture 6"
  - platform: ads1115
    multiplexer: 'A2_GND'
    ads1115_id: ads1115_2
    gain: 6.144
    name: "Soil Moisture 7"
  - platform: ads1115
    multiplexer: 'A3_GND'
    ads1115_id: ads1115_2
    gain: 6.144
    name: "Soil Moisture 8"
  - platform: pulse_counter
    pin: 34
    name: "water_flow"
    unit_of_measurement: 'l/m'
    filters:
      - multiply: 0.0222

    
switch:
  - platform: gpio
    name: garage_door_act
    id: garage_door_act
    pin:
      mcp23017: mcp23017_hub
      number: 0
      mode: OUTPUT
      inverted: True
      restore_mode: ALWAYS_OFF
  - platform: gpio
    name: irr_master
    pin:
      mcp23017: mcp23017_hub
      number: 1
      mode: OUTPUT
      id: MR
      inverted: true
      restore_mode: ALWAYS_OFF
  - platform: gpio
    name: irr_zone1
    pin:
      mcp23017: mcp23017_hub
      number: 2
      mode: OUTPUT
      inverted: true
      restore_mode: ALWAYS_OFF
    on_turn_on:
    - switch.turn_on: MR
    on_turn_off:
    - switch.turn_off: MR
  - platform: gpio
    name: irr_zone2
    pin:
      mcp23017: mcp23017_hub
      number: 3
      mode: OUTPUT
      inverted: true
      restore_mode: ALWAYS_OFF
    on_turn_on:
    - switch.turn_on: MR
    on_turn_off:
    - switch.turn_off: MR
  - platform: gpio
    name: irr_zone3
    pin:
      mcp23017: mcp23017_hub
      number: 4
      mode: OUTPUT
      inverted: true
      restore_mode: ALWAYS_OFF
    on_turn_on:
    - switch.turn_on: MR
    on_turn_off:
    - switch.turn_off: MR
  - platform: gpio
    name: irr_zone4
    pin:
      mcp23017: mcp23017_hub
      number: 5
      mode: OUTPUT
      inverted: true
      restore_mode: ALWAYS_OFF
    on_turn_on:
    - switch.turn_on: MR
    on_turn_off:
    - switch.turn_off: MR
  - platform: gpio
    name: irr_zone5
    pin:
      mcp23017: mcp23017_hub
      number: 6
      mode: OUTPUT
      inverted: true
      restore_mode: ALWAYS_OFF
    on_turn_on:
    - switch.turn_on: MR
    on_turn_off:
    - switch.turn_off: MR
  - platform: restart
    name: "Garage Board restart"
      
cover:
  - platform: template
    name: "Garage Door"
    lambda: |-
      if (id(gd_state).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - if:
          condition:
            binary_sensor.is_on: house_armed_state
          then:
            - switch.turn_off: garage_door_act
            - switch.turn_on: garage_door_act
            - delay: 0.5s
            - switch.turn_off: garage_door_act
    close_action:
      - if:
          condition:
            binary_sensor.is_on: gd_state
          then:
            - switch.turn_off: garage_door_act
            - switch.turn_on: garage_door_act
            - delay: 0.5s
            - switch.turn_off: garage_door_act
    optimistic: false
    assumed_state: false
    device_class: garage
    
esp32_camera:
  name: 'ttgocam01'
  external_clock:
    pin: GPIO32
    frequency: 20MHz
  i2c_pins:
    sda: GPIO13
    scl: GPIO12
  data_pins: [GPIO5, GPIO14, GPIO4, GPIO15, GPIO18, GPIO23, GPIO36, GPIO39]
  vsync_pin: GPIO27
  href_pin: GPIO25
  pixel_clock_pin: GPIO19
  resolution: 640x480
  idle_framerate: 0.01 fps

binary_sensor:
  - platform: gpio
    pin: 33
    name: "Garage Motion"
    device_class: moving
  - platform: homeassistant
    name: "garage_door"
    id: gd_state
    entity_id: binary_sensor.garage_door
  - platform: homeassistant
    name: "house_armed"
    id: house_armed_state
    entity_id: binary_sensor.house_armed

    
font:
  - file: "FFF_Tusj.ttf"
    id: my_font
    size: 6

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    rotation: 180°
    lambda: |-
      it.printf(0, 0, my_font, "Temperature: %.1f°C", id(temp).state);
      it.printf(0, 60, my_font, "Humidity: %.1f%%", id(hum).state);
