esphome:
  name: garage
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret AP
  password: !secret APPW

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret OTA_PW

ota:
  password: !secret OTA_PW

i2c:
  sda: 21
  scl: 22
  scan: False
  

    
esp32_camera:
  external_clock:
    pin: GPIO32
    frequency: 20MHz
  i2c_pins:
    sda: 13
    scl: 12
  data_pins: [5, 14, 4, 15, 18, 23, 36, 39]
  vsync_pin: 27
  href_pin: 25
  pixel_clock_pin: 9
  power_down_pin: 26
  name: garage_camera
  jpeg_quality: 10

binary_sensor:
  - platform: gpio
    pin: 33
    name: "Garage Motion"
    device_class: moving
    
font:
  - file: "FFF_Tusj.ttf"
    id: my_font
    size: 20

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-
      it.print(0, 0, my_font, "Hello World!");
