substitutions:
  devicename: closet

packages:
  base_board: !include 
    file: packages/Waveshare-ESP32-S3-ETH-PoE.yaml
    vars:
      devicename: ${devicename}
  string_light: !include 
    file: packages/add_light.yaml
    vars:
      pin: GPIO38
      length: 100
      color_line: RGB
      name: closet-strip

      length: 100
      color_line: RGB
      name: hall_ban
