substitutions:
  devicename: closet

packages:
  base_board: !include 
    file: packages/Waveshare-ESP32-S3-ETH-PoE.yaml
    vars:
      devicename: ${devicename}
  string_light: !include 
    file: packages/add_light.yaml
    vars:
      pin: GPIO38
      length: 101
      color_line: RGB
      name: closet-strip
  banister: !include 
    file: packages/partition_light.yaml
    vars:
      name: stove
      parent: closet-strip
      start: 1
      end: 100
