esphomeyaml:
  name: kitchen_leak
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret AP
  password: !secret APPW

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret AP_PW

ota:
  password: !secret OTA_PW
 
  
sensor:
  - platform: adc
    pin: A0
    name: "kitchen_leak_raw"
    id: "kitchen_leak_raw"
    unit_of_measurement: "V"
    filters:
      - multiply: 3.3
    internal: true

binary_sensor:
  - platform: template
    name: "kitchen_leak"
    device_class: moisture
    lambda: |-
      if (id(kitchen_leak_raw).state > 1) {
        // LEAK.
        return true;
      } else {
        // Nominal
        return false;
      }
