esphomeyaml:
  name: kitchen_leak
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret AP
  password: !secret APPW

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret AP_PW

ota:
  password: !secret OTA_PW
 
  
sensor:
  - platform: adc
    pin: A0
    name: "kitchen_leak"
    unit_of_measurement: "V"

