substitutions:
  devicename: kitchen_cabinet_eth_va

packages:
  va_board: !include 
    file: packages/poe_board_base_2.6.yaml
    vars:
      devicename: ${devicename}
  headboard: !include 
    file: packages/add_light.yaml
    vars:
      pin: GPIO48
      length: 200
      color_line: RGB
      name: kitchen_cabinet
  stove: !include 
    file: packages/partition_light.yaml
    vars:
      name: stove
      parent: 
      start: 80
      end: 99
  cabinet_top: !include 
    file: packages/partition_light.yaml
    vars:
      name: Cabinet Top
      parent: kitchen_cabinet
      start: 80
      end: 99
  cabinet_bottom: !include 
    file: packages/partition_light.yaml
    vars:
      name: Cabinet Bottom
      parent: kitchen_cabinet
      start: 80
      end: 99

light:
  - id: !extend kitchen_cabinet
    rmt_channel: 1
  - id: !extend Cabinet Top
    segments:
      - id: kitchen_cabinet
        from: 0
        to: 39
      - id: kitchen_cabinet
        from: 179
        to: 199
  - id: !extend Cabinet Bottom
    segments:
      - id: kitchen_cabinet
        from: 40
        to: 79
      - id: kitchen_cabinet
        from: 100
        to: 179

sensor:   
  - platform: bme280_i2c
    temperature:
      name: ${devicename}_ext_temp
      oversampling: 16x
    pressure:
      name: ${devicename}_ext_pressure
    address: 0x76
    i2c_id: i2c_channel
    update_interval: 60s  
