substitutions:
  devicename: kitchen_cabinet_eth_va

packages:
  base_board: !include 
    file: packages/poe_board_base_2.6.yaml
    vars:
      devicename: ${devicename}
  voice_board: !include 
    file: packages/va_board_2.0.yaml
    vars:
      devicename: ${devicename}
  headboard: !include 
    file: packages/add_light.yaml
    vars:
      pin: GPIO48
      length: 200
      color_line: RGB
      name: kitchen_cabinet
  stove: !include 
    file: packages/partition_light.yaml
    vars:
      name: stove
      parent: kitchen_cabinet
      start: 80
      end: 99
  cabinet_top: !include 
    file: packages/partition_light.yaml
    vars:
      name: cabinet_top
      parent: kitchen_cabinet
      start: 0
      end: 39
  cabinet_bottom: !include 
    file: packages/partition_light.yaml
    vars:
      name: cabinet_bottom
      parent: kitchen_cabinet
      start: 40
      end: 79

light:
  - id: !extend cabinet_top
    segments:
      - id: kitchen_cabinet
        from: 179
        to: 199
  - id: !extend cabinet_bottom
    segments:
      - id: kitchen_cabinet
        from: 100
        to: 179

sensor:   
  - platform: bme280_i2c
    temperature:
      name: ${devicename}_ext_temp
      oversampling: 16x
    pressure:
      name: ${devicename}_ext_pressure
    address: 0x76
    i2c_id: i2c_channel
    update_interval: 60s  
