esphome:
  name: lr-bt-sns
  friendly_name: lr-bt-sns
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32s3

esp32:
  board: esp32-s3-devkitc-1
  framework:
    version: recommended    
    type: arduino

# Enable logging
logger:
  hardware_uart: USB_CDC

# Enable Home Assistant API
api:
  encryption:
    key: !secret ENC_KEY

ota:
  platform: esphome
  password: !secret OTA_PW
 
time:
  - platform: homeassistant
    id: homeassistant_time
    on_time:
      - seconds: 0
        minutes: 0
        hours: 4
        then:
          - button.press: lrbtsnsreboot

button:
  - platform: restart
    name: "lrbtsnsreboot"
    id: "lrbtsnsreboot"
  
i2c:
   sda: GPIO05
   scl: GPIO04
   id: i2c_channel


ethernet:
  type: W5500
  clk_pin: GPIO11
  mosi_pin: GPIO9
  miso_pin: GPIO10
  cs_pin: GPIO12
  interrupt_pin: GPIO46
  reset_pin: GPIO3
  clock_speed: 25Mhz
  
esp32_ble_tracker:

sensor:
  - platform: bme280_i2c
    temperature:
      name: "lr-bt-sns Temperature"
      oversampling: 16x
    pressure:
      name: "lr-bt-sns Pressure"
    humidity:
      name: "lr-bt-sns Humidity"
    address: 0x76
    update_interval: 60s      
    
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:63:F7:31'
    temperature:
      name: "Hydrangea Temperature"
    moisture:
      name: "Hydrangea Moisture"
    illuminance:
      name: "Hydrangea Illuminance"
    conductivity:
      name: "Hydrangea Soil Conductivity"
    battery_level:
      name: "Hydrangea Battery Level"
  - platform: xiaomi_hhccjcy01
    mac_address: '5C:85:7E:12:D5:A6'
    temperature:
      name: "4 Temperature"
    moisture:
      name: "4 Moisture"
    illuminance:
      name: "4 Illuminance"
    conductivity:
      name: "4 Soil Conductivity"
  - platform: xiaomi_hhccjcy01
    mac_address: '5C:85:7E:12:D5:2E'
    temperature:
      name: "2 Temperature"
    moisture:
      name: "2 Moisture"
    illuminance:
      name: "2 Illuminance"
    conductivity:
      name: "2 Soil Conductivity"
  - platform: xiaomi_hhccjcy01
    mac_address: '5C:85:7E:12:D5:40'
    temperature:
      name: "3 Temperature"
    moisture:
      name: "3 Moisture"
    illuminance:
      name: "3 Illuminance"
    conductivity:
      name: "3 Soil Conductivity"

light:
  - platform: neopixelbus
    variant: WS2811
    pin: GPIO37
    num_leds: 200
    type: RGB
    name: fy_string
    id: fy_string
    effects:
      - addressable_fireworks:
          name: Fireworks
          update_interval: 32ms
          spark_probability: 75%
          use_random_color: true
          fade_out_rate: 125
      - addressable_twinkle:
          name: twinkle
          twinkle_probability: 10%
          progress_interval: 64ms
      - addressable_color_wipe:
          name: Christmas stripes
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              num_leds: 50
            - red: 0%
              green: 100%
              blue: 0%
              num_leds: 50
          add_led_interval: 100ms
          reverse: False
      - addressable_color_wipe:
          name: Independence Day
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              num_leds: 20
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 20
            - red: 0%
              green: 0%
              blue: 100%
              num_leds: 20
          add_led_interval: 33ms
          reverse: false
      - addressable_lambda:
          name: Blue Sparkle
          update_interval: 12ms
          lambda:
            static int state = 0;
      
            if (initial_run){
              state = 0;
      
              it.all() = ESPColor(0,0,255);
            } else {
      
              it.all() = ESPColor(0,0,255);
              for (int i = it.size() % 10; i > 0; i--) {
                int p = rand() % it.size();
                it[p] = ESPColor(255,255,255);
              }
            }
