esphome:
  name: mainbathvent  
esp8266:
  board: nodemcuv2

wifi:
  ssid: !secret AP
  password: !secret APPW
  power_save_mode: none

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: fp5cNg1T9MH2bIkvVBhpBbGKv+Y1j5zI7U0xOXPXPOQ=

ota:
  platform: esphome
  password: !secret OTA_PW


i2c:
   sda: GPIO4
   scl: GPIO5
    
time:
  - platform: homeassistant
    id: homeassistant_time
    on_time:
      - seconds: 0
        minutes: 0
        hours: 4
        then:
          - button.press: mainbathventreboot
  
button:
  - platform: restart
    name: "mainbathventreboot"
    id: "mainbathventreboot"
  
bme68x_bsec2_i2c:
  address: 0x77
  model: bme680
  operating_age: 28d
  sample_rate: LP
  supply_voltage: 3.3V
  
text_sensor:
  - platform: bme68x_bsec2
    iaq_accuracy:
      name: "Main Bath Vent Intake IAQ Accuracy"

sensor:
  - platform: bme68x_bsec2
    temperature:
      name: "Main Bath Vent Temperature"
    pressure:
      name: "Main Bath Vent Pressure"
    humidity:
      name: "Main Bath Vent Humidity"
    iaq:
      name: "Main Bath Vent IAQ"
    co2_equivalent:
      name: "Main Bath Vent CO2 Equivalent"
    breath_voc_equivalent:
      name: "Main Bath Vent Breath VOC Equivalent"

  - platform: bme280_i2c
    temperature:
      name: "Attic Temp"
      oversampling: 16x
    humidity:
      name: "Attic Humidity"
    address: 0x76
    pressure:
      name: "Attic Rack Pressure"
    update_interval: 60s
    
