esphomeyaml:
  name: master_bed_rgbw
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret AP
  password: !secret APPW
  power_save_mode: none

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret AP_PW

ota:
  password: !secret OTA_PW
 
output:
  - platform: esp8266_pwm
    id: BHWHT
    pin: D1
  - platform: esp8266_pwm
    id: BHBLU
    pin: D2
  - platform: esp8266_pwm
    id: BHGRN
    pin: D3
  - platform: esp8266_pwm
    id: BHRED
    pin: D4
  - platform: esp8266_pwm
    id: LHWHT
    pin: D5
  - platform: esp8266_pwm
    id: LHBLU
    pin: D6
  - platform: esp8266_pwm
    id: LHGRN
    pin: D7
  - platform: esp8266_pwm
    id: LHRED
    pin: D8
light:
  - platform: rgbw
    name: "Brett Headboard"
    red: BHRED
    green: BHGRN
    blue: BHBLU
    white: BHWHT
  - platform: rgbw
    name: "Liz Headboard"
    red: LHRED
    green: LHGRN
    blue: LHBLU
    white: LHWHT
