substitutions:
  devicename: master_headboard_eth_va

packages:
  base_board: !include 
    file: packages/poe_board_base_2.6.yaml
    vars:
      devicename: ${devicename}
  voice_board: !include 
    file: packages/va_board_2.0.yaml
    vars:
      devicename: ${devicename}
  headboard: !include 
    file: packages/add_light.yaml
    vars:
      pin: GPIO48
      length: 20
      color_line: RBG
      name: master_headboard
  brett: !include 
    file: packages/partition_light.yaml
    vars:
      name: brett_headboard
      parent: master_headboard
      start: 0
      end: 9
  liz: !include 
    file: packages/partition_light.yaml
    vars:
      name: liz_headboard
      parent: master_headboard
      start: 10
      end: 19

sensor:   
  - platform: bmp280_i2c
    temperature:
      name: ${devicename}_ext_temp
      oversampling: 16x
    pressure:
      name: ${devicename}_ext_pressure
    address: 0x76
    i2c_id: i2c_channel
    update_interval: 60s  
