esphome:
  name: mini_aquarium
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret AP
  password: !secret APPW

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret OTA_PW

ota:
  password: !secret OTA_PW

i2c:
  sda: D21
  scl: D22
  scan: False
  
  
sensor:
  - platform: adc
    pin: A0
    name: "water_prob_v"
    unit_of_measurement: "V"
  - platform: adc
    pin: A3
    name: "bed_prob_v"
    unit_of_measurement: "V"
  - platform: bme280
    temperature:
      name: "MiniTank Temperature"
      oversampling: 16x
      unit_of_measurement: "°C"
    pressure:
      name: "MiniTank Pressure"
      unit_of_measurement: "P"
    humidity:
      name: "MiniTank Humidity"
      unit_of_measurement: "%"
    address: 0x77
    update_interval: 60s
  - platform: tcs34725
    red_channel:
      name: "TCS34725 Red Channel"
    green_channel:
      name: "TCS34725 Green Channel"
    blue_channel:
      name: "TCS34725 Blue Channel"
    clear_channel:
      name: "TCS34725 Clear Channel"
    illuminance:
      name: "TCS34725 Illuminance"
    color_temperature:
      name: "TCS34725 Color Temperature"
    gain: 1x
    integration_time: 2.4ms
    address: 0x29
    update_interval: 60s
  - platform: homeassistant
    name: "Feeder Toggle"
    entity_id: sensor.feeder_toggle
      on_value_range:
        - above: 50.0
          then:
          - stepper.report_position:
              id: feeder
              position: 0
            # It's best to call set_target directly after report_position, so that the stepper doesn't move
          - stepper.set_target:
              id: feeder
              target: 0
          - stepper.set_target:
              id: feeder
              target: 1000
# Individual outputs
output:
  - platform: ledc
    id: 'R'
    pin: D8
  - platform: ledc
    id: 'G'
    pin: D9
  - platform: ledc
    id: 'B'
    pin: D10
  - platform: ledc
    id: 'W'
    pin: D11
  - platform: ledc
    id: 'Pump'
    pin: D3
  - platform: ledc
    id: 'Htr'
    frequency: 120
    pin: D4
  - platform: ledc
    id: 'Air'
    frequency: 120
    pin: D5
    
light:
  - platform: rgbw
    name: "Tank Light"
    red: R
    green: G
    blue: B
    white: W
  - platform: monochromatic
    name: "Bed Pump"
    output: 'Pump'
  - platform: monochromatic
    name: "Heater"
    output: 'Htr'
  - platform: monochromatic
    name: "Air Pump"
    output: 'Air'
    
stepper:
  - platform: a4988
    id: feeder
    step_pin: D0
    dir_pin: D1
    max_speed: 250 steps/s
    # Optional:
    sleep_pin: D2
    acceleration: inf
    deceleration: inf
