substitutions:
  devicename: nursery_window_controller
  motion_name: "nursery_motion"
  temp_name: "Nursery window temp"
  press_name: "Nursery window pressure"
  hum_name: "Nursery window humidity"
  lux_name: "Nursery light level"
  mot1_i_name: "Nursery moter1 current"
  mot1_p_name: "Nursery moter1 power"
  mot1_vdd_name: "Nursery moter1 vdd"
  mot1_sv_name: "Nursery moter1 shunt voltage"
  mot2_i_name: "Nursery moter2 current"
  mot2_p_name: "Nursery moter2 power"
  mot2_vdd_name: "Nursery moter2 vdd"
  mot2_sv_name: "Nursery moter2 shunt voltage"
  mot3_i_name: "Nursery moter3 current"
  mot3_p_name: "Nursery moter3 power"
  mot3_vdd_name: "Nursery moter3 vdd"
  mot3_sv_name: "Nursery moter3 shunt voltage"
  mot1_MS1_name: "Nursery M1MS1"
  mot1_MS2_name: "Nursery M1MS2"
  mot1_MS3_name: "Nursery M1MS3"
  mot2_MS1_name: "Nursery M2MS1"
  mot2_MS2_name: "Nursery M2MS2"
  mot2_MS3_name: "Nursery M2MS3"
  mot3_MS1_name: "Nursery M3MS1"
  mot3_MS2_name: "Nursery M3MS2"
  mot3_MS3_name: "Nursery M3MS3"
  blind_name: "Nursery_blind_step"
  curt1_name: "Nursery_curtain1_step"
  curt2_name: "Nursery_curtain2_step"

<<: !include window_blind_2xcurtain.conf
