substitutions:
  devicename: office_eth_va

packages:
  base_board: !include 
    file: packages/poe_board_base_2.6.yaml
    vars:
      devicename: ${devicename}
  voice_board: !include 
    file: packages/va_board_2.0.yaml
    vars:
      devicename: ${devicename}
  occupancy: !include 
    file: packages/LD2410.yaml
    vars:
      devicename: ${devicename}
  motorboarad: !include
    file: packages/curtain.yaml
    vars:
      index: 0

pcf8574:
  - id: 'pcf8574_hub'
    address: 0x20
    pcf8575: false
    i2c_id: i2c_channel

switch:
  - platform: output
    name: "mot1go"
    output: 'mot1en_0'
  - platform: output
    name: "mot1dir"
    output: 'mot1dir_0'


sensor:   
  - platform: bmp280_i2c
    temperature:
      name: ${devicename}_ext_temp
      oversampling: 16x
    pressure:
      name: ${devicename}_ext_pressure
    address: 0x76
    i2c_id: i2c_channel
    update_interval: 60s
    
binary_sensor:
  - platform: gpio
    name: ${devicename}_office_motion
    id: ${devicename}_office_motion
    device_class: motion
    pin:
      pcf8574: pcf8574_hub
      number: 0
      mode:
        input: true
    filters:
      - delayed_off: 300s
      - delayed_on: 5s
