substitutions:
  devicename: office_eth_va

packages:
  va_board: !include 
    file: packages/poe_board_base_2.6.yaml
    vars:
      devicename: ${devicename}
  string_light: !include 
    file: packages/add_light.yaml
    vars:
      pin: GPIO48
      length: 20
      color_line: GRB
      name: ${devicename}_other_strip


light:
  - id: !extend ${devicename}_other_strip
    rmt_channel: 1


sensor:   
  - platform: bmp280_i2c
    temperature:
      name: ${devicename}_ext_temp
      oversampling: 16x
    pressure:
      name: ${devicename}_ext_pressure
    address: 0x76
    i2c_id: i2c_channel
    update_interval: 60s  

binary_sensor:
  - platform: gpio
    pin: GPIO44
    name: "Office Motion"
    device_class: motion
    filters:
      delayed_off: 300s


    
