substitutions:
  devicename: office_eth_va

packages:
  va_board: !include 
    file: packages/poe_board_base_2.6.yaml
    vars:
      devicename: ${devicename}


sensor:   
  - platform: bmp280_i2c
    temperature:
      name: ${devicename}_ext_temp
      oversampling: 16x
    pressure:
      name: ${devicename}_ext_pressure
    address: 0x76
    i2c_id: i2c_channel
    update_interval: 60s  

binary_sensor:
  - platform: gpio
    pin: GPIO43
    name: "Office Motion"
    device_class: motion
    filters:
      invert:


    
