substitutions:
  devicename: poe_test_12v_va

packages:
  eth: !include packages/ethernet.yaml
  va_adf: !include 
    file: packages/voice_adf.yaml
    vars:
      devicename: ${devicename}
  voice: !include 
    file: packages/voice.yaml
    vars:
      devicename: ${devicename}
  va_board: !include 
    file: packages/va_board.yaml
    vars:
      devicename: ${devicename}

esphome:
  name: ${devicename}
  friendly_name: ${devicename}
  
esp32:
  board: esp32s3box
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_AUDIO_BOARD_CUSTOM: "y"
      CONFIG_ESP32_S3_BOX_3_BOARD: "y"
    components:
      - name: esp32_s3_box_3_board
        source: github://jesserockz/esp32-s3-box-3-board@main
        refresh: 0s

psram:
  mode: octal
  speed: 80MHz


# Enable logging
logger:
  hardware_uart: USB_CDC

# Enable Home Assistant API
api:
  encryption:
    key: !secret ENC_KEY

ota:
  platform: esphome
  password: !secret OTA_PW
  
i2c:
   sda: GPIO05
   scl: GPIO04
   id: i2c_channel   
