esphome:
  name: poemastertest
  friendly_name: Initial testing for poe
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32s3

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: recommended

i2s_audio:
  i2s_lrclk_pin: GPIO39
  i2s_bclk_pin: GPIO38
  i2s_mclk_pin: GPIO41

speaker:
  - platform: i2s_audio
    dac_type: external
    i2s_dout_pin: GPIO40
    mode: mono

microphone:
  - platform: i2s_audio
    id: external_mic
    adc_type: external
    i2s_din_pin: GPIO42
    pdm: false

uart:
  rx_pin: GPIO36
  tx_pin: GPIO37
  baud_rate: 9600
  stop_bits: 1
  data_bits: 8
  id: dist

#tx_pin: GPIO44

# Enable logging
logger:
  hardware_uart: USB_SERIAL_JTAG

# Enable Home Assistant API
api:
  encryption:
    key: !secret ENC_KEY

ota:
  platform: esphome
  password: !secret OTA_PW
 
esp32_ble_tracker:
#bluetooth_proxy:
  
i2c:
   sda: GPIO05
   scl: GPIO04
   id: i2c_channel


ethernet:
  type: W5500
  clk_pin: GPIO11
  mosi_pin: GPIO9
  miso_pin: GPIO10
  cs_pin: GPIO12
  interrupt_pin: GPIO46
  reset_pin: GPIO3
  clock_speed: 25Mhz
  
#esp32_ble_tracker:

sensor:
  - platform: bme280_i2c
    temperature:
      name: "poemastertest Temperature"
      oversampling: 16x
    pressure:
      name: "poemastertest Pressure"
    humidity:
      name: "poemastertest Humidity"
    address: 0x76
    update_interval: 60s
  - platform: "a02yyuw"
    name: "Distance"
    uart_id: dist
    filters:
      - throttle: 10s
      

