esphome:
  name: poemastertest
  friendly_name: Initial testing for poe
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32s3

esp32:
  board: esp32-s3-devkitc-1
  framework:
    version: recommended    
    type: esp-idf


# Enable logging
logger:
  hardware_uart: USB_SERIAL_JTAG

# Enable Home Assistant API
api:
  encryption:
    key: !secret ENC_KEY

ota:
  password: !secret OTA_PW
 
#esp32_ble_tracker:
#bluetooth_proxy:
  
i2c:
   sda: GPIO05
   scl: GPIO04
   id: i2c_channel


ethernet:
  type: W5500
  clk_pin: GPIO11
  mosi_pin: GPIO9
  miso_pin: GPIO10
  cs_pin: GPIO12
  interrupt_pin: GPIO46
  reset_pin: GPIO3
  clock_speed: 25Mhz

sensor:
  - platform: bme280_i2c
    temperature:
      name: "poemastertest Temperature"
      oversampling: 16x
    pressure:
      name: "poemastertest Pressure"
    humidity:
      name: "poemastertest Humidity"
    address: 0x76
    update_interval: 60s
  - platform: internal_temperature
    name: "poemastertest Internal Temperature"

light:
  - platform: esp32_rmt_led_strip
    chipset: WS2811
    pin: GPIO37
    num_leds: 30
    rmt_channel: 0
    type: GRB
    name: poetest
    id: poetest
    effects:
      - addressable_fireworks:
          name: Fireworks
          update_interval: 32ms
          spark_probability: 75%
          use_random_color: true
          fade_out_rate: 125
      - addressable_twinkle:
          name: twinkle
          twinkle_probability: 10%
          progress_interval: 64ms
      - addressable_color_wipe:
          name: Christmas stripes
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              num_leds: 50
            - red: 0%
              green: 100%
              blue: 0%
              num_leds: 50
          add_led_interval: 100ms
          reverse: False
