packages:
  string_light: !include 
    file: packages/add_light.yaml
    vars:
      pin: GPIO37
      length: 620
      color_line: RGB
      name: rb_string
  tree_light: !include 
    file: packages/add_light.yaml
    vars:
      pin: GPIO38
      length: 620
      color_line: RGB
      name: tree_string
  string_light_part: !include 
    file: packages/partition_light.yaml
    vars:
      name: decklight
      parent: rb_string
      start: 0
      end: 427

light:
  - id: !extend tree_string
    rmt_symbols: 96

esphome:
  name: rainbrarrel
  friendly_name: rainbarrel
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32s3

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf

ethernet:
  type: W5500
  clk_pin: GPIO11
  mosi_pin: GPIO9
  miso_pin: GPIO10
  cs_pin: GPIO12
  interrupt_pin: GPIO46
  reset_pin: GPIO3
  clock_speed: 25Mhz

# Enable logging
logger:
  hardware_uart: USB_CDC

# Enable Home Assistant API
api:
  encryption:
    key: !secret ENC_KEY

ota:
  platform: esphome
  password: !secret OTA_PW
uart:
  rx_pin: GPIO44
  tx_pin: GPIO43
  baud_rate: 9600
  id: dist
 
#esp32_ble_tracker:
#bluetooth_proxy:
  
i2c:
   sda: GPIO05
   scl: GPIO04
   id: i2c_channel

pcf8574:
  - id: 'pcf8574_hub'
    address: 0x27
    pcf8575: false

# Individual outputs
switch:
  - platform: gpio
    name: "rainbarrel relay 1"
    pin:
      pcf8574: pcf8574_hub
      # Use pin number 0
      number: 4
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "rainbarrel relay 2"
    pin:
      pcf8574: pcf8574_hub
      # Use pin number 0
      number: 5
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "rainbarrel relay 3"
    pin:
      pcf8574: pcf8574_hub
      # Use pin number 0
      number: 6
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "Rainbarrel Sol"
    pin:
      pcf8574: pcf8574_hub
      # Use pin number 0
      number: 7
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true
      
  
esp32_ble_tracker:

sensor:
  - platform: bme280_i2c
    temperature:
      name: "rainbarrel Temperature"
      oversampling: 16x
    pressure:
      name: "rainbarrel Pressure"
    humidity:
      name: "rainbarrel Humidity"
    address: 0x76
    update_interval: 60s   
  - platform: "a02yyuw"
    name: "Distance"
    id: raw_dist
    uart_id: dist
    filters:
      - exponential_moving_average:
          alpha: 0.1
          send_every: 15
      - clamp:
          min_value: 3
          max_value: 34
          ignore_out_of_range: true
  - platform: template
    name: "Tank Volume"
    id: tank_vol
    lambda: return 2.00 * ((34.75 - (id(raw_dist).state) * 0.0393701) / 34.75) * 55;
    device_class: volume_storage
  - platform: template
    name: "Tank Percentage"
    lambda: return (id(tank_vol).state / 110.00) * 100.00;
    device_class: humidity
              
