esphome:
  name: rainbrarrel
  friendly_name: rainbarrel
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32s3

esp32:
  board: esp32-s3-devkitc-1
  framework:
    version: recommended    
    type: arduino

# Enable logging
logger:
  hardware_uart: USB_CDC

# Enable Home Assistant API
api:
  encryption:
    key: !secret ENC_KEY

ota:
  platform: esphome
  password: !secret OTA_PW
uart:
  rx_pin: GPIO44
  tx_pin: GPIO43
  baud_rate: 9600
  stop_bits: 1
  data_bits: 8
  id: dist
 
#esp32_ble_tracker:
#bluetooth_proxy:
  
i2c:
   sda: GPIO05
   scl: GPIO04
   id: i2c_channel


ethernet:
  type: W5500
  clk_pin: GPIO11
  mosi_pin: GPIO9
  miso_pin: GPIO10
  cs_pin: GPIO12
  interrupt_pin: GPIO46
  reset_pin: GPIO3
  clock_speed: 25Mhz

pcf8574:
  - id: 'pcf8574_hub'
    address: 0x27
    pcf8575: false

# Individual outputs
switch:
  - platform: gpio
    name: "rainbarrel relay 1"
    pin:
      pcf8574: pcf8574_hub
      # Use pin number 0
      number: 4
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "rainbarrel relay 2"
    pin:
      pcf8574: pcf8574_hub
      # Use pin number 0
      number: 5
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "rainbarrel relay 3"
    pin:
      pcf8574: pcf8574_hub
      # Use pin number 0
      number: 6
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "Rainbarrel Sol"
    pin:
      pcf8574: pcf8574_hub
      # Use pin number 0
      number: 7
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true
      
  
esp32_ble_tracker:

sensor:
  - platform: bme280_i2c
    temperature:
      name: "rainbarrel Temperature"
      oversampling: 16x
    pressure:
      name: "rainbarrel Pressure"
    humidity:
      name: "rainbarrel Humidity"
    address: 0x76
    update_interval: 60s   
  - platform: "a02yyuw"
    name: "Distance"
    id: raw_dist
    uart_id: dist
    internal: true
  - exponential_moving_average:
      alpha: 0.1
      send_every: 60
  - platform: template
    name: "Tank Volume"
    id: tank_vol
    lambda: return 2 * (( * (34.75 - (id(raw_dist).state)) * 3.14 * 23.25 * 23.25) * 0.004329);
  - platform: template
    name: "Tank Volume"
    lambda: return ((id(raw_dist).state) / 110) * 100;
    

    
      

light:
  - platform: neopixelbus
    variant: WS2811
    pin: GPIO37
    num_leds: 428
    type: RGB
    name: decklight
    id: decklight
    effects:
      - addressable_fireworks:
          name: Fireworks
          update_interval: 32ms
          spark_probability: 75%
          use_random_color: true
          fade_out_rate: 125
      - addressable_twinkle:
          name: twinkle
          twinkle_probability: 10%
          progress_interval: 64ms
      - addressable_color_wipe:
          name: Christmas stripes
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              num_leds: 50
            - red: 0%
              green: 100%
              blue: 0%
              num_leds: 50
          add_led_interval: 100ms
          reverse: False
      - addressable_color_wipe:
          name: Independence Day
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              num_leds: 20
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 20
            - red: 0%
              green: 0%
              blue: 100%
              num_leds: 20
          add_led_interval: 33ms
          reverse: false
