homeassistant:
  customize:    

automation:
  - id: 'irrigattion'
    alias: irrigation
    trigger:
      - platform: calendar
        event: start
        entity_id: calendar.teamcarriger_gmail_com
    condition:
      - condition: template
        value_template: "{{ 'Irrigate' in trigger.calendar_event.summary }}"
    action:
      - if:
          - "{{ trigger.event == 'start' }}"
        then:
          - service: switch.turn_on
            entity_id: switch.rainbrarrel_backyard_irrigation
    mode: queued

