homeassistant:
  customize:    
    
    
automation:
  - alias: backyard_person_detected
    trigger: 
      platform: state
      entity_id: binary_sensor.backyard_person
      from: 'off'
      to: 'on'
    condition:
      - condition: state
        entity_id: lock.front_door
        state: locked
    action:
      - service: camera.snapshot
        data:
          entity_id: camera.backyard_last_person
          filename: /config/www/snapshot1.jpg


script:
  by_irrigation:
    alias: by_irrigation
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.rainbrarrel_rainbarrel_sol
      - delay: '00:05:00'
      - service: switch.turn_off
        data:
          entity_id: switch.rainbrarrel_rainbarrel_sol
