homeassistant:
  customize:
  
camera:
  - platform: mjpeg
    name: Backyard
    still_image_url: http://192.168.2.200:81/image/backyard?q=100&s=100
    mjpeg_url: http://192.168.2.200:81/mjpg/backyard/video.mjpg
    
  - name: Backyard Last Person
    platform: mqtt
    topic: frigate/backyard/person/snapshot
  - name: Backyard Last Car
    platform: mqtt
    topic: frigate/backyard/car/snapshot

plant:
  hydrangea:
    sensors:
      moisture: sensor.hydrangea_moisture
      temperature: sensor.hydrangea_temperature
      conductivity: sensor.hydrangea_soil_conductivity
      brightness: sensor.hydrangea_illuminance
    min_moisture: 20
    
binary_sensor:
  - name: backyard_person
    platform: mqtt
    state_topic: "frigate/backyard/person"
    device_class: motion
    availability_topic: "frigate/available"
    delay_off:
      minutes: 1
    
automation:
  - alias: backyard_person_detected
    trigger: 
      platform: state
      entity_id: binary_sensor.backyard_person
      from: 'off'
      to: 'on'
    condition:
      - condition: state
        entity_id: lock.front_door
        state: locked
    action:
      - service: camera.snapshot
        data:
          entity_id: camera.backyard_last_person
          filename: /config/www/snapshot1.jpg
      - delay: 5
      - service: notify.group_notify
        data:
          message: "Homie be up in your yard"
          data:
            image: "https://homeassistant.teamcarriger.club/local/snapshot1.jpg"


script:
  by_irrigation:
    alias: by_irrigation
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.irr_master
      - service: switch.turn_on
        data:
          entity_id: switch.irr_zone1
      - delay: '00:30:00'
      - service: switch.turn_off
        data:
          entity_id: switch.irr_master
      - service: switch.turn_off
        data:
          entity_id: switch.irr_zone1
      - delay: '00:30:00'
      - service: switch.turn_on
        data:
          entity_id: switch.irr_master
      - service: switch.turn_on
        data:
          entity_id: switch.irr_zone2
      - delay: '00:30:00'
      - service: switch.turn_off
        data:
          entity_id: switch.irr_master
      - service: switch.turn_off
        data:
          entity_id: switch.irr_zone2
      - delay: '00:30:00'
      - service: switch.turn_on
        data:
          entity_id: switch.irr_master
      - service: switch.turn_on
        data:
          entity_id: switch.irr_zone1
      - delay: '00:30:00'
      - service: switch.turn_off
        data:
          entity_id: switch.irr_master
      - service: switch.turn_off
        data:
          entity_id: switch.irr_zone1
      - delay: '00:30:00'
      - service: switch.turn_on
        data:
          entity_id: switch.irr_master
      - service: switch.turn_on
        data:
          entity_id: switch.irr_zone2
      - delay: '00:30:00'
      - service: switch.turn_off
        data:
          entity_id: switch.irr_master
      - service: switch.turn_off
        data:
          entity_id: switch.irr_zone2
      - delay: '00:30:00'
      - service: switch.turn_on
        data:
          entity_id: switch.irr_master
      - service: switch.turn_on
        data:
          entity_id: switch.irr_zone1
      - delay: '00:30:00'
      - service: switch.turn_off
        data:
          entity_id: switch.irr_master
      - service: switch.turn_off
        data:
          entity_id: switch.irr_zone1
      - delay: '00:30:00'
      - service: switch.turn_on
        data:
          entity_id: switch.irr_master
      - service: switch.turn_on
        data:
          entity_id: switch.irr_zone2
      - delay: '00:30:00'
      - service: switch.turn_off
        data:
          entity_id: switch.irr_master
      - service: switch.turn_off
        data:
          entity_id: switch.irr_zone2
      - delay: '00:30:00'
