homeassistant:
  customize:
  
camera:
  - platform: mjpeg
    name: Backyard
    still_image_url: http://192.168.2.200:81/image/backyard?q=100&s=100
    mjpeg_url: http://192.168.2.200:81/mjpg/backyard/video.mjpg

plant:
  hydrangea:
    sensors:
      moisture: sensor.hydrangea_moisture
      temperature: sensor.hydrangea_temperature
      conductivity: sensor.hydrangea_soil_conductivity
      brightness: sensor.hydrangea_illuminance
    min_moisture: 20

script:
  by_irrigation:
    alias: by_irrigation
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.irr_master
      - service: switch.turn_on
        data:
          entity_id: switch.irr_zone1
      - delay: '00:30:00'
      - service: switch.turn_off
        data:
          entity_id: switch.irr_master
      - service: switch.turn_off
        data:
          entity_id: switch.irr_zone1
      - delay: '00:30:00'
      - service: switch.turn_on
        data:
          entity_id: switch.irr_master
      - service: switch.turn_on
        data:
          entity_id: switch.irr_zone2
      - delay: '00:30:00'
      - service: switch.turn_off
        data:
          entity_id: switch.irr_master
      - service: switch.turn_off
        data:
          entity_id: switch.irr_zone2
      - delay: '00:30:00'
      - service: switch.turn_on
        data:
          entity_id: switch.irr_master
      - service: switch.turn_on
        data:
          entity_id: switch.irr_zone1
      - delay: '00:30:00'
      - service: switch.turn_off
        data:
          entity_id: switch.irr_master
      - service: switch.turn_off
        data:
          entity_id: switch.irr_zone1
      - delay: '00:30:00'
      - service: switch.turn_on
        data:
          entity_id: switch.irr_master
      - service: switch.turn_on
        data:
          entity_id: switch.irr_zone2
      - delay: '00:30:00'
      - service: switch.turn_off
        data:
          entity_id: switch.irr_master
      - service: switch.turn_off
        data:
          entity_id: switch.irr_zone2
      - delay: '00:30:00'
      - service: switch.turn_on
        data:
          entity_id: switch.irr_master
      - service: switch.turn_on
        data:
          entity_id: switch.irr_zone1
      - delay: '00:30:00'
      - service: switch.turn_off
        data:
          entity_id: switch.irr_master
      - service: switch.turn_off
        data:
          entity_id: switch.irr_zone1
      - delay: '00:30:00'
      - service: switch.turn_on
        data:
          entity_id: switch.irr_master
      - service: switch.turn_on
        data:
          entity_id: switch.irr_zone2
      - delay: '00:30:00'
      - service: switch.turn_off
        data:
          entity_id: switch.irr_master
      - service: switch.turn_off
        data:
          entity_id: switch.irr_zone2
      - delay: '00:30:00'
