homeassistant:
  customize:
  
light:
  - platform: group
    name: shelf_light_combine
    entities:
      - light.basement_light_00
      - light.basement_light_01
      - light.basement_light_02
      - light.basement_light_03
  - platform: switch
    name: basement_stair_light
    entity_id: switch.basement_stair_light
      
binary_sensor:
  - platform: mqtt # 
    state_topic: "hawirelesslink/sensor/jasco_products_26931_smart_motion_switch_burglar_7/state"
    name: basement_stair_motion
    payload_on: "8"
    payload_off: "0"
    device_class: motion
    
roomba:
  - host: 192.168.2.121
    blid: secret! megamaid_un
    password: secret! megamaid_pw
  
media_player:
  - platform: kodi
    name: projector_kodi
    host: 192.168.3.3
    username: !secret KODI_USR
    password: !secret KODI_PW

  - platform: androidtv
    name: projector_shield
    host: 192.168.3.3
    adb_server_ip: 127.0.0.1
    adb_server_port: 5037
    
  - platform: onkyo
    host: 192.168.3.4
    name: projector_receiver
    sources:
      strm_box: 'HTPC'
      game: "Nintendo Switch"
      
  - platform: universal
    name: projector_media
    children:
      - media_player.projector_kodi
      - media_player.projector_shield
      - media_player.projector_receiver
    commands:
      turn_on:
        service: script.turn_on
        entity_id: script.turn_on_projector
      turn_off:
        service: script.turn_on
        entity_id: script.turn_off_projector
      select_source:
        service: media_player.select_source
        data:
          entity_id: media_player.projector_receiver
          source: '{{ source }}'
    attributes:
      state: media_player.projector_receiver
      source: media_player.projector_receiver|source
      source_list: media_player.projector_receiver|source_list

switch:
  platform: telnet
  switches:
    projector:
      resource: 192.168.3.10
      port: 23
      command_on: "\x7e\x30\x30\x30\x30\x20\x31\x0d"
      command_off: "\x7e\x30\x30\x30\x30\x20\x32\x0d"
  
automation:
  - alias: turn_off_projector
    initial_state: 'off'
    trigger:
    - platform: time
      at: '1:30:00'
    condition: []
    action:
    - data:
        entity_id: switch.projector
      service: switch.turn_off
      
  - id: sync_hall_light
    alias: "Sync Zwave lights in basement stairwell"
    initial_state: 'on'
    mode: single
    trigger:
      - platform: state
        entity_id: 
          - switch.basement_stair_light
          - switch.basement_stair_remote
    action:
      - choose:
        - conditions:
            - condition: state
              entity_id: switch.basement_stair_light
              state: 'on'
            - condition: template
              value_template: "{{ state_attr(trigger.entity_id, 'friendly_name') == states.switch.basement_stair_light.attributes.friendly_name }}"
          sequence:
            - service: switch.turn_on
              entity_id: switch.basement_stair_remote
            - delay:
                milliseconds: 500

        - conditions:
            - condition: state
              entity_id: switch.basement_stair_remote
              state: 'on'
            - condition: template
              value_template: "{{ state_attr(trigger.entity_id, 'friendly_name') ==  states.switch.basement_stair_remote.attributes.friendly_name }}"
          sequence:
            - service: switch.turn_on
              entity_id: switch.basement_stair_light
            - delay:
                milliseconds: 500

        - conditions:
            - condition: state
              entity_id: switch.basement_stair_light
              state: 'off'
            - condition: template
              value_template: "{{ state_attr(trigger.entity_id, 'friendly_name') == states.switch.basement_stair_light.attributes.friendly_name }}"
          sequence:
            - service: switch.turn_off
              entity_id: switch.basement_stair_remote
            - delay:
                milliseconds: 500

        - conditions:
            - condition: state
              entity_id: switch.basement_stair_remote
              state: 'off'
            - condition: template
              value_template: "{{ state_attr(trigger.entity_id, 'friendly_name') == states.switch.basement_stair_remote.attributes.friendly_name }}"
          sequence:
            - service: switch.turn_off
              entity_id: switch.basement_stair_light
            - delay:
                milliseconds: 500
      
      
script:
  turn_off_projector:
    sequence:
      service: switch.turn_off
      data:
        entity_id: switch.projector
      service: media_player.turn_off
      data:
        entity_id: media_player.projector_receiver
      service: media_player.turn_off
      data:
        entity_id: media_player.projector_shield
  turn_on_projector:
    sequence:
      service: switch.turn_on
      data:
        entity_id: switch.projector
      service: media_player.turn_on
      data:
        entity_id: media_player.projector_receiver
      service: media_player.turn_on
      data:
        entity_id: media_player.projector_shield
