homeassistant:
  customize:
    light.basemet_dimmer:
      friendly_name: Basement Dimmer
    light.shelf_light_combine:
      friendly_name: Basement Shelf Light
    switch.basement_stair_light:
      friendly_name: Basement Stair Light
      
light:
  - platform: group
    name: shelf_light_combine
    entities:
      - light.basement_light_00
      - light.basement_light_01
      - light.basement_light_02
      - light.basement_light_03
  - platform: switch
    name: basement_stair_light
    entity_id: switch.basement_stair_light
      
    
#roomba:
#  - host: 192.168.2.121
#    blid: secret! megamaid_un
#    password: secret! megamaid_pw
  
media_player:
  - platform: kodi
    name: projector_kodi
    host: 192.168.3.3
    username: !secret KODI_USR
    password: !secret KODI_PW

#  - platform: androidtv
#    name: projector_shield
#    host: 192.168.3.3
#    adb_server_ip: 127.0.0.1
#    adb_server_port: 5037
    
  - platform: onkyo
    host: 192.168.3.4
    name: projector_receiver
    sources:
      strm_box: 'HTPC'
      game: "Nintendo Switch"
      
  - platform: universal
    name: projector_media
    children:
      - media_player.projector_kodi
      - media_player.projector_shield
      - media_player.projector_receiver
    commands:
      turn_on:
        service: script.turn_on
        entity_id: script.turn_on_projector
      turn_off:
        service: script.turn_on
        entity_id: script.turn_off_projector
      select_source:
        service: media_player.select_source
        data:
          entity_id: media_player.projector_receiver
          source: '{{ source }}'
    attributes:
      state: media_player.projector_receiver
      source: media_player.projector_receiver|source
      source_list: media_player.projector_receiver|source_list

switch:
  platform: telnet
  switches:
    projector:
      resource: 192.168.3.10
      port: 23
      command_on: "\x7e\x30\x30\x30\x30\x20\x31\x0d"
      command_off: "\x7e\x30\x30\x30\x30\x20\x32\x0d"
  
automation:
  - alias: turn_off_projector
    initial_state: 'off'
    trigger:
    - platform: time
      at: '1:30:00'
    condition: []
    action:
    - data:
        entity_id: switch.projector
      service: switch.turn_off
      
      
script:
  turn_off_projector:
    sequence:
      service: switch.turn_off
      data:
        entity_id: switch.projector
      service: media_player.turn_off
      data:
        entity_id: media_player.projector_receiver
      service: media_player.turn_off
      data:
        entity_id: media_player.projector_shield
  turn_on_projector:
    sequence:
      service: switch.turn_on
      data:
        entity_id: switch.projector
      service: media_player.turn_on
      data:
        entity_id: media_player.projector_receiver
      service: media_player.turn_on
      data:
        entity_id: media_player.projector_shield
