homeassistant:
  customize:
  
light:
  - platform : mqtt
    name: "basemet_dimmer"
    state_topic: "hawirelesslink/light/basement_dim/state"
    command_topic: "/HAwirelesslink/return/light/basement_dim/state"
    brightness_state_topic: "hawirelesslink/light/basement_dim/brightness"
    brightness_command_topic: "/HAwirelesslink/return/light/basement_dim/brightness"
    payload_on: "on"
    payload_off: "off"
    retain: false
    
  - platform : mqtt
    name: "basement_stair_light"
    state_topic: "hawirelesslink/switch/jasco_products_26931_smart_motion_switch_switch_7/state"
    command_topic: "/HAwirelesslink/return/switch/jasco_products_26931_smart_motion_switch_switch_7/state"
    payload_on: "on"
    payload_off: "off"
    retain: false
    
  - platform: group
    name: shelf_light_combine
    entities:
      - light.basement_light_00
      - light.basement_light_01
      - light.basement_light_02
      - light.basement_light_03
      
binary_sensor:
  - platform: mqtt # 
    state_topic: "hawirelesslink/sensor/jasco_products_26931_smart_motion_switch_burglar_7/state"
    name: basement_stair_motion
    payload_on: "8"
    payload_off: "0"
    device_class: motion
  
media_player:
  - platform: kodi
    name: projector_kodi
    host: 192.168.3.3
    username: !secret KODI_USR
    password: !secret KODI_PW

  - platform: androidtv
    name: projector_shield
    host: 192.168.3.3
    adb_server_ip: 127.0.0.1
    adb_server_port: 5037

  - platform: universal
    name: projector_media
    children:
      - media_player.projector_kodi
      - media_player.projector_shield
      - media_player.projector
  
switch:
  platform: telnet
  switches:
    projector:
      resource: 192.168.3.10
      port: 23
      command_on: "\x7e\x30\x30\x30\x30\x20\x31\x0d"
      command_off: "\x7e\x30\x30\x30\x30\x20\x32\x0d"
  
automation:
  - alias: turn_off_projector
    initial_state: 'off'
    trigger:
    - platform: time
      at: '1:30:00'
    condition: []
    action:
    - data:
        entity_id: switch.projector
      service: switch.turn_off
      

