homeassistant:
  customize:
  
light:
  - platform : mqtt
    name: "basemet_dimmer"
    state_topic: "hawirelesslink/light/basement_dim/state"
    command_topic: "/HAwirelesslink/return/light/basement_dim/state"
    brightness_state_topic: "hawirelesslink/light/basement_dim/brightness"
    brightness_command_topic: "/HAwirelesslink/return/light/basement_dim/brightness"
    payload_on: "on"
    payload_off: "off"
    retain: true
  
media_player:
  - platform: kodi
    name: projector_kodi
    host: 192.168.3.3
    username: !secret KODI_USR
    password: !secret KODI_PW

  - platform: androidtv
    name: projector_shield
    host: 192.168.3.3
    adb_server_ip: 127.0.0.1
    adb_server_port: 5037

  - platform: pjlink
    name: projector
    host: 192.168.3.10

  - platform: universal
    name: projector_media
    children:
      - media_player.projector_kodi
      - media_player.projector_shield
      - media_player.projector
