
automation:
  - id: va_thunderstorm_sounds
    alias: va_thunderstorm_sounds
    mode: parallel
    triggers:
      - trigger: conversation
        command: "play thunderstorm sounds"
    conditions: []
    actions:
      - action: media_player.turn_on
        target:
          entity_id: 'media_player.{{ area_name(trigger.device_id) }}speaker'
      - action: media_player.play_media
        target:
          entity_id: 'media_player.{{ area_name(trigger.device_id) }}speaker'
        data:
          media_content_id: media-source://media_source/media/Server/media/Sorted Music/thunder.mp3
          media_content_type: audio/mpeg
        metadata:
          title: thunder.mp3
          thumbnail: null
          media_class: music
          children_media_class: null
          navigateIds:
            - {}
            - media_content_type: app
              media_content_id: media-source://media_source
            - media_content_type: ""
              media_content_id: media-source://media_source/media/Server
            - media_content_type: ""
              media_content_id: media-source://media_source/media/Server/media
            - media_content_type: ""
              media_content_id: media-source://media_source/media/Server/media/Sorted Music

  - id: va_stop_goog_speaker
    alias: va_stop_goog_speaker
    mode: parallel
    triggers:
      - trigger: conversation
        command: "stop sounds"
    conditions: []
    actions:
      - action: media_player.media_stop
        target:
          entity_id: 'media_player.{{ area_name(trigger.device_id) }}speaker'
      - action: media_player.turn_off
        target:
          entity_id: 'media_player.{{ area_name(trigger.device_id) }}speaker'

  - id: va_alarm_goog_speaker
    alias: va_alarm_goog_speaker
    mode: parallel
    triggers:
      - platform: state
        entity_id: binary_sensor.master_headboard_eth_va_master_headboard_eth_va_alarm_on
        to: "on"
    conditions: []
    actions:
      - action: media_player.turn_on
        target:
          entity_id: 'media_player.{{ area_name(trigger.entity_id) }}speaker'
      - repeat:
          sequence:
            - delay: '00:00:03'
            - action: media_player.play_media
              target:
                 entity_id: 'media_player.{{ area_name(trigger.entity_id) }}speaker'
              data:
                media_content_id: media-source://media_source/media/Server/media/Sorted Music/beep-6-96243.mp3
                media_content_type: audio/mpeg
              metadata:
                title: beep-6-96243.mp3
                thumbnail: null
                media_class: music
                children_media_class: null
                navigateIds:
                  - {}
                  - media_content_type: app
                    media_content_id: media-source://media_source
                  - media_content_type: ""
                    media_content_id: media-source://media_source/media/Server
                  - media_content_type: ""
                    media_content_id: media-source://media_source/media/Server/media
                  - media_content_type: ""
                    media_content_id: media-source://media_source/media/Server/media/Sorted Music
          while:
            - condition: template
              value_template: "{{ is_state(trigger.entity_id, 'on') }}"

  - id: va_set_vol_goog_speaker
    alias: va_set_vol_goog_speaker
    mode: parallel
    triggers:
      - platform: state
        entity_id: media_player.masterbedroomspeaker
    conditions: []
    actions:
      - action: media_player.volume_set
        target:
          entity_id: 'media_player.{{ area_name(trigger.device_id) }}speaker'
        data_template:
          volume_level: >
            {{ trigger.to_state.attributes.volume_level | float }}
