
input_text:
  announce_textbox:
    name: announce_textbox

automation:
  - id: va_thunderstorm_sounds
    alias: va_thunderstorm_sounds
    mode: parallel
    triggers:
      - trigger: conversation
        command: "play thunderstorm sounds"
    conditions: []
    actions:
      - action: media_player.turn_on
        target:
          entity_id: 'media_player.{{ area_name(trigger.device_id) }}speaker'
      - action: media_player.play_media
        target:
            entity_id: >
              {{ area_entities(area_id(trigger.device_id))
              | select('match','media_player.*speaker')
              | list
              | first }}
        data:
          media:
            media_content_id: media-source://media_source/media/media/media/Sorted Music/thunder.mp3
            media_content_type: audio/mpeg
            metadata:
              title: thunder.mp3
              thumbnail: null
              media_class: music
              children_media_class: null
              navigateIds:
                - {}
                - media_content_type: app
                  media_content_id: media-source://media_source
                - media_content_type: ""
                  media_content_id: media-source://media_source/media/media
                - media_content_type: ""
                  media_content_id: media-source://media_source/media/media/media
                - media_content_type: ""
                  media_content_id: media-source://media_source/media/media/media/Sorted Music
            


  - id: va_stop_goog_speaker
    alias: va_stop_goog_speaker
    mode: parallel
    triggers:
      - trigger: conversation
        command: "stop sounds"
    conditions: []
    actions:
      - action: media_player.media_stop
        target:
          entity_id: 'media_player.{{ area_name(trigger.device_id) }}speaker'
      - action: media_player.turn_off
        target:
          entity_id: 'media_player.{{ area_name(trigger.device_id) }}speaker'

  - id: va_alarm_goog_speaker
    alias: va_alarm_goog_speaker
    mode: parallel
    triggers:
      - platform: state
        entity_id: binary_sensor.master_headboard_eth_va_master_headboard_eth_va_alarm_on
        to: "on"
      - platform: state
        entity_id: binary_sensor.kitchen_cabinet_eth_va_kitchen_cabinet_eth_va_alarm_on
        to: "on"
      - platform: state
        entity_id: binary_sensor.livingroom_eth_va_livingroom_eth_va_alarm_on
        to: "on"
    conditions: []
    actions:
      - action: media_player.turn_on
        target:
          entity_id: 'media_player.{{ area_name(trigger.entity_id) }}speaker'
      - repeat:
          sequence:
            - delay: '00:00:03'
            - action: media_player.play_media
              target:
                entity_id: >
                  {{ area_entities(area_id(trigger.device_id))
                  | select('match','media_player.*speaker')
                  | list
                  | first }}data:
                media:
                  media_content_id: >-
                    media-source://media_source/media/media/media/Sorted
                    Music/beep-6-96243.mp3
                  media_content_type: audio/mpeg
                  metadata:
                    title: beep-6-96243.mp3
                    thumbnail: null
                    media_class: music
                    children_media_class: null
                    navigateIds:
                      - {}
                      - media_content_type: app
                        media_content_id: media-source://media_source
                      - media_content_type: ""
                        media_content_id: media-source://media_source/media/media
                      - media_content_type: ""
                        media_content_id: media-source://media_source/media/media/media
                      - media_content_type: ""
                        media_content_id: media-source://media_source/media/media/media/Sorted Music
          while:
            - condition: template
              value_template: "{{ is_state(trigger.entity_id, 'on') }}"

  - id: va_set_vol_goog_speaker
    alias: va_set_vol_goog_speaker
    mode: parallel
    triggers:
      - platform: state
        entity_id: media_player.masterbedroomspeaker
    conditions: []
    actions:
      - action: media_player.volume_set
        target:
          entity_id: 'media_player.{{ area_name(trigger.device_id) }}speaker'
        data_template:
          volume_level: >
            {{ state_attr(trigger.entity_id, 'volume_level') | float }}

  - id: calendar_announce
    alias: calendar_announce
    trigger:
      - platform: calendar
        event: start
        entity_id: calendar.teamcarriger_gmail_com
    condition:
      - condition: template
        value_template: "{{ 'Announce' in trigger.calendar_event.summary }}"
    actions:
      - action: assist_satellite.announce
        metadata: {}
        data:
          message: "{{ trigger.calendar_event.description }}"
        target:
          area_id:
            - 36a7e54132e84284a4368f292e945bb0
            - 63db88fe052b434c86e1d37781ce0972
            - 259e54ef72a347c2b9fa159e5bcd32b7

  - id: button_announce
    alias: button_announce
    triggers:
      - trigger: state
        entity_id: input_text.announce_textbox
    actions:
          - action: assist_satellite.announce
            metadata: {}
            data:
              message: "{{ states('input_text.announce_textbox') }}"
            target:
              area_id:
                - 36a7e54132e84284a4368f292e945bb0
                - 63db88fe052b434c86e1d37781ce0972
                - 259e54ef72a347c2b9fa159e5bcd32b7
          

            
