homeassistant:
  customize:
    binary_sensor.emi_window_controller_motion:
      friendly_name: Emi Room Motion
    sensor.emi_window_controller_temp:
      friendly_name: Emi Room Temperature
    sensor.emi_window_controller_humidity:
      friendly_name: Emi Room  Humidity
    sensor.emi_window_controller_pressure:
      friendly_name: Emi Room Pressure
    cover.emi_window_controller_blind:
      friendly_name: Emi Room Blind
    cover.emi_window_controller_curt1:
      friendly_name: Emi Room Sheer Curtain
    cover.emi_window_controller_curt2:
      friendly_name: Emi Room Curtain
    sensor.emi_window_controller_lux:
      friendly_name: Emi Room Light Lux
  
binary_sensor:
  - platform: mqtt # Emi fan state
    state_topic: "hawirelesslink/fan/king_of_fans_inc_hbuniversalcfremote_0020d37b_1_514/state"
    name: emi_fan_state
    payload_on: "on"
    payload_off: "off"
    device_class: power

  - platform: mqtt # Emi Motion Sensor
    state_topic: "hawirelesslink/binary_sensor/imagic_by_greatstar_1117_s_fe53fcd3_1_1280/state"
    name: emi_motion
    payload_on: "on"
    payload_off: "off"
    device_class: motion
    
fan:
  - platform: template
    fans:
      emi_fan:
        friendly_name: "Emi fan"
        value_template: "{{ states('binary_sensor.emi_fan_state') }}"
        speed_template: "{{ states('sensor.emi_fan_speed')|replace('\"','') }}"
        turn_on:
          service:  mqtt.publish
          data_template:
              topic: "/HAwirelesslink/return/fan/king_of_fans_inc_hbuniversalcfremote_0020d37b_1_514/state"
              payload: 'on'
        turn_off:
          service:  mqtt.publish
          data_template:
              topic: "/HAwirelesslink/return/fan/king_of_fans_inc_hbuniversalcfremote_0020d37b_1_514/state"
              payload: 'off'
        set_speed:
          service: mqtt.publish
          data_template:
              topic: "/HAwirelesslink/return/fan/king_of_fans_inc_hbuniversalcfremote_0020d37b_1_514/speed"
              payload: '{{ speed }}'
        speeds:
          - 'low'
          - 'medium'
          - 'high'
          - 'on'
          - 'auto'
          - 'smart'
          - 'off'
          
light:

  - platform: group
    name: emi_star_lamp
    entities:
      - light.emi_star_1
      - light.emi_star_2
      - light.emi_star_3

  - platform : mqtt
    name: emi_fan_light
    state_topic: "hawirelesslink/light/king_of_fans_inc_hbuniversalcfremote_7bd32000_level_on_off/state"
    command_topic: "/HAwirelesslink/return/light/king_of_fans_inc_hbuniversalcfremote_7bd32000_level_on_off/state"
    payload_on: "on"
    payload_off: "off"
    retain: false
    
sensor:
  - platform: mqtt
    name: "emi_fan_speed"
    state_topic: "hawirelesslink/fan/king_of_fans_inc_hbuniversalcfremote_0020d37b_1_514/speed"

  - platform: mqtt
    name: emi_temp
    state_topic: "hawirelesslink/sensor/imagic_by_greatstar_1117_s_fe53fcd3_1_1026/state"
    unit_of_measurement: "°F"
    
camera:
  - platform: mjpeg
    name: emi_camera
    still_image_url: http://192.168.2.200:81/image/emibed?q=100&s=100
    mjpeg_url: http://192.168.2.200:81/mjpg/emibed/video.mjpg
    
automation:
  - id: emi_fan_speed
    alias: emi_fan_speed
    initial_state: 'off'
    trigger:
    - entity_id: sensor.emi_temp
      platform: state
    - entity_id: 'fan.emi_fan'
      platform: state
    condition:
      - condition: state
        entity_id: 'fan.emi_fan'
        state: 'on'
    action:
    - service: fan.set_speed
      data_template:
        entity_id: fan.emi_fan
        speed: >
          {% if (states.sensor.emi_temp.state|float > 80 ) %}
            on
          {% elif (states.sensor.emi_temp.state|float <= 80 ) and (states.sensor.emi_temp.state|float > 76 ) %} 
            high
          {% elif (states.sensor.emi_temp.state|float <= 76 ) and (states.sensor.emi_temp.state|float > 74 ) %} 
            medium
          {% elif (states.sensor.emi_temp.state|float <= 74 ) %} 
            low
          {% endif %}
