# Frontend/integration entity renames:
# fan.nursery_fan → fan.emi_room_fan
# sensor.lottie_room_air_temperature → sensor.emi_room_air_temperature

homeassistant:
  customize:

automation:
  - id: emi_room_fan_speed
    alias: emi_room_fan_speed
    trigger:
      - entity_id: sensor.emi_room_air_temperature
        platform: state
      - entity_id: fan.emi_room_fan
        platform: state
    condition:
      - condition: state
        entity_id: fan.emi_room_fan
        state: 'on'
    action:
      - service: fan.set_percentage
        target:
          entity_id: fan.emi_room_fan
        data:
          percentage: >
            {% if (states.sensor.emi_room_air_temperature.state|float(default=0) > 80 ) %}
              100
            {% elif (states.sensor.emi_room_air_temperature.state|float(default=0) <= 80 ) and (states.sensor.emi_room_air_temperature.state|float(default=0) > 76 ) %}
              75
            {% elif (states.sensor.emi_room_air_temperature.state|float(default=0) <= 76 ) and (states.sensor.emi_room_air_temperature.state|float(default=0) > 74 ) %}
              50
            {% elif (states.sensor.emi_room_air_temperature.state|float(default=0) <= 74 ) %}
              25
            {% endif %}
