homeassistant:
  customize:
    binary_sensor.emi_window_controller_motion:
      friendly_name: Emi Room Motion
    sensor.emi_window_controller_temp:
      friendly_name: Emi Room Temperature
    sensor.emi_window_controller_humidity:
      friendly_name: Emi Room  Humidity
    sensor.emi_window_controller_pressure:
      friendly_name: Emi Room Pressure
    cover.emi_window_controller_blind:
      friendly_name: Emi Room Blind
    cover.emi_window_controller_curt1:
      friendly_name: Emi Room Sheer Curtain
    cover.emi_window_controller_curt2:
      friendly_name: Emi Room Curtain
    sensor.emi_window_controller_lux:
      friendly_name: Emi Room Light Lux
    fan.emi_fan:
      friendly_name: Emi Fan
    light.emi_fan_light:
      friendly_name: Emi Fan Light
    binary_sensor.emi_motion:
      friendly_name: Emi Bedroom Motion
    sensor.emi_temp:
      friendly_name: Emi Bedroom Temperature
  
          
light:
  - platform: group
    name: emi_star_lamp
    entities:
      - light.emi_star_1
      - light.emi_star_2
      - light.emi_star_3

camera:
  - platform: mjpeg
    name: emi_camera
    still_image_url: http://192.168.2.200:81/image/emibed?q=100&s=100
    mjpeg_url: http://192.168.2.200:81/mjpg/emibed/video.mjpg
    
automation:
  - id: emi_fan_speed
    alias: emi_fan_speed
    initial_state: 'off'
    trigger:
    - entity_id: sensor.emi_temp
      platform: state
    - entity_id: 'fan.emi_fan'
      platform: state
    condition:
      - condition: state
        entity_id: 'fan.emi_fan'
        state: 'on'
    action:
    - service: fan.set_preset_mode
      data_template:
        entity_id: fan.emi_fan
        speed: >
          {% if (states.sensor.emi_temp.state|float > 80 ) %}
            on
          {% elif (states.sensor.emi_temp.state|float <= 80 ) and (states.sensor.emi_temp.state|float > 76 ) %} 
            high
          {% elif (states.sensor.emi_temp.state|float <= 76 ) and (states.sensor.emi_temp.state|float > 74 ) %} 
            medium
          {% elif (states.sensor.emi_temp.state|float <= 74 ) %} 
            low
          {% endif %}

script:
  goodnight_emi:
    sequence:
      - service:  light.turn_on
        target:
          entity_id:  light.emi_star_lamp
        data:
          kelvin: 2800
          brightness_pct: 100
      - service:  fan.turn_on
        target:
          entity_id:  fan.emi_fan
      - service:  light.turn_on
        target:
          entity_id:  light.hallway
        data:
          brightness_pct: 25
      - delay:
          minutes: 30
      - service:  light.turn_off
        data:
          entity_id:  light.emi_fan_light
      - service:  light.turn_on
        target:
          entity_id:  light.emi_star_lamp
        data:
          brightness_pct: 10
          transition: 900
      - delay:
          minutes: 15
      - service:  light.turn_off
        target:
          entity_id:  light.emi_star_lamp
        data:
          transition: 300
