homeassistant:
  customize:



template:
  - sensor:
      - name: "Total Power Grid"
        unit_of_measurement: "Wh"
        state_class: "total_increasing"
        device_class: "energy"
        state: >
          {{ (states('sensor.em16_a1_this_month_energy')|float(0) + states('sensor.em16_a1_this_month_energy')|float(0))}}
      - name: "Total Power Grid In"
        unit_of_measurement: "Wh"
        state_class: "total_increasing"
        device_class: "energy"
        state: >
          {% if states('sensor.total_power_grid')|float(0) > 0 %}
            {{ states('sensor.total_power_grid')|float(0) }}
          {% else %}
            0
          {% endif %}
      - name: "Total Power Grid Out"
        unit_of_measurement: "Wh"
        state_class: "total_increasing"
        device_class: "energy"
        state: >
          {% if states('sensor.total_power_grid')|float(0) < 0 %}
            {{ states('sensor.total_power_grid')|float(0) }}
          {% else %}
            0
          {% endif %}
  - sensor:
      - name: "Total Power Solar"
        unit_of_measurement: "Wh"
        state_class: "total_increasing"
        device_class: "energy"
        state: >
          {{ (states('sensor.em16_a2_this_month_energy')|float(0) + states('sensor.em16_b2_this_month_energy')|float(0)) }}
  - sensor:
      - name: "Pump Corrected power"
        unit_of_measurement: "Wh"
        state_class: "total_increasing"
        device_class: "energy"
        state: >
          {{ (states('sensor.pump_acc')|float(0)) * 2 }}
  - sensor:
      - name: "Stove Corrected power"
        unit_of_measurement: "Wh"
        state_class: "total_increasing"
        device_class: "energy"
        state: >
          {{ (states('sensor.stove_acc')|float(0) ) * 2 }}
  - sensor:
      - name: "Dryer Corrected power"
        unit_of_measurement: "Wh"
        state_class: "total_increasing"
        device_class: "energy"
        state: >
          {{ (states('sensor.dryer_acc')|float(0) ) * 2 }}




          
