homeassistant:
  customize:
    light.porch_light:
      friendly_name: Porch Light
    light.garage_ext_2:
      friendly_name: Driveway Light 2

plant:
  MidFront_Hydrangea:
    sensors:
      moisture: sensor.lr_bt_sns_hydrangea_moisture
      temperature: sensor.lr_bt_sns_hydrangea_temperature
      conductivity: sensor.lr_bt_sns_hydrangea_soil_conductivity
      brightness: sensor.lr_bt_sns_hydrangea_illuminance
    min_moisture: 20
    min_conductivity: 50
  Door_Lilac:
    sensors:
      moisture: sensor.lr_bt_sns_4_moisture
      temperature: sensor.lr_bt_sns_4_temperature
      conductivity: sensor.lr_bt_sns_4_soil_conductivity
      brightness: sensor.lr_bt_sns_4_illuminance
    min_moisture: 20
    min_conductivity: 50
  MidOut_Hydrangea:
    sensors:
      moisture: sensor.lr_bt_sns_3_moisture
      temperature: sensor.lr_bt_sns_3_temperature
      conductivity: sensor.lr_bt_sns_3_soil_conductivity
      brightness: sensor.lr_bt_sns_3_illuminance
    min_moisture: 20
    min_conductivity: 50
  Mid_Hydrangea:
    sensors:
      moisture: sensor.lr_bt_sns_2_moisture
      temperature: sensor.lr_bt_sns_2_temperature
      conductivity: sensor.lr_bt_sns_2_soil_conductivity
      brightness: sensor.lr_bt_sns_2_illuminance
    min_moisture: 20
    min_conductivity: 50
      
    
      
template:
  - binary_sensor:
      - name: doorbell_person
        state: >
          {{ is_state('binary_sensor.doorbell_person_raw', 'on') }}
        delay_off:
          minutes: 5
    

automation:
  - alias: doorbell_person_detected
    trigger: 
      platform: state
      entity_id: binary_sensor.doorbell_person
      from: 'off'
      to: 'on'
    condition:
      - condition: state
        entity_id: lock.front_door
        state: locked
    action:
      - service: camera.snapshot
        data:
          entity_id: camera.doorbell_last_person
          filename: /config/www/snapshot1.jpg
