homeassistant:
  customize:

binary_sensor:
  - platform: mqtt # Detect motion from fron camera from blueiris
    state_topic: "blueiris/frontyard"
    name: front_foscam_motion
    payload_on: "motion"
    payload_off: "clear"
    
  - name: doorbell_person_raw
    platform: mqtt
    state_topic: "frigate/doorbell/person"
    device_class: motion
      
  - platform: template
    sensors:
      doorbell_person:
        value_template: >-
          {{ is_state('binary_sensor.doorbell_person_raw', 'on') }}
        delay_off:
          minutes: 5
      
  - name: frontyard_person
    platform: mqtt
    state_topic: "frigate/frontyard/person"
    device_class: motion
    availability_topic: "frigate/available"
    
camera:
  - platform: mjpeg
    name: frontdoor
    still_image_url: http://192.168.2.200:81/image/frontdoor?q=100&s=100
    mjpeg_url: http://192.168.2.200:81/mjpg/frontdoor/video.mjpg
    
  - platform: mjpeg
    name: "Front Porch"
    still_image_url: http://192.168.2.200:81/image/Frontyard?q=100&s=100
    mjpeg_url: http://192.168.2.200:81/mjpg/frontyard/video.mjpg
    
  - name: doorbell_last_person
    platform: mqtt
    topic: frigate/doorbell/person/snapshot
  - name: Doorbell Last Car
    platform: mqtt
    topic: frigate/doorbell/car/snapshot
    
  - name: Frontyard Last Person
    platform: mqtt
    topic: frigate/frontyard/person/snapshot
  - name: Backyard Last Car
    platform: mqtt
    topic: frigate/frontyard/car/snapshot

automation:
  - alias: doorbell_person_detected
    trigger: 
      platform: state
      entity_id: binary_sensor.doorbell_person
      from: 'off'
      to: 'on'
    condition:
      - condition: state
        entity_id: lock.front_door
        state: locked
    action:
      - service: camera.snapshot
        data:
          entity_id: camera.doorbell_last_person
          filename: /config/www/snapshot1.jpg
