automation:
  - id: 'frig_person_found'
    alias: frig_person_found
    initial_state: 'off'
    mode: single
    triggers:
      - trigger: state
        entity_id: image.doorbell_person
        attribute: entity_picture
        not_from:
          - "unknown"
          - "unavailable"
      - trigger: state
        entity_id: image.garage_person
        attribute: entity_picture
        not_from:
          - "unknown"
          - "unavailable"
    condition: []
    actions:
    - data:
        message: "Look at this fool man"
        data: 
          image: '{{ state_attr(trigger.entity_id, "entity_picture") }}'
      action: notify.group_notify
    - delay:
        hours: 0
        minutes: 5
        seconds: 0
        milliseconds: 0
