automation:
  alias: Frigate Person
  description: ""
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera:
        - camera.backyard_2
        - camera.backyard_shed
        - camera.doorbell
        - camera.garage_2
      notify_group: notify.group_notify
      notify_device: 16e48cf04bd912efe3b48f87441a304f
      base_url: https://homeassistant.teamcarriger.club
      labels:
        - person
      video: >-
        {{base_url}}/api/frigate{{client_id}}/notifications/{{review_id}}/review_preview.gif?format=ts
      color: "#6e41ab"
