automation:
  - id: 'person_found_db'
    alias: person_found_db
  - mode: single
    trigger:
    - entity_id: image.doorbell_person
      platform: state
      not_from:
        - "unknown"
        - "unavailable"
    condition: []
    action:
    - data:
        data: 
          image: "{{ state_attr(\"image.doorbell_person\", \"entity_picture\") }}"
        message: "Man look at this fool"
      service: notify.group_notify
    - delay: '00:05:00'    
