automation:
  - id: 'frig_person_found'
    alias: frig_person_found
    initial_state: 'off'
  - mode: single
    triggers:
    - entity_id: image.doorbell_person
      platform: state
      not_from:
        - "unknown"
        - "unavailable"
    - entity_id: image.garage_person
      platform: state
      not_from:
        - "unknown"
        - "unavailable"
    condition: []
    actions:
    - data:
        message: "Look at this fool man"
        data: 
          image: '{{ state_attr(trigger.entity_id, "entity_picture") }}'
      service: notify.group_notify
    - delay: '00:05:00'
