homeassistant:
  customize:
    binary_sensor.garage_door_back:
      device_class: door
      
camera:
  - platform: mjpeg
    name: Garage
    still_image_url: http://192.168.2.200:81/image/garage?q=100&s=100
    mjpeg_url: http://192.168.2.200:81/mjpg/garage/video.mjpg
        
switch:
  - platform : mqtt
    name: "garage_wall_switch"
    state_topic: "hawirelesslink/switch/enerwave_zw15rm_plus_15a_tr_smart_meter_duplex_receptacle_switch/state"
    command_topic: "/HAwirelesslink/return/switch/enerwave_zw15rm_plus_15a_tr_smart_meter_duplex_receptacle_switch/state"
    state_on: "on"
    state_off: "off"
    payload_on: "on"
    payload_off: "off"
    retain: false
