  
homeassistant:
  customize:
    binary_sensor.hall_window_opened:
      device_class: window
      friendly_name: Hall Window
    binary_sensor.hallway_motion_combine:
      device_class: motion
    sensor.hallway_motion_temperature:
      friendly_name: Hall Lower Temperature
    sensor.hallway_motion_2_temperature:
      friendly_name: Hall Upper Temperature
    sensor.hall_window_temperature:
      friendly_name: Hall Window Temperature

binary_sensor:
  - platform: template # Combine both hallway sensors into 1 logical 
    sensors:
      hallway_motion_combine:
        value_template: >-
          {{ is_state('binary_sensor.hallway_motion', 'on')
             or is_state('binary_sensor.hallway_motion_2', 'on') }}
        delay_off:
          minutes: 5
