  
homeassistant:
  customize:
    binary_sensor.hall_window_opened:
      device_class: window
      friendly_name: Hall Window
    binary_sensor.hallway_motion_combine:
      device_class: motion
    sensor.hallway_motion_temperature:
      friendly_name: Hall Lower Temperature
    sensor.hallway_motion_2_temperature:
      friendly_name: Hall Upper Temperature
    sensor.hall_window_temperature:
      friendly_name: Hall Window Temperature

binary_sensor:
  - platform: template # Combine both hallway sensors into 1 logical 
    sensors:
      hallway_motion_combine:
        value_template: >-
          {{ is_state('binary_sensor.hallway_motion', 'on')
             or is_state('binary_sensor.hallway_motion_2', 'on') }}
        delay_off:
          minutes: 5
sensor:
  - platform: template
    sensors:
      hall_lights_sync:
        value_template: >
          {% set my_lights = [ states.light.hallway, states.light.leviton_dz6hd_1bz_decora_600w_smart_dimmer_level_3, states.light.hall_lights ] %}
          {% for l in my_lights | sort(attribute='last_updated', reverse=true) %}
            {%- if loop.first %}{{ l.entity_id }},{{ l.attributes.brightness | default(0) }}{% elif loop.last -%}{% endif -%}
          {%- endfor %}

automation:
  - alias: Sync Hallway
    trigger:
      - platform: state
        entity_id: light.hall_lights
      - platform: state
        entity_id: light.hallway
      - platform: state
        entity_id: light.leviton_dz6hd_1bz_decora_600w_smart_dimmer_level_3
    condition: []
    action:
    - service: light.turn_on
      data_template:
        entity_id: >
          {% if states('sensor.hall_lights_sync').split(',')[0] == "light.hall_lights"  %}
            light.hallway
          {% elif states('sensor.hall_lights_sync').split(',')[0] == "light.hallway" %}
            light.leviton_dz6hd_1bz_decora_600w_smart_dimmer_level_3
          {% else %}
            light.hall_lights
          {% endif %}
        brightness: >
          {{ states('sensor.hall_lights_sync').split(',')[1] | int }}
    - service: light.turn_on
      data_template:
        entity_id: >
          {% if states('sensor.hall_lights_sync').split(',')[0] == "light.hall_lights"  %}
            light.leviton_dz6hd_1bz_decora_600w_smart_dimmer_level_3
          {% elif states('sensor.hall_lights_sync').split(',')[0] == "light.hallway" %}
            light.hall_lights
          {% else %}
            light.hallway
          {% endif %}
        brightness: >
          {{ states('sensor.hall_lights_sync').split(',')[1] | int  }}
