homeassistant:
  customize:
  
input_boolean:
  independence_day:
    name: independence_day

template:
  - binary_sensor:
      - name: house_sts_independence_day
        state: >
          {{ is_state('input_boolean.independence_day', 'on') }}

automation:
  - id: 'independence_day_on'
    alias: independence_day_on
    trigger:
      - platform: calendar
        event: start
        entity_id: calendar.teamcarriger_gmail_com
      - platform: calendar
        event: end
        entity_id: calendar.teamcarriger_gmail_com
    condition:
      - condition: template
        value_template: "{{ 'independence day' in trigger.calendar_event.summary }}"
    action:
      - if:
          - "{{ trigger.event == 'start' }}"
        then:
          - service: input_boolean.turn_on
            entity_id: input_boolean.independence day
        else:
          - service: input_boolean.turn_off
            entity_id: input_boolean.independence day
    mode: queued

scene:
  - name: xmas_lights_on
    entities:
      light.front_garden_level_light_color_on_off:
        color_name: green
      light.front_light1_level_light_color_on_off:
        color_name: green
      light.front_light1_level_light_color_on_off:
        color_name: red
      light.front_light1_level_light_color_on_off:
        color_name: red
  - name: house_evening_independence
    entities:
      light.front_light1_level_light_color_on_off:
        color_name: red
      light.front_light2_level_light_color_on_off:
        color_name: white
      light.front_light3_level_light_color_on_off:
        color_name: red
      light.front_garden_level_light_color_on_off:
        color_name: blue
      light.rainbrarrel_decklight:
        state: on
        brightness: 215
        effect: "Independence Day"

