homeassistant:
  customize:
  

input_boolean:
  independence_day:
    name: independence_day
    initial: false
  house_sts_xmas_lights:
    name: house_sts_xmas_lights
    initial: false
  super_bowl:
    name: house_sts_super_bowl
    initial: false

    
template:
  - binary_sensor:
      - name: house_sts_independence_day
        state: >
          {{ is_state('input_boolean.independence_day', 'on') }}
  - binary_sensor:
      - name: house_sts_xmas_lights
        state: >
          {{ is_state('input_boolean.house_sts_xmas_lights', 'on') }}
  - binary_sensor:
      - name: house_sts_super_bowl
        state: >
          {{ is_state('input_boolean.super_bowl', 'on') }}

          
automation:
  - id: 'independence_day_on'
    alias: independence_day_on
    trigger:
      - platform: calendar
        event: start
        entity_id: calendar.teamcarriger_gmail_com
      - platform: calendar
        event: end
        entity_id: calendar.teamcarriger_gmail_com
    condition:
      - condition: template
        value_template: "{{ '4th of July Lights' in trigger.calendar_event.summary }}"
    action:
      - if:
          - "{{ trigger.event == 'start' }}"
        then:
          - service: input_boolean.turn_on
            entity_id: input_boolean.independence_day
        else:
          - service: input_boolean.turn_off
            entity_id: input_boolean.independence_day
    mode: queued

  - id: 'house_sts_xmas_lights'
    alias: house_sts_xmas_lights
    trigger:
      - platform: calendar
        event: start
        entity_id: calendar.teamcarriger_gmail_com
      - platform: calendar
        event: end
        entity_id: calendar.teamcarriger_gmail_com
    condition:
      - condition: template
        value_template: "{{ 'xmas_lights' in trigger.calendar_event.summary }}"
    action:
      - if:
          - "{{ trigger.event == 'start' }}"
        then:
          - service: input_boolean.turn_on
            entity_id: input_boolean.house_sts_xmas_lights
        else:
          - service: input_boolean.turn_off
            entity_id: input_boolean.house_sts_xmas_lights
    mode: queued

  - id: 'morning_xmas'
    alias: morning_xmas
    trigger:
    - platform: time
      at: '7:30:00'
    condition:
      - condition: template
        value_template: "{{ is_state('input_boolean.house_sts_xmas_lights', 'on') }}"
    action:
    - data:
        entity_id: switch.garage_wall_switch
      service: switch.turn_off
    - data:
        entity_id: light.uhall_ban_hall_ban
        brightness: 255
      service: light.turn_on
    mode: queued
    

script:
  xmas_light:
    sequence:
    - service: light.turn_on
      data:
        color_name: blue
        entity_id: light.front_light1_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: green
        entity_id: light.front_light2_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: red
        entity_id: light.front_light3_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: blue
        entity_id: light.front_garden_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: red
        entity_id: light.porch_light
    - service: light.turn_on
      data:
        brightness: 215
        entity_id: light.rainbrarrel_rb_string
        color_name: white
        effect: "Blue Sparkle"
    - service: light.turn_on
      data:
        brightness: 215
        entity_id: light.lr_bt_sns_fy_string
        color_name: white
        effect: "Blue Sparkle"
    - service: switch.turn_on
      data:
        entity_id: switch.garage_wall_switch
        
  super_bowl:
    sequence:
    - service: light.turn_on
      data:
        brightness: 215
        entity_id: light.rainbrarrel_rb_string
        color_name: white
        effect: "Chiefs"
    - service: light.turn_on
      data:
        brightness: 215
        entity_id: light.lr_bt_sns_fy_string
        color_name: white
        effect: "Chiefs"
    - service: light.turn_on
      data:
        brightness: 215
        entity_id: light.cabinet_bottom
        color_name: white
        effect: "Chiefs"
    - service: light.turn_on
      data:
        brightness: 215
        entity_id: light.cabinet_top
        color_name: white
        effect: "Chiefs"
    - service: light.turn_on
      data:
        brightness: 215
        entity_id: light.uhall_ban_hall_ban
        color_name: white
        effect: "Chiefs"

        
  normal_day:
    sequence:
    - service: light.turn_on
      data:
        color_name: white
        entity_id: light.front_light1_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: white
        entity_id: light.front_light2_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: white
        entity_id: light.front_light3_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: white
        entity_id: light.front_garden_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: white
        entity_id: light.porch_light
    - service: light.turn_on
      data:
        brightness: 215
        entity_id: light.rainbrarrel_decklight
        color_name: white
        effect: None

  xmas_light:
    sequence:
    - service: light.turn_on
      data:
        color_name: blue
        entity_id: light.front_light1_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: white
        entity_id: light.front_light2_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: red
        entity_id: light.front_light3_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: blue
        entity_id: light.front_garden_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: red
        entity_id: light.porch_light
    - service: light.turn_on
      data:
        brightness: 215
        entity_id: light.rainbrarrel_rb_string
        color_name: white
        effect: "Independence Day"
    - service: light.turn_on
      data:
        brightness: 215
        entity_id: light.lr_bt_sns_fy_string
        color_name: white
        effect: "Independence Day"
    - service: switch.turn_on
      data:
        entity_id: switch.garage_wall_switch
        
        
        
