homeassistant:
  customize:
  

input_boolean:
  independence_day:
    name: independence_day
    initial: false
  house_sts_xmas_lights:
    name: house_sts_xmas_lights
    initial: false

    
template:
  - binary_sensor:
      - name: house_sts_independence_day
        state: >
          {{ is_state('input_boolean.independence_day', 'on') }}
  - binary_sensor:
      - name: house_sts_xmas_lights
        state: >
          {{ is_state('input_boolean.house_sts_xmas_lights', 'on') }}

          
automation:
  - id: 'independence_day_on'
    alias: independence_day_on
    trigger:
      - platform: calendar
        event: start
        entity_id: calendar.teamcarriger_gmail_com
      - platform: calendar
        event: end
        entity_id: calendar.teamcarriger_gmail_com
    condition:
      - condition: template
        value_template: "{{ '4th of July Lights' in trigger.calendar_event.summary }}"
    action:
      - if:
          - "{{ trigger.event == 'start' }}"
        then:
          - service: input_boolean.turn_on
            entity_id: input_boolean.independence_day
        else:
          - service: input_boolean.turn_off
            entity_id: input_boolean.independence_day
    mode: queued

automation:
  - id: 'house_sts_xmas_lights'
    alias: house_sts_xmas_lights
    trigger:
      - platform: calendar
        event: start
        entity_id: calendar.teamcarriger_gmail_com
      - platform: calendar
        event: end
        entity_id: calendar.teamcarriger_gmail_com
    condition:
      - condition: template
        value_template: "{{ 'xmas_lights' in trigger.calendar_event.summary }}"
    action:
      - if:
          - "{{ trigger.event == 'start' }}"
        then:
          - service: input_boolean.turn_on
            entity_id: input_boolean.house_sts_xmas_lights
        else:
          - service: input_boolean.turn_off
            entity_id: input_boolean.house_sts_xmas_lights
    mode: queued


script:
  independence_day:
    sequence:
    - service: light.turn_on
      data:
        color_name: red
        entity_id: light.front_light1_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: white
        entity_id: light.front_light2_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: red
        entity_id: light.front_light3_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: blue
        entity_id: light.front_garden_level_light_color_on_off
    - service: light.turn_on
      data:
        brightness: 215
        entity_id: light.rainbrarrel_decklight

script:
  xmas_light:
    sequence:
    - service: light.turn_on
      data:
        color_name: red
        entity_id: light.front_light1_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: blue
        entity_id: light.front_light2_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: green
        entity_id: light.front_light3_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: blue
        entity_id: light.front_garden_level_light_color_on_off
    - service: light.turn_on
      data:
        brightness: 255
        color_name: blue
        entity_id: light.rainbrarrel_rb_string
        effect: "Blue Sparkle"
    - service: light.turn_on
      data:
        brightness: 255
        color_name: blue
        entity_id: light.lr_bt_sns_fy_string
        effect: "Blue Sparkle"
        
script:
  normal_day:
    sequence:
    - service: light.turn_on
      data:
        color_name: white
        entity_id: light.front_light1_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: white
        entity_id: light.front_light2_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: white
        entity_id: light.front_light3_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: white
        entity_id: light.front_garden_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: white
        entity_id: light.porch_light
    - service: light.turn_on
      data:
        brightness: 215
        entity_id: light.rainbrarrel_decklight
        color_name: white
        effect: None
        
        
        
