homeassistant:
  customize:
  

input_boolean:
  independence_day:
    name: independence_day
  house_sts_xmas_lights:
    name: house_sts_xmas_lights
  super_bowl:
    name: house_sts_super_bowl
  halloween:
    name: halloween
    

    
template:
  - binary_sensor:
      - name: house_sts_independence_day
        state: >
          {{ is_state('input_boolean.independence_day', 'on') }}
  - binary_sensor:
      - name: house_sts_xmas_lights
        state: >
          {{ is_state('input_boolean.house_sts_xmas_lights', 'on') }}
  - binary_sensor:
      - name: house_sts_super_bowl
        state: >
          {{ is_state('input_boolean.super_bowl', 'on') }}
  - binary_sensor:
      - name: house_sts_halloween
        state: >
          {{ is_state('input_boolean.halloween', 'on') }}


automation:
  - id: 'independence_day_on'
    alias: independence_day_on
    trigger:
      - platform: calendar
        event: start
        entity_id: calendar.teamcarriger_gmail_com
      - platform: calendar
        event: end
        entity_id: calendar.teamcarriger_gmail_com
    condition:
      - condition: template
        value_template: "{{ '4th of July Lights' in trigger.calendar_event.summary }}"
    action:
      - if:
          - "{{ trigger.event == 'start' }}"
        then:
          - service: input_boolean.turn_on
            entity_id: input_boolean.independence_day
        else:
          - service: input_boolean.turn_off
            entity_id: input_boolean.independence_day
    mode: queued

  - id: 'halloween_on'
    alias: halloween_on
    trigger:
      - platform: calendar
        event: start
        entity_id: calendar.teamcarriger_gmail_com
      - platform: calendar
        event: end
        entity_id: calendar.teamcarriger_gmail_com
    condition:
      - condition: template
        value_template: "{{ 'Halloween Lights' in trigger.calendar_event.summary }}"
    action:
      - if:
          - "{{ trigger.event == 'start' }}"
        then:
          - service: input_boolean.turn_on
            entity_id: input_boolean.halloween
        else:
          - service: input_boolean.turn_off
            entity_id: input_boolean.halloween
    mode: queued


  - id: 'house_sts_xmas_lights'
    alias: house_sts_xmas_lights
    trigger:
      - platform: calendar
        event: start
        entity_id: calendar.teamcarriger_gmail_com
      - platform: calendar
        event: end
        entity_id: calendar.teamcarriger_gmail_com
    condition:
      - condition: template
        value_template: "{{ 'xmas_lights' in trigger.calendar_event.summary }}"
    action:
      - if:
          - "{{ trigger.event == 'start' }}"
        then:
          - service: input_boolean.turn_on
            entity_id: input_boolean.house_sts_xmas_lights
        else:
          - service: input_boolean.turn_off
            entity_id: input_boolean.house_sts_xmas_lights
    mode: queued

script:
  xmas_light:
    mode: parallel
    sequence:
      - parallel:
          - continue_on_error: true
            service: switch.turn_off
            data:
              entity_id: switch.front_outlets

          - continue_on_error: true
            service: light.turn_on
            data:
              brightness: 255
              effect: "Jayhawks"
            target:
              entity_id:
                - light.front_eave
                - light.backyard_eave
                - light.lr_bt_sns_yard_string
                - light.lr_bt_sns_tree_meteor

          - continue_on_error: true
            service: light.turn_on
            data:
              brightness: 255
              effect: "Blue Sparkle"
            target:
              entity_id:
                - light.lr_bt_sns_front_window
                - light.rainbrarrel_ext_back_window
                - light.decklight

          - continue_on_error: true
            service: light.turn_on
            data:
              brightness: 255
              effect: "Rainbow"
            target:
              entity_id:
                - light.cabinet_top
                - light.uhall_ban_hall_ban
                - light.lr_bt_sns_tree_string
                - light.lr_bt_sns_garden_fiber

          - continue_on_error: true
            service: light.turn_on
            data:
              brightness: 255
              color_name: red
            target:
              entity_id:
                - light.front_light3_level_light_color_on_off
                - light.porch_light

          - continue_on_error: true
            service: light.turn_on
            data:
              color_name: red
            target:
              entity_id: light.front_light1_level_light_color_on_off

          - continue_on_error: true
            service: light.turn_on
            data:
              color_name: blue
            target:
              entity_id: light.front_light2_level_light_color_on_off

          - continue_on_error: true
            service: light.turn_on
            data:
              color_name: green
            target:
              entity_id: light.lr_bt_sns_yard_string
     

  normal_day:
    sequence:
    - service: light.turn_on
      data:
        color_name: white
        entity_id: light.front_light1_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: white
        entity_id: light.front_light2_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: white
        entity_id: light.front_light3_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: white
        entity_id: light.front_garden_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: white
        entity_id: light.porch_light
    - service: light.turn_on
      data:
        brightness: 215
        entity_id: light.rainbrarrel_decklight
        color_name: white
        effect: None
    - service: switch.turn_on
      data:
        entity_id: switch.garage_wall_switch

  independence_day:
    sequence:
    - service: light.turn_on
      data:
        color_name: blue
        entity_id: light.front_light1_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: white
        entity_id: light.front_light2_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: red
        entity_id: light.front_light3_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: blue
        entity_id: light.front_garden_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: red
        entity_id: light.porch_light
    - service: light.turn_on
      data:
        brightness: 215
        entity_id: light.rainbrarrel_rb_string
        color_name: white
        effect: "Independence Day"
    - service: light.turn_on
      data:
        brightness: 215
        entity_id: light.lr_bt_sns_fy_string
        color_name: white
        effect: "Independence Day"

  halloween_light:
    sequence:
    - service: light.turn_on
      data:
        brightness: 255
        color_name: orange
        effect: "Dithering Lights"
      target:
        entity_id:
          - light.front_eave
          - light.backyard_eave
    - service: light.turn_on
      data:
        brightness: 255
        color_name: purple
        effect: "Dithering Lights"
      target:
        entity_id:
          - light.lr_bt_sns_front_window
          - light.cabinet_top
          - light.rainbrarrel_ext_back_window
          - light.uhall_ban_hall_ban
          - light.decklight
          - light.lr_bt_sns_yard_string
    - service: light.turn_on
      data:
        brightness: 255
        color_name: purple
      target:
        entity_id:
          - light.front_light3_level_light_color_on_off
          - light.front_garden_level_light_color_on_off
          - light.porch_light
    - service: light.turn_on
      data:
        color_name: orange
        entity_id: light.front_light1_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: white
        entity_id: light.front_light2_level_light_color_on_off
    - service: light.turn_on
      data:
        color_name: green
        entity_id: light.lr_bt_sns_yard_string
        


        
