homeassistant:
  customize:
    binary_sensor.house_sts_hvac_cool_req:
      device_class: cold
    binary_sensor.house_sts_hvac_heat_req:
      device_class: heat
    binary_sensor.house_sts_hvac_run:
      device_class: power
    binary_sensor.house_sts_hvac_shut:
      device_class: door
    
template:
  - binary_sensor:
      - name: house_sts_hvac_shut
        state: >
          {{ is_state('binary_sensor.hall_window_opened', 'off')
             and is_state('binary_sensor.sliding_glass_door_opened', 'off')
             and is_state('binary_sensor.livingroom_door_opened', 'off') }}
        delay_off:
          minutes: 5

  - binary_sensor:
      - name: house_sts_hvac_cool_req
        state: >
          {{ states('sensor.dark_sky_daytime_high_temperature_0d')|float(default=0) > states('input_number.hvac_ac_enable_temp')|float(default=0) }}
        delay_off:
          minutes: 30
        delay_on:
          minutes: 5

  - binary_sensor:
      - name: house_sts_hvac_heat_req
        state: >
          {{ state_attr('weather.hvac', 'temperature')|float(default=0) < states('input_number.hvac_heat_enable_temp')|float
             and state_attr('weather.hvac', 'forecast')[0]['templow']|float(default=0) < 50 }}
        delay_off:
          minutes: 30
        delay_on:
          minutes: 5

  - binary_sensor:
      - name: house_sts_hvac_req
        state: >
          {{ is_state('binary_sensor.house_sts_hvac_cool_req', 'on')
             or is_state('binary_sensor.house_sts_hvac_heat_req', 'on') }}

  - binary_sensor:
      - name: house_sts_hvac_run
        state: >
          {{ is_state('binary_sensor.house_sts_hvac_req', 'on')
             and is_state('binary_sensor.house_sts_hvac_shut', 'on') }}

  - binary_sensor:
      - name: house_sts_hum_passive_req
        state: >
          {{ is_state('binary_sensor.house_sts_hvac_heat_req', 'on')
             and states('sensor.hvac_current_humidity')|float(default=0) < states('sensor.hvac_target_humidity')|float(default=0) }}

  - binary_sensor:
      - name: house_sts_hum_active_req
        state: >
          {{ is_state('binary_sensor.house_sts_hvac_heat_req', 'on')
             and states('sensor.hvac_current_humidity')|float(default=0) < states('sensor.hvac_target_humidity')|float-5 }}

  - binary_sensor:
      - name: house_sts_hum_passive_run
        state: >
          {{ is_state('binary_sensor.house_sts_hum_passive_req', 'on')
             and is_state('sensor.hvac_fan_state', 'on') }}
             
  - sensor:
      - name: hvac_target_humidity
        unit_of_measurement: "%"
        state: >
          {% if ((0.0049*states('sensor.dark_sky_temperature')| float(default='0')+0.2668)*100) > states('input_number.hvac_humidity_max')|float(default=0) %}
            {{ states('input_number.hvac_humidity_max')| float(default='0') }}
          {% else %} 
            {{ (0.0049*states('sensor.dark_sky_temperature')|float(default=0)+0.2668)*100 }}
          {% endif %}

  - sensor:
      - name: hvac_fan_state
        state: >
          {{ states.climate.hvac.attributes.fan }}

  - sensor:
      - name: hvac_current_humidity
        unit_of_measurement: "%"
        state: >
          {{ states.climate.hvac.attributes.current_humidity|float(default=0) }}

automation:
  - id: 'house_hvac_ena'
    alias: house_hvac_ena
    initial_state: 'off'
    trigger:
    - entity_id: binary_sensor.house_sts_hvac_run
      platform: state
    condition: []
    action:
    - data:
        entity_id: script.hvac_run_stop
      service: script.turn_on

  - id: 'house_hvac_set'
    alias: house_hvac_set
    initial_state: 'off'
    trigger:
    - entity_id: binary_sensor.house_sts_dte_cheap
      platform: state
    - entity_id: binary_sensor.house_sts_guest
      platform: state
    - entity_id: binary_sensor.house_sts_vacation
      platform: state
    - entity_id: binary_sensor.house_sts_incoming
      platform: state
    condition: []
    action:
    - data:
        entity_id: script.hvac_run_setpoint
      service: script.turn_on

  - id: humidifier_passive
    alias: humidifier_passive
    initial_state: 'off'
    trigger:
    - entity_id: binary_sensor.house_sts_hum_passive_run
      platform: state
    condition: []
    action:
    - data:
        entity_id: switch.humidifier
      service_template: >
        {% if is_state('binary_sensor.house_sts_hum_passive_run','on') %}
          switch.turn_on
        {% else %}
          switch.turn_off
        {% endif %}

  - id: humidifier_active
    alias: humidifier_active
    initial_state: 'off'
    trigger:
    - entity_id: binary_sensor.house_sts_hum_active_req
      platform: state
    condition: []
    action:
    - data_template:
        fan_mode: >
            {% if is_state('binary_sensor.house_sts_hum_active_req', 'on') %}
              on
            {% else %}
              auto
            {% endif %}
        entity_id: climate.hvac_local
      service: climate.set_fan_mode
    - delay:
        milliseconds: 500
    - data_template:
        fan_mode: >
            {% if is_state('binary_sensor.house_sts_hum_active_req', 'on') %}
              on
            {% else %}
              auto
            {% endif %}
        entity_id: climate.hvac_local
      service: climate.set_fan_mode
    - delay:
        milliseconds: 500
    - data_template:
        fan_mode: >
            {% if is_state('binary_sensor.house_sts_hum_active_req', 'on') %}
              on
            {% else %}
              auto
            {% endif %}
        entity_id: climate.hvac_local
      service: climate.set_fan_mode
