homeassistant:
  customize:
    light.cabinet_led:
      friendly_name: "Cabinet Lights"
    light.kitchen_sink:
      friendly_name: "Kitchen Sink Light"
    light.kitchen_lamp:
      friendly_name: "Kitchen Light"
    light.kitchen_fan:
      friendly_name: "Kitchen Fan Light"
    binary_sensor.kitchen_leak:
      friendly_name: "Kitchen Sink Leak Sensor"
    binary_sensor.garage_entry_opened:
      device_class: door
      friendly_name: Garage Entry
    binary_sensor.sliding_glass_door_opened:
      device_class: door
      friendly_name: Sliding glass door
    binary_sensor.sliding_glass_door_opened_2:
      friendly_name: sliding_glass_door
    binary_sensor.kitchen_motion:
      device_class: motion
    fan.kitchen_fan:
      friendly_name: Kitchen Fan
    sensor.garage_entry_temperature:
      friendly_name: Garage Entry Temperature
  
template:
  - binary_sensor:
      - name: sliding_glass_door_opened
        state: >
          {{ is_state('binary_sensor.sliding_glass_door', 'on') }}
  
    
automation:
  - id: kitchen_fan_speed
    alias: kitchen_fan_speed
    initial_state: 'off'
    trigger:
    - entity_id: sensor.garage_entry_temperature
      platform: state
    - entity_id: 'fan.kitchen_fan'
      platform: state
    condition:
      - condition: state
        entity_id: 'fan.kitchen_fan'
        state: 'on'
    action:
    - service: fan.set_percentage
      data_template:
        entity_id: fan.kitchen_fan
        speed: >
          {% if (states.sensor.garage_entry_temperature.state|float(default=0) > 80 ) %}
            on
          {% elif (states.sensor.garage_entry_temperature.state|float(default=0) <= 80 ) and (states.sensor.garage_entry_temperature.state|float(default=0) > 76 ) %} 
            high
          {% elif (states.sensor.garage_entry_temperature.state|float(default=0) <= 76 ) and (states.sensor.garage_entry_temperature.state|float(default=0) > 74 ) %} 
            medium
          {% elif (states.sensor.garage_entry_temperature.state|float(default=0) <= 74 ) %} 
            low
          {% endif %}
script:
  reset_kitchen_fan:
    mode: restart
    sequence:
      - service:  switch.turn_on
        target:
          entity_id:  switch.shelly1pm_c45bbe6b423f
      - delay: 4
      - repeat:
          count: '5'
          sequence:
            - service:  switch.turn_off
              target:
                entity_id:  switch.shelly1pm_c45bbe6b423f
            - delay: 4
            - service:  switch.turn_on
              target:
                entity_id:  switch.shelly1pm_c45bbe6b423f
            - delay: 4
