homeassistant:
  customize:
          
template:
  - sensor:
      - name: "Total Water Usage"
        unit_of_measurement: "gal"
        state_class: "total_increasing"
        device_class: "water"
        state: >
          {{ states('sensor.daily_water_filtered') }}

  - binary_sensor:
      - name: leak_detectrd
        state: >
          {{ is_state('binary_sensor.laundry_leak_moisture', 'on')
             or is_state('binary_sensor.kitchen_sink_moisture', 'on') }}

          
sensor:
  - platform: statistics
    name: daily_water_filtered
    entity_id: sensor.hub_drop_4_4025c2_total_water_used_today
    state_characteristic: value_max
    max_age:
      minutes: 2
    sampling_size: 10

automation:
  - alias: turn_off_house_water
    initial_state: 'off'
    trigger:
    - entity_id: binary_sensor.leak_detectrd
      platform: state
    condition: []
    action:
    - data:
        entity_id: switch.hub_drop_4_4025c2_water_supply
      service: switch.turn_off
