homeassistant:
  customize:
          
template:
  - sensor:
      - name: "Total Water Usage"
        unit_of_measurement: "gal"
        state_class: "total_increasing"
        device_class: "water"
        state: >
          {{ states('sensor.hub_drop_4_4025c2_total_water_used_today') }}
