homeassistant:
  customize:
          
automation:
- id: laundry_room_litter_control
  alias: laundry_room_litter_control
  initial_state: 'off'
  trigger:
  - entity_id: binary_sensor.cat_motion_combine
    platform: state
  condition: []
  action:
  - data:
      entity_id: switch.laundry_room_litter_box
    service_template: >
      {% if is_state('binary_sensor.cat_motion_combine','off') %}
        switch.turn_on
      {% else %}
        switch.turn_off
      {% endif %}
