homeassistant:
  customize:
          
template:
  - sensor:
      - name: "Total Water Usage"
        unit_of_measurement: "gal"
        state_class: "total_increasing"
        device_class: "water"
        state: >
          {{ states('sensor.total_water_usage_integrated') }}

# Integration sensor configuration
sensor:
  - platform: integration
    source: sensor.water_flow_rate
    name: total_water_usage_integrated
    unit_prefix: none
    round: 2
    method: trapezoidal
    unit_time: min
