homeassistant:
  customize:
    light.livingroom_entry:
      friendly_name: "Livingroom Entry"
    light.main_livingroom:
      friendly_name: "Main Livingroom"
    switch.livingroom_subwoofer:
      friendly_name: "Livingroom Subwoofer"
      icon: mdi:speaker
    binary_sensor.livingroom_door_opened:
      device_class: door
      friendly_name: Livingroom Door
  
template:
  - binary_sensor:
      - name: livingroom_door_opened
        state: >
          {{ is_state('binary_sensor.front_door', 'on') }}
      - name: petbowl_leak
        state: >
          {{ is_state('binary_sensor.water_bowl', 'on') }}
        delay_off:
          minutes: 5
  
mqtt:
  light:
    name: "Jayhawk Candle"
    state_topic: "/Jayhawk_Candle/relay/switch"
    command_topic: "/Jayhawk_Candle/gpio/12"
    payload_on: "1"
    payload_off: "0"
    retain: false
    
lock:
  - platform: template
    name: front_door
    value_template: "{{ states('lock.schlage_allegion_be469_touchscreen_deadbolt_locked') }}"
    lock:
      service: script.front_door_lock
    unlock:
      service: script.front_door_unlock
    
media_player:
  - platform: kodi
    name: Livingroom_kodi
    host: 192.168.3.6
    username: !secret KODI_USR
    password: !secret KODI_PW

  - platform: androidtv
    name: livingroom_shield
    host: 192.168.3.6
    adb_server_ip: 127.0.0.1
    adb_server_port: 5037

  - platform: universal
    name: livingroom_media
    children:
      - media_player.Livingroom_kodi
      - media_player.livingroom_shield
      - media_player.living_room_un55ju6400
      - media_player.living_room_tv

      
alert:
  water_bowl_alarm:
    name: water_bowl_alarm
    done_message: "Petbowl Leak Resolved"
    message: "The water bowl is leaking bruh"
    entity_id: binary_sensor.petbowl_leak
    state: 'on'
    repeat: 30
    can_acknowledge: true
    skip_first: false
    notifiers:
      - group_notify
      
automation:
  - id: petbowl_leak
    alias: petbowl_leak
    initial_state: 'off'
    trigger:
      - platform: state
        entity_id: binary_sensor.petbowl_leak
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.petbowl_leak
                state: 'off'
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: switch.water_bowl
        default:
          - service: switch.turn_off
            target:
              entity_id: switch.water_bowl


script:
  front_door_lock:
    alias: front_door_lock
    sequence:
      - condition: state
        entity_id: binary_sensor.livingroom_door_opened
        state: 'off'
      - service: lock.lock
        data:
          entity_id: lock.schlage_allegion_be469_touchscreen_deadbolt_locked
  
  front_door_unlock:
    alias: front_door_unlock
    sequence:
      - condition: state
        entity_id: alarm_control_panel.alarm_panel
        state: 'disarmed'
      - service: lock.unlock
        data:
          entity_id: lock.schlage_allegion_be469_touchscreen_deadbolt_locked
