homeassistant:
  customize:
    light.livingroom_entry:
      friendly_name: "Livingroom Entry"
    light.main_livingroom_entry:
      friendly_name: "Main Livingroom"
    switch.livingroom_subwoofer:
      friendly_name: "Livingroom Subwoofer"
      icon: mdi:speaker
    binary_sensor.livingroom_door_opened:
      device_class: door
      friendly_name: Livingroom Door
  
binary_sensor:
  - platform: template
    sensors:
      livingroom_door_opened:
        friendly_name: "Front Door"
        value_template: >-
          {{ is_state('binary_sensor.front_door', 'on') }}
  
light:
  - platform : mqtt
    name: "Jayhawk Candle"
    state_topic: "/Jayhawk_Candle/relay/switch"
    command_topic: "/Jayhawk_Candle/gpio/12"
    payload_on: "1"
    payload_off: "0"
    retain: false
    
lock:
  - platform: template
    name: front_door
    value_template: "{{ states('lock.schlage_allegion_be469_touchscreen_deadbolt_locked') }}"
    lock:
      service: script.front_door_lock
    unlock:
      service: script.front_door_unlock
#roomba:
#  - host: 192.168.2.123
#    blid: secret! lrr_un
#    password: secret! lrr_pw
    
media_player:
  - platform: kodi
    name: Livingroom_kodi
    host: 192.168.3.6
    username: !secret KODI_USR
    password: !secret KODI_PW

  - platform: androidtv
    name: livingroom_shield
    host: 192.168.3.6
    adb_server_ip: 127.0.0.1
    adb_server_port: 5037

  - platform: universal
    name: livingroom_media
    children:
      - media_player.Livingroom_kodi
      - media_player.livingroom_shield
      - media_player.living_room_un55ju6400
      - media_player.living_room_tv
      
automation:
  - id: house_sts_jayhawks_on
    alias: house_sts_jayhawks_on
    initial_state: 'off'
    trigger:
    - entity_id: binary_sensor.house_sts_jayhawks
      platform: state
    condition: []
    action:
    - data:
        entity_id: light.jayhawk_candle
      service_template: >
        {% if is_state('binary_sensor.house_sts_jayhawks', 'on') %}
          light.turn_on
        {% else %}
          light.turn_off
        {% endif %}
