homeassistant:
  customize:
    switch.main_bath_fan:
      friendly_name: Main Bathroom Vent
      icon: mdi:fan
    light.main_bath_vanity:
      friendly_name: Main Bathroom Vanity
    light.main_bath_vent_light:
      friendly_name: Main Bathroom Vent Light
    binary_sensor.main_bath_vent_needed:
      device_class: occupancy
    binary_sensor.main_bath_motion:
      device_class: motion
  
  
binary_sensor:
  - platform: template
    sensors:
      main_bath_vent_needed:
        value_template: >-
          {{ states('sensor.bathroom_vent_humidity')|float > states('sensor.main_bath_target_humidity')|float 
             or is_state('binary_sensor.main_bath_vent_motion','on') }}
        delay_off:
          minutes: 5

  - platform: template
    sensors:
      main_bath_motion:
        value_template: >-
          {{ states('sensor.bathroom_motion_raw')|float > 0 }}

  - platform: template
    sensors:
      main_bath_vent_motion:
        value_template: >-
          {{ is_state('binary_sensor.main_bath_motion','on') }}
        delay_off:
          minutes: 1
          
    
sensor:
  - platform: mqtt
    name: "Bathroom Vent Temperature"
    state_topic: "/Attic_Sensor/Vent/Temperature"
    unit_of_measurement: "°C"
    device_class: temperature

  - platform: mqtt
    name: "Bathroom Vent Pressure"
    state_topic: "/Attic_Sensor/Vent/Pressure"
    unit_of_measurement: "hPa"
    device_class: temperature

  - platform: mqtt
    name: "Bathroom Vent Humidity"
    state_topic: "/Attic_Sensor/Vent/Humidity"
    unit_of_measurement: "%"
    device_class: pressure

  - platform: mqtt
    name: "Bathroom Vent VOC"
    state_topic: "/Attic_Sensor/Vent/Gas"
    unit_of_measurement: "Ω"

  - platform: template
    sensors:
      main_bath_target_humidity:
        value_template: >-
          {% if is_state('binary_sensor.house_sts_hvac_shut', 'off') or is_state('binary_sensor.house_sts_hvac_cool_req', 'on') %}
            {{ (states('sensor.hvac_humidity')|float+states('input_number.main_bath_humidity_thresh')|float) }}
          {% elif (states('sensor.hvac_humidity')|float+states('input_number.main_bath_humidity_thresh')|float) > (states('input_number.hvac_humidity_max'))|float %}
            {{ (states('input_number.hvac_humidity_max')|float+states('input_number.main_bath_humidity_thresh')|float) }}
          {% else %}
            {{ (states('sensor.hvac_target_humidity')|float+states('input_number.main_bath_humidity_thresh')|float) }}
          {% endif %}
        unit_of_measurement: "%"
        

input_boolean:
  bath_fan_needed:
    name: bath_fan_needed
    initial: off

automation:
  - id: main_bath_vent_control
    alias: main_bath_vent_control
    initial_state: 'off'
    trigger:
    - entity_id: input_boolean.bath_fan_needed
      platform: state
    condition: []
    action:
    - data:
        entity_id: switch.main_bath_fan
      service_template: >
        {% if is_state('input_boolean.bath_fan_needed','on') %}
          switch.turn_on
        {% else %}
          switch.turn_off
        {% endif %}
        
  - id: main_bath_vent_control_on
    alias: main_bath_vent_control_on
    initial_state: 'off'
    trigger:
    - entity_id: light.main_bath_vent_light
      platform: state
      to: "on"
    condition: []
    action:
    - data:
        entity_id: input_boolean.bath_fan_needed
      service:
        input_boolean.turn_on

  - id: main_bath_vent_control_off
    alias: main_bath_vent_control_off
    initial_state: 'off'
    trigger:
    - entity_id: binary_sensor.main_bath_vent_needed
      platform: state
      to: "off"
    condition: []
    action:
    - data:
        entity_id: input_boolean.bath_fan_needed
      service:
        input_boolean.turn_off
