homeassistant:
  customize:

binary_sensor:

  - platform: mqtt # Master Bedroom Window
    state_topic: "hawirelesslink/binary_sensor/centralite_3315_s_0e4974b8_1_1280/state"
    name: master_bed_window
    payload_on: "on"
    payload_off: "off"
    device_class: window
          
    
sensor:
  - platform: mqtt
    name: master_bed_window_temp
    state_topic: "hawirelesslink/sensor/centralite_3315_s_0e4974b8_1_1026/state"
    unit_of_measurement: "°F"
    device_class: temperature
    
    
automation:
  - id: 'mbr_tv_off'
    alias: mbr_tv_off
    initial_state: 'off'
    trigger:
    - platform: time
      at: '2:30:00'
    - platform: time
      at: '3:30:00'
    - platform: time
      at: '4:30:00'
    condition: []
    action:
    - data:
        entity_id: switch.master_tv
      service: switch.turn_off
