homeassistant:
  customize:
    binary_sensor.master_bed_window:
      friendly_name: Master Bedroom Window
      device_class: window
    switch.master_tv:
      friendly_name: Master Bedroom TV
      icon: mdi:television
    fan.master_fan:
      friendly_name: Master Fan
    light.master_fan_light:
      friendly_name: Master Fan Light
    switch.master_tv:
      friendly_name: Master TV
    sensor.master_bed_window_temp:
      friendly_name: Master Bedroom Window Temp
      
automation:
  - id: 'mbr_tv_off'
    alias: mbr_tv_off
    initial_state: 'off'
    trigger:
    - platform: time
      at: '2:30:00'
    - platform: time
      at: '3:30:00'
    - platform: time
      at: '4:30:00'
    condition: []
    action:
    - data:
        entity_id: switch.master_tv
      service: switch.turn_off
