homeassistant:
  customize:
    
    
automation:
  - id: 'mbr_tv_off'
    alias: mbr_tv_off
    initial_state: 'off'
    trigger:
    - platform: time
      at: '2:30:00'
    - platform: time
      at: '3:30:00'
    - platform: time
      at: '4:30:00'
    condition: []
    action:
    - data:
        entity_id: switch.master_tv
      service: switch.turn_off
