homeassistant:
  customize:
  
#binary_sensor:

    
timer:
  mt_fish_feeder:
    duration: '00:10:00'

binary_sensor:
  - platform: template
    sensors:
      mt_feeder_toggle:
        value_template: >-
          {{ is_state('input_boolean.feed_mini_tank', 'on') }}

input_boolean:
  feed_mini_tank:
    name: Feed Fish
    initial: off

script:
  feed_fish:
    alias: feed_fish
    sequence:
      - service: light.turn_off
        data:
          entity_id: light.bed_pump
