homeassistant:
  customize:
  
binary_sensor:
  - platform: template
    sensors:
      mt_feeder_toggle:
        value_template: >-
          {{ is_state('input_boolean.feed_mini_tank', 'on') }}

input_boolean:
  feed_mini_tank:
    name: Feed Fish
    initial: off
    
automation:
  - id: 'mt_light_on_dawn'
    alias: 'mt_light_on_dawn'
    initial_state: 'off'
    trigger:
    - entity_id: binary_sensor.morning
      platform: state
      to: 'on'
    condition: []
    action:
    - data:
        entity_id: light.tank_light
      service: light.turn_on
      
  - id: 'mt_light_off_dusk'
    alias: 'mt_light_off_dusk'
    initial_state: 'off'
    trigger:
    - entity_id: binary_sensor.evening
      platform: state
      to: 'on'
    condition: []
    action:
    - data:
        entity_id: light.tank_light
      service: light.turn_off

  - id: 'mt_feed'
    alias: mt_feed
    initial_state: 'off'
    trigger:
    - platform: time
      at: '11:00:00'
    condition: []
    action:
    - data:
        entity_id: script.mt_feed_fish
      service: script.turn_on
      
  - id: 'mt_heater'
    alias: mt_heater
    initial_state: 'off'
    trigger:
    - platform: template
      value_template: "{% if states('sensor.tank_probe_c')|float < 70.0 %}true{% endif %}"
    - platform: template
      value_template: "{% if states('sensor.tank_probe_c')|float > 80.0 %}true{% endif %}"
    condition: []
    action:
    - data:
        entity_id: light.heater
      service_template: >
        {% if states('sensor.tank_probe_c')|float < 70.0 %}
          light.turn_on
        {% else %}
          light.turn_off
        {% endif %}
      

script:
  mt_feed_fish:
    alias: mt_feed_fish
    sequence:
      - service: light.turn_off
        data:
          entity_id: light.bed_pump
      - delay: '00:10:00'
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.feed_mini_tank
      - delay: '00:20:00'
      - service: light.turn_on
        data:
          entity_id: light.bed_pump
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.feed_mini_tank
      - service: script.turn_on
        data:
          entity_id: script.mt_pump_on
   
  mt_pump_off:
    alias: mt_pump_off
    sequence:
      - service: light.turn_off
        data:
          entity_id: light.bed_pump
      - delay: '00:05:00'
      - service: script.turn_on
        data:
          entity_id: script.mt_pump_on
          
  mt_pump_on:
    alias: mt_pump_on
    sequence:
      - condition: state
        entity_id: 'input_boolean.feed_mini_tank'
        state: 'off'
      - service: light.turn_on
        data:
          entity_id: light.bed_pump
      - delay: '00:00:30'
      - service: script.turn_on
        data:
          entity_id: script.mt_pump_off
