homeassistant:
  customize:
  

proxmoxve:
  - host: 192.168.1.4
    username: !secret proxmoxUN
    password: !secret proxmoxPW
    verify_ssl: false
    realm: pve
    nodes:
      - node: rebbacah
        vms:
          - 100
          - 201
          - 300
          - 400



sensor:
  - platform: mqtt
    name: "Rebbacah CPU"
    state_topic: "rebbacah/rebbacah/cpu"
    unit_of_measurement: '%'
    value_template: "{{ my_test_json.fields.usage_system|float + my_test_json.fields.usage_guest|float }}"
    
  - platform: mqtt
    name: "Rebbacah CPU"
    state_topic: "rebbacah/rebbacah/cpu"
    unit_of_measurement: '%'
    value_template: "{{ my_test_json.fields.usage_system|float + my_test_json.fields.usage_guest|float }}"
