homeassistant:
  customize:
  

proxmoxve:
  - host: 192.168.1.4
    username: !secret proxmoxUN
    password: !secret proxmoxPW
    verify_ssl: false
    realm: pve
    nodes:
      - node: rebbacah
        vms:
          - 100
          - 201
          - 300
          - 400
