homeassistant:
  customize:

binary_sensor:
  - platform: mqtt # Emi fan state
    state_topic: "hawirelesslink/fan/king_of_fans_inc_hbuniversalcfremote_a4952a00_fan/state"
    name: nursery_fan_state
    payload_on: "on"
    payload_off: "off"
    device_class: power
    
fan:
  - platform: template
    fans:
     nursery_fan:
        friendly_name: "Nursery fan"
        value_template: "{{ states('binary_sensor.nursery_fan_state') }}"
        speed_template: "{{ states('sensor.nursery_fan_speed')|replace('\"','') }}"
        turn_on:
          service:  mqtt.publish
          data_template:
              topic: "/HAwirelesslink/return/fan/king_of_fans_inc_hbuniversalcfremote_a4952a00_fan/state"
              payload: 'on'
        turn_off:
          service:  mqtt.publish
          data_template:
              topic: "/HAwirelesslink/return/fan/king_of_fans_inc_hbuniversalcfremote_a4952a00_fan/state"
              payload: 'off'
        set_speed:
          service: mqtt.publish
          data_template:
              topic: "/HAwirelesslink/return/fan/king_of_fans_inc_hbuniversalcfremote_a4952a00_fan/speed"
              payload: '{{ speed }}'
        speeds:
          - 'low'
          - 'medium'
          - 'high'
          - 'on'
          - 'auto'
          - 'smart'
          - 'off'
          
sensor:
  - platform: mqtt
    name: "emi_fan_speed"
    state_topic: "hawirelesslink/fan/king_of_fans_inc_hbuniversalcfremote_0020d37b_1_514/speed"
          
light:
  - platform : mqtt
    name: nursery_fan_light
    state_topic: "hawirelesslink/light/king_of_fans_inc_hbuniversalcfremote_a4952a00_level_on_off/state"
    command_topic: "/HAwirelesslink/return/light/king_of_fans_inc_hbuniversalcfremote_a4952a00_level_on_off/state"
    payload_on: "on"
    payload_off: "off"
    retain: false
    
  
switch:
  - platform : mqtt
    name: nursery_heater
    state_topic: "hawirelesslink/switch/ledvance_plug_00054677_1/state"
    command_topic: "/HAwirelesslink/return/light/ledvance_plug_00054677_1/state"
    payload_on: "on"
    payload_off: "off"
    retain: false

climate:
  - platform: generic_thermostat
    name: nursery_heater
    heater: switch.nursery_heater
    target_sensor: sensor.nursery_temp
    min_temp: 0
    max_temp: 70
    ac_mode: false
    target_temp: 65
    cold_tolerance: 0
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "off"
    away_temp: 0
    precision: 0.1
