homeassistant:
  customize:
  
switch:
  - platform : mqtt
    name: nursery_heater
    state_topic: "hawirelesslink/switch/ledvance_plug_00054677_1/state"
    command_topic: "/HAwirelesslink/return/light/ledvance_plug_00054677_1/state"
    payload_on: "on"
    payload_off: "off"
    retain: false

climate:
  - platform: generic_thermostat
    name: nursery_heater
    heater: switch.nursery_heater
    target_sensor: sensor.nursery_temp
    min_temp: 0
    max_temp: 70
    ac_mode: false
    target_temp: 65
    cold_tolerance: 0
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "off"
    away_temp: 0
    precision: 0.1
