homeassistant:
  customize:
    sensor.office_computer_power:
      device_class: power
    sensor.octoprint_target_bed_temp:
      device_class: temperature
    sensor.office_pressure:
      device_class: pressure
    sensor.office_temperature:
      device_class: temperature
    sensor.office_humidity:
      device_class: humidity
  
binary_sensor:
  - platform: mqtt
    state_topic: "/Office/motion_sensor/Switch"
    name: "off_sts_motion_raw"
    payload_on: "1"
    payload_off: "0"

  - platform: template
    sensors:
      off_sts_motion:
        value_template: >-
          {{ is_state('binary_sensor.off_sts_motion_raw', 'on') }}
        delay_off:
          minutes: 15

  - platform: template
    sensors:
      off_htr_needed:
        value_template: >-
          {{ is_state('binary_sensor.off_sts_motion','on')
             and is_state('binary_sensor.house_sts_hvac_heat_req','on') }}
  
sensor:
  - platform: mqtt
    name: "Office Temperature"
    state_topic: "/office/enviroment/Temperature"
    unit_of_measurement: "°C"

  - platform: mqtt
    name: "Office Pressure"
    state_topic: "/office/enviroment/Pressure"
    unit_of_measurement: "hPa"
    
  - platform: mqtt
    name: "Office Humidity"
    state_topic: "/office/enviroment/Humidity"
    unit_of_measurement: "%"

  - platform: mqtt
    name: "Office Computer Power"
    state_topic: "hawirelesslink/sensor/enerwave_zw15rm_plus_15a_tr_smart_meter_duplex_receptacle_power_2/power_consumption"
    unit_of_measurement: "W"
    
switch:
  - platform: wake_on_lan
    name: off_4k_mon
    mac: "a0:6a:44:23:f6:99"
    host: 192.168.1.209
    broadcast_address: 192.168.1.209

  - platform: wake_on_lan
    name: off_computron3000
    mac: "40:16:7e:e8:dc:7b"
    host: 192.168.1.107
    broadcast_address: 192.168.1.107

  - platform: wake_on_lan
    name: off_frankenserver
    mac: "68:1c:a2:13:24:37"
    host: 192.168.1.186

  - platform : mqtt
    name: "Office Heater"
    state_topic: "/Office_Heater/relay/switch"
    command_topic: "/Office_Heater/gpio/12"
    payload_on: "1"
    payload_off: "0"
    retain: false
    
climate:
  - platform: generic_thermostat
    name: office_climate
    heater: switch.office_heater
    target_sensor: sensor.office_temperature
    min_temp: 0
    max_temp: 70
    ac_mode: false
    target_temp: 65
    cold_tolerance: 0
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "off"
    away_temp: 0
    precision: 0.1
    
automation:
  - id: 'off_occ_on'
    alias: off_occ_on
    initial_state: 'off'
    trigger:
    - entity_id: binary_sensor.off_sts_motion
      platform: state
    condition: []
    action:
    - service: climate.set_temperature
      data_template:
        temperature: >
          {% if is_state('binary_sensor.off_htr_needed','on') %}
            65
          {% else %}
            30
          {% endif %}
      entity_id: climate.office_climate
    - data:
        entity_id: switch.off_4k_mon
      service: switch.turn_on
    - data:
        entity_id: switch.off_computron3000
      service: switch.turn_on
