homeassistant:
  customize:
    sensor.office_computer_power:
      device_class: power
    sensor.octoprint_target_bed_temp:
      device_class: temperature
    sensor.office_pressure:
      device_class: pressure
    sensor.office_temperature:
      device_class: temperature
    sensor.office_humidity:
      device_class: humidity

sensor:
  - platform: integration
    source: sensor.computron_w
    name: computron_khw
    unit_prefix: k
    round: 2
    max_sub_interval:
      minutes: 5
  
switch:
  - platform: wake_on_lan
    name: off_4k_mon
    mac: "a0:6a:44:23:f6:99"
    host: 192.168.2.124
    broadcast_address: 192.168.2.124

  - platform: wake_on_lan
    name: off_computron3000
    mac: "40:16:7e:e8:dc:7b"
    host: 192.168.1.195
    broadcast_address: 192.168.1.195
    
climate:
  - platform: generic_thermostat
    name: office_climate
    heater: switch.office_heater_switch
    target_sensor: sensor.office_temperature
    min_temp: 0
    max_temp: 70
    ac_mode: false
    target_temp: 68
    cold_tolerance: 0
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 300
    initial_hvac_mode: "off"
    away_temp: 0
    precision: 1
    
automation:
  - id: 'off_occ_on'
    alias: off_occ_on
    initial_state: 'off'
    trigger:
    - entity_id: binary_sensor.office_eth_va_office_eth_va_presence
      platform: state
    action:
    - service: climate.set_hvac_mode
      data_template:
        hvac_mode: >
            {% if is_state('binary_sensor.office_eth_va_office_eth_va_presence', 'off') or is_state('binary_sensor.house_sts_hvac_run', 'off')  %}
              off
            {% else %}
              heat
            {% endif %}
        entity_id: climate.office_climate


    
      
      
