  
homeassistant:
  customize:
    person.brett:
      entity_picture: "https://lh3.googleusercontent.com/a-/AAuE7mAFoTSi0SiXnqVRLTmC9jrqC8duqWiPUirXhUFFnA"
    person.brett:
      entity_picture: "https://lh3.googleusercontent.com/a-/AAuE7mAWnEl6y091B1GyCwAp_-1FldDoDGy7kJNvsRUn"
  
  
automation:
  - id: 'brett_home'
    alias: brett_home
    initial_state: 'off'
    trigger:
    - entity_id: binary_sensor.brett_ble
      platform: state
      from: 'off'
      to: 'on'
    condition: []
    action:
    - service: device_tracker.see
      data:
        dev_id: device_tracker.google_maps_116842525089175776476
        location_name: 'home'
        
  - id: 'liz_home'
    alias: liz_home
    initial_state: 'off'
    trigger:
    - entity_id: binary_sensor.liz_ble
      platform: state
      from: 'off'
      to: 'on'
    condition: []
    action:
    - service: device_tracker.see
      data:
        dev_id: google_maps_108379141181739394475
        location_name: 'home'
