homeassistant:
  customize:
    fan.nursery_fan:
      friendly_name: Scarlett Fan
    light.nursery_fan_light:
      friendly_name: Scarlett Light


climate:
  - platform: generic_thermostat
    name: nursery_heater
    heater: switch.nursery_heater
    target_sensor: sensor.nursery_temp
    min_temp: 0
    max_temp: 70
    ac_mode: false
    target_temp: 65
    cold_tolerance: 0
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "off"
    away_temp: 0
    precision: 0.1
    
automation:
  - id: nursery_fan_speed
    alias: nursery_fan_speed
    initial_state: 'off'
    trigger:
    - entity_id: sensor.emi_temp
      platform: state
    - entity_id: 'fan.nursery_fan'
      platform: state
    condition:
      - condition: state
        entity_id: 'fan.nursery_fan'
        state: 'on'
    action:
    - service: fan.set_speed
      data_template:
        entity_id: fan.nursery_fan
        speed: >
          {% if (states.sensor.emi_temp.state|float(default=0) > 80 ) %}
            on
          {% elif (states.sensor.emi_temp.state|float(default=0) <= 80 ) and (states.sensor.emi_temp.state|float(default=0) > 76 ) %} 
            high
          {% elif (states.sensor.emi_temp.state|float(default=0) <= 76 ) and (states.sensor.emi_temp.state|float(default=0) > 74 ) %} 
            medium
          {% elif (states.sensor.emi_temp.state|float(default=0) <= 74 ) %} 
            low
          {% endif %}
