homeassistant:
  customize:
    fan.nursery_fan:
      friendly_name: Scarlett Fan
    light.nursery_fan_light:
      friendly_name: Scarlett Light
      

climate:
  - platform: generic_thermostat
    name: Lottie Heater
    heater: switch.lottie_heater_switch
    target_sensor: sensor.lottie_room_air_temperature
    min_temp: 50
    max_temp: 75
    ac_mode: false
    target_temp: 70
    cold_tolerance: 0
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    initial_hvac_mode: "off"
    away_temp: 50
    sleep_temp: 68
    comfort_temp: 70
    precision: 0.1
    
automation:
  - id: nursery_fan_speed
    alias: nursery_fan_speed
    initial_state: 'off'
    trigger:
    - entity_id: sensor.emi_temp
      platform: state
    - entity_id: 'fan.nursery_fan'
      platform: state
    condition:
      - condition: state
        entity_id: 'fan.nursery_fan'
        state: 'on'
    action:
    - service: fan.set_percentage
      data_template:
        entity_id: fan.nursery_fan
      data:
        preset_mode: >
          {% if (states.sensor.emi_temp.state|float(default=0) > 80 ) %}
            100
          {% elif (states.sensor.emi_temp.state|float(default=0) <= 80 ) and (states.sensor.emi_temp.state|float(default=0) > 76 ) %} 
            67
          {% elif (states.sensor.emi_temp.state|float(default=0) <= 76 ) and (states.sensor.emi_temp.state|float(default=0) > 74 ) %} 
            33
          {% elif (states.sensor.emi_temp.state|float(default=0) <= 74 ) %} 
            0
          {% endif %}
          
