homeassistant:
  customize:
    fan.nursery_fan:
      friendly_name: Scarlett Fan
    light.nursery_fan_light:
      friendly_name: Scarlett Light
    
automation:
  - id: nursery_fan_speed
    alias: nursery_fan_speed
    initial_state: 'off'
    trigger:
    - entity_id: sensor.lottie_room_air_temperature
      platform: state
    - entity_id: 'fan.nursery_fan'
      platform: state
    condition:
      - condition: state
        entity_id: 'fan.nursery_fan'
        state: 'on'
    action:
    - service: fan.set_percentage
      data_template:
        entity_id: fan.nursery_fan
      data:
        percentage: >
          {% if (states.sensor.lottie_room_air_temperature.state|float(default=0) > 80 ) %}
            100
          {% elif (states.sensor.lottie_room_air_temperature.state|float(default=0) <= 80 ) and (states.sensor.lottie_room_air_temperature.state|float(default=0) > 76 ) %} 
            75
          {% elif (states.sensor.lottie_room_air_temperature.state|float(default=0) <= 76 ) and (states.sensor.lottie_room_air_temperature.state|float(default=0) > 74 ) %} 
            50
          {% elif (states.sensor.lottie_room_air_temperature.state|float(default=0) <= 74 ) %} 
            25
          {% endif %}
          
