automation:
  - id: 'kansas_playing'
    alias: kansas_playing
    trigger:
    - entity_id: sensor.kansas_basketball
      platform: state
      from:
        - "PRE"
        - "IN"
      to:
        - "IN"
        - "POST"
    - entity_id: sensor.kansas_football
      platform: state
      from:
        - "PRE"
        - "IN"
      to:
        - "IN"
        - "POST"
    - entity_id: sensor.kansas_volleyball
      platform: state
      from:
        - "PRE"
        - "IN"
      to:
        - "IN"
        - "POST"
    condition: []
    action:
      - if:
          - condition: state
            entity_id: trigger.to_state
            state: "IN"
        then:
          - service: light.turn_on
            data:
              brightness: 255
              entity_id: light.uhall_ban_hall_ban
              color_name: white
              effect: "Jayhawks"
          - service: light.turn_on
            data:
              brightness: 255
              entity_id: light.cabinet_top
              color_name: white
              effect: "Jayhawks"
          - data_template:
              message: "Jayhawks be playing."
            service: notify.group_notify
        else:
          - service: light.turn_on
            data:
              brightness: 50
              entity_id: light.uhall_ban_hall_ban
              color_name: white
              effect: "None"
          - service: light.turn_on
            data:
              brightness: 255
              entity_id: light.cabinet_top
              color_name: white
              effect: "None"
    mode: queued
  - id: 'chiefs_playing'
    alias: chiefs_playing
    trigger:
    - entity_id: sensor.kansas_city_chiefs
      platform: state
      from:
        - "PRE"
        - "IN"
      to:
        - "IN"
        - "POST"
    condition: []
    action:
      - if:
          - condition: template
            value_template: >-
              "{{ trigger.to_state.state == 'IN' }}"
        then:
          - service: light.turn_on
            data:
              brightness: 255
              entity_id: light.uhall_ban_hall_ban
              color_name: white
              effect: "Chiefs"
          - service: light.turn_on
            data:
              brightness: 255
              entity_id: light.cabinet_top
              color_name: white
              effect: "Chiefs"
          - data_template:
              message: "Chiefs be playing."
            service: notify.group_notify
        else:
          - service: light.turn_on
            data:
              brightness: 50
              entity_id: light.uhall_ban_hall_ban
              color_name: white
              effect: "None"
          - service: light.turn_on
            data:
              brightness: 255
              entity_id: light.cabinet_top
              color_name: white
              effect: "None"
    mode: queued
