homeassistant:
  customize:

binary_sensor:
  - platform: template
    sensors:
      house_sts_occupants:
        value_template: >-
          {{ is_state('group.occupants', 'home') }}
  - platform: template
    sensors:
      house_sts_guest:
        value_template: >-
          {{ states.calendar.guest_mode_visitor.state == 'on'
             or states.calendar.guest_mode_date.state == 'on' }}
  - platform: template
    sensors:
      house_sts_vacation:
        value_template: >-
          {{ states.calendar.vacation_mode.state == 'on' }}

  - platform: template
    sensors:
      house_sts_away_vacation:
        value_template: >-
          {{ ((states.proximity.brett_home.state)|float > 120 and 
             (states.proximity.liz_home.state)|float) > 120 and 
              is_state('binary_sensor.house_sts_vacation', 'on') }}
              
  - platform: template
    sensors:
      house_sts_incoming:
        value_template: >-
          {{ is_state('device_tracker.google_maps_116842525089175776476', 'homecoming')
             or is_state('device_tracker.google_maps_108379141181739394475', 'homecoming') }}

  - platform: template
    sensors:
      house_sts_dte_cheap:
        value_template: >-
          {{ states.calendar.dte_cheap.state == 'on' }}

  - platform: template
    sensors:
      house_sts_jayhawks:
        value_template: >-
          {{ states.calendar.football_kuathleticscom.state == 'on'
             or states.calendar.mens_basketball_kuathleticscom.state == 'on'
             or states.calendar.volleyball_kuathleticscom.state == 'on' }}
             
  - platform: template
    sensors:
      house_boot_complete:
        value_template: >-
          {{ states('sensor.uptime')|float > 5 }}
          
  - platform: template
    sensors:
      ingress_alarm:
        value_template: >-
          {{ (states('alarm_control_panel.alarm_panel') == 'armed_away'
             or states('alarm_control_panel.alarm_panel') == 'armed_home')
             and states('group.security') == 'on' }}
             
  - platform: template
    sensors:
      house_armed:
        value_template: >-
          {{ is_state('alarm_control_panel.alarm_panel','disarmed') }}
          
          
alert:
  ingress_alarm:
    name: ingress_alarm
    done_message: "House is now secure"
    message: "House is open bro"
    entity_id: binary_sensor.ingress_alarm
    state: 'on'
    repeat: 5
    can_acknowledge: true
    skip_first: true
    notifiers:
      - group_notify
      
input_number:
  hvac_home_ac_temp:
    mode: slider
    min: 60
    max: 85
    step: 1
    unit_of_measurement: "F"
  
  hvac_home_heat_temp:
    mode: slider
    min: 60
    max: 85
    step: 1
    unit_of_measurement: "F"
  
  hvac_away_ac_temp:
    mode: slider
    min: 60
    max: 85
    step: 1
    unit_of_measurement: "F"
  
  hvac_away_heat_temp:
    mode: slider
    min: 60
    max: 85
    step: 1
    unit_of_measurement: "F"
  
  hvac_overnight_ac_temp:
    mode: slider
    min: 60
    max: 85
    step: 1
    unit_of_measurement: "F"
  
  hvac_overnight_heat_temp:
    mode: slider
    min: 60
    max: 85
    step: 1
    unit_of_measurement: "F"
  
  hvac_vacation_ac_temp:
    mode: slider
    min: 60
    max: 85
    step: 1
    unit_of_measurement: "F"
  
  hvac_vacation_heat_temp:
    mode: slider
    min: 60
    max: 85
    step: 1
    unit_of_measurement: "F"
    
  hvac_ac_enable_temp:
    mode: slider
    min: 60
    max: 85
    step: 1
    unit_of_measurement: "F"
  
  hvac_heat_enable_temp:
    mode: slider
    min: 60
    max: 85
    step: 1
    unit_of_measurement: "F"
  
  hvac_humidity_max:
    mode: slider
    min: 30
    max: 55
    step: 1
    unit_of_measurement: "%"
    
  main_bath_humidity_thresh:
    mode: slider
    min: 0
    max: 15
    step: 1
    unit_of_measurement: "%"

  office_heater_thresh:
    mode: slider
    min: 55
    max: 70
    step: 1
    unit_of_measurement: "F"

sensor:
  - platform: rest
    name: Statewide Covid Stats
    resource: https://covidtracking.com/api/states?state=MI
    json_attributes:
      - positive
      - negative
      - pending
      - hospitalized
      - death
      - total
      - lastUpdateEt
    value_template: '{{ value_json.state }}'
    scan_interval: 60

  - platform: darksky
    api_key: eccf5f65e6dce657df3792d7e362f0db
    forecast:
      - 0
    monitored_conditions:
      - summary
      - icon
      - nearest_storm_distance
      - temperature
      - apparent_temperature
      - humidity
      - temperature_high
      - temperature_low

  - platform: template
    sensors:
      timeday:
        value_template: >-
          {% if is_state('binary_sensor.house_wake_for_work', 'on') or is_state('binary_sensor.house_weekend_wakeup', 'on') or is_state('binary_sensor.morning', 'on')%}
            {{ "morning" }}
          {% elif is_state('binary_sensor.afternoon', 'on') %} 
            {{ "afternoon" }}
          {% elif is_state('binary_sensor.evening', 'on') %}
            {{ "evening" }}
          {% else %}
            {{ "night" }}
          {% endif %}

  - platform: openhardwaremonitor
    host: 192.168.3.2

  - platform: openhardwaremonitor
    host: 192.168.2.201

  - platform: uptime
    unit_of_measurement: minutes

  - platform: mqtt
    name: "Attic Temp"
    state_topic: "/Attic_Sensor/Attic/Temperature"
    unit_of_measurement: "°C"

  - platform: mqtt
    name: "Attic Pressure"
    state_topic: "/Attic_Sensor/Attic/Pressure"
    unit_of_measurement: "hPa"

  - platform: mqtt
    name: "Attic Humidity"
    state_topic: "/Attic_Sensor/Attic/Humidity"
    unit_of_measurement: "%"


  - platform: flunearyou

  - platform: radarr
    api_key: cc9b6cb785744745b0877c7278d7e9d9
    host: 192.168.1.3
    monitored_conditions:
      - upcoming
      - movies
      - status
    days: 7

  - platform: sonarr
    api_key: 4208feb776af401ea6cb76833bf23d73
    host: 192.168.1.3
    monitored_conditions:
      - upcoming
      - series
      - wanted
    days: 7

  - platform: qbittorrent
    url: 'http://192.168.1.3:8112'
    username: !secret QBUN
    password: !secret QBPW

  - platform: mqtt
    name: "VPN down"
    state_topic: "hawirelesslink/sensor/speedtest_download/state"
    unit_of_measurement: "Mbit/s"

  - platform: mqtt
    name: "VPN up"
    state_topic: "hawirelesslink/sensor/speedtest_upload/state"
    unit_of_measurement: "Mbit/s"

  - platform: zestimate
    api_key: !secret ZILLOW
    zpid: 
      - 24680932

  - platform: template
    sensors:
      house_status:
        value_template: >-
          {% if is_state('binary_sensor.house_sts_occupants', 'on') %}
            {{ "Occupied" }}
          {% elif is_state('binary_sensor.house_sts_guest', 'on') %} 
            {{ "Guest mode" }}
          {% elif is_state('binary_sensor.house_sts_vacation', 'on') %}
            {{ "Vacation" }}
          {% else %}
            {{ "Away" }}
          {% endif %}

automation:
  - id: system_update_available
    alias: system_update_available
    initial_state: 'off'
    trigger:
      platform: state
      entity_id: updater.updater
    action:
      service: notify.brett_notify
      data:
        message: 'Update for Home Assistant is available.'

  - id: 'ha_start'
    alias: ha_start
    trigger:
    - event: start
      platform: homeassistant
    condition: []
    action:
    - data:
        entity_id: script.initialization
      service: script.turn_on

  - id: 'house_sts_occupants'
    alias: house_sts_occupants
    initial_state: 'off'
    trigger:
    - entity_id: binary_sensor.house_sts_occupants
      platform: state
    condition: []
    action:
    - data:
        entity_id: script.hvac_run_setpoint
      service: script.turn_on
    - data:
        entity_id: alarm_control_panel.alarm_panel
        code: !secret alarmcode
      service_template: >
        {% if is_state('binary_sensor.house_sts_occupants', 'off') and is_state('binary_sensor.house_sts_guest', 'off') %}
          alarm_control_panel.alarm_arm_away
        {% elif is_state('binary_sensor.house_sts_occupants', 'off') and is_state('house_status', 'vacation') %}
          alarm_control_panel.alarm_arm_away
        {% else %}
          alarm_control_panel.alarm_disarm
        {% endif %}
    - data_template:
        entity_id: >
             {% if is_state('binary_sensor.house_sts_occupants', 'off') and is_state('binary_sensor.house_sts_guest', 'off') %}
               scene.house_away
             {% else %}
               scene.house_home
             {% endif %} 
      service: scene.turn_on  
    - data_template:
        message: >
          Occupancy mode changed to {{ states('binary_sensor.house_sts_occupants') }}
      service: notify.group_notify

      
