homeassistant:
  customize:
    alarm_control_panel.abode_alarm_system:
      hidden: true
    sensor.home_eta:
      hidden: true
    sensor.home_security_state:
      hidden: true
    zone.brett_work:
      radius: 5000
    device_tracker.google_maps_108379141181739394475:
      friendly_name: Liz
    device_tracker.google_maps_116842525089175776476:
      friendly_name: Brett
    binary_sensor.house_sts_occupants:
      device_class: occupancy
      

template:
  - binary_sensor:
      - name: house_sts_occupants
        state: >
          {{ is_state('group.occupants', 'home') }}
  - binary_sensor:
      - name: house_sts_guest
        state: >
          {{ states.calendar.guest_mode_visitor.state == 'on'
             or states.calendar.guest_mode_date.state == 'on' }}
  - binary_sensor:
      - name: house_sts_vacation
        state: >
          {{ states.calendar.vacation_mode.state == 'on' }}

  - binary_sensor:
      - name: house_sts_away_vacation
        state: >
          {{ ((states.proximity.brett_home.state)|float(default=0) > 120 and 
             (states.proximity.liz_home.state)|float(default=0)) > 120 and 
              is_state('binary_sensor.house_sts_vacation', 'on') }}
              
  - binary_sensor:
      - name: house_sts_incoming
        state: >
          {{ is_state('device_tracker.google_maps_116842525089175776476', 'homecoming')
             or is_state('device_tracker.google_maps_108379141181739394475', 'homecoming') }}

  - binary_sensor:
      - name: house_sts_dte_cheap
        state: >
          {{ states.calendar.dte_cheap.state == 'on' }}

  - binary_sensor:
      - name: house_sts_jayhawks
        state: >
          {{ states.calendar.football_kuathleticscom.state == 'on'
             or states.calendar.mens_basketball_kuathleticscom.state == 'on'
             or states.calendar.volleyball_kuathleticscom.state == 'on' }}
             
  - binary_sensor:
      - name: house_boot_complete
        state: >
          {{ states('sensor.uptime')|float(default=0) > 5 }}
          
  - binary_sensor:
      - name: ingress_alarm
        state: >
          {{ (states('alarm_control_panel.alarm_panel') == 'armed_away'
             or states('alarm_control_panel.alarm_panel') == 'armed_home')
             and states('group.security') == 'on' }}
             
  - binary_sensor:
      - name: house_armed
        state: >
          {{ is_state('alarm_control_panel.alarm_panel','disarmed') }}
          
  - sensor:
      - name: timeday
        state: >
          {% if is_state('binary_sensor.house_wake_for_work', 'on') or is_state('binary_sensor.house_weekend_wakeup', 'on') or is_state('binary_sensor.morning', 'on')%}
            {{ "morning" }}
          {% elif is_state('binary_sensor.afternoon', 'on') %} 
            {{ "afternoon" }}
          {% elif is_state('binary_sensor.evening', 'on') %}
            {{ "evening" }}
          {% else %}
            {{ "night" }}
          {% endif %}

binary_sensor:
  - platform: ping
    host: 192.168.2.51
          
          
alert:
  ingress_alarm:
    name: ingress_alarm
    done_message: "House is now secure"
    message: "House is open bro"
    entity_id: binary_sensor.ingress_alarm
    state: 'on'
    repeat: 5
    can_acknowledge: true
    skip_first: true
    notifiers:
      - group_notify
      
input_number:
  hvac_home_ac_temp:
    mode: slider
    min: 60
    max: 85
    step: 1
    unit_of_measurement: "F"
  
  hvac_home_heat_temp:
    mode: slider
    min: 60
    max: 85
    step: 1
    unit_of_measurement: "F"
  
  hvac_away_ac_temp:
    mode: slider
    min: 60
    max: 85
    step: 1
    unit_of_measurement: "F"
  
  hvac_away_heat_temp:
    mode: slider
    min: 60
    max: 85
    step: 1
    unit_of_measurement: "F"
  
  hvac_overnight_ac_temp:
    mode: slider
    min: 60
    max: 85
    step: 1
    unit_of_measurement: "F"
  
  hvac_overnight_heat_temp:
    mode: slider
    min: 60
    max: 85
    step: 1
    unit_of_measurement: "F"
  
  hvac_vacation_ac_temp:
    mode: slider
    min: 60
    max: 85
    step: 1
    unit_of_measurement: "F"
  
  hvac_vacation_heat_temp:
    mode: slider
    min: 60
    max: 85
    step: 1
    unit_of_measurement: "F"
    
  hvac_ac_enable_temp:
    mode: slider
    min: 60
    max: 85
    step: 1
    unit_of_measurement: "F"
  
  hvac_heat_enable_temp:
    mode: slider
    min: 60
    max: 85
    step: 1
    unit_of_measurement: "F"
  
  hvac_humidity_max:
    mode: slider
    min: 30
    max: 55
    step: 1
    unit_of_measurement: "%"
    
  main_bath_humidity_thresh:
    mode: slider
    min: 0
    max: 15
    step: 1
    unit_of_measurement: "%"

  office_heater_thresh:
    mode: slider
    min: 55
    max: 70
    step: 1
    unit_of_measurement: "F"

sensor:
  - platform: mqtt
    name: "DTE Energy Bridge Summary"
    state_topic: "event/metering/summation/minute"
    unit_of_measurement: 'W'
    value_template: "{{ value_json.value | round(0) }}" 
    
  - platform: integration
    source: sensor.dte_energy_bridge_summary
    name: energy_spent
    unit_prefix: k
    round: 2

  - platform: darksky
    api_key: eccf5f65e6dce657df3792d7e362f0db
    forecast:
      - 0
    monitored_conditions:
      - summary
      - temperature
      - apparent_temperature
      - humidity
      - temperature_high
      - temperature_low

  - platform: uptime

  - platform: mqtt
    name: "Attic Temp"
    state_topic: "/Attic_Sensor/Attic/Temperature"
    unit_of_measurement: "°C"

  - platform: mqtt
    name: "Attic Pressure"
    state_topic: "/Attic_Sensor/Attic/Pressure"
    unit_of_measurement: "hPa"

  - platform: mqtt
    name: "Attic Humidity"
    state_topic: "/Attic_Sensor/Attic/Humidity"
    unit_of_measurement: "%"

  - platform: radarr
    api_key: c037c402e3814b978495137f7d18bf89
    host: 192.168.100.100
    monitored_conditions:
      - upcoming
      - movies
      - status
    days: 7


  - platform: qbittorrent
    url: 'http://192.168.100.100:8112'
    username: !secret QBUN
    password: !secret QBPW

          
folder_watcher:
  - folder: /config/www/
    patterns:
      - '*.jpg'

automation:
  - id: system_update_available
    alias: system_update_available
    initial_state: 'off'
    trigger:
      platform: state
      entity_id: updater.updater
    action:
      service: notify.brett_notify
      data:
        message: 'Update for Home Assistant is available.'
        
  - id: send_person_detected
    alias: send_person_detected
    initial_state: 'off'
    mode: single
    trigger:
      platform: event
      event_type: folder_watcher
      event_data:
        event_type: modified
    action:
      - delay:
          seconds: 10
      - service: notify.group_notify
        data:
          message: "Homie be up in your yard"
          data:
            image: "https://homeassistant.teamcarriger.club/local/snapshot1.jpg"
      - delay:
          seconds: 30

  - id: 'ha_start'
    alias: ha_start
    trigger:
    - event: start
      platform: homeassistant
    condition: []
    action:
    - data:
        entity_id: script.initialization
      service: script.turn_on
    - data_template:
        message: "Rejoice! For now is the blessed time for home assistant has once again booted."
      service: notify.group_notify
      

  - id: 'ha_down'
    alias: ha_down
    trigger:
    - event: shutdown
      platform: homeassistant
    condition: []
    action:
    - data_template:
        message: "Home Assistant is now shutting down"
      service: notify.group_notify

  - id: 'house_sts_occupants'
    alias: house_sts_occupants
    initial_state: 'off'
    trigger:
    - entity_id: binary_sensor.house_sts_occupants
      platform: state
    condition: []
    action:
    - data:
        entity_id: script.hvac_run_setpoint
      service: script.turn_on
    - data:
        entity_id: alarm_control_panel.alarm_panel
        code: !secret alarmcode
      service_template: >
        {% if is_state('binary_sensor.house_sts_occupants', 'off') and is_state('binary_sensor.house_sts_guest', 'off') %}
          alarm_control_panel.alarm_arm_away
        {% elif is_state('binary_sensor.house_sts_occupants', 'off') and is_state('house_status', 'vacation') %}
          alarm_control_panel.alarm_arm_away
        {% else %}
          alarm_control_panel.alarm_disarm
        {% endif %}
    - data_template:
        entity_id: >
             {% if is_state('binary_sensor.house_sts_occupants', 'off') and is_state('binary_sensor.house_sts_guest', 'off') %}
               scene.house_away
             {% else %}
               scene.house_home
             {% endif %} 
      service: scene.turn_on
    - data_template:
        message: >
          Occupancy mode changed to {{ states('binary_sensor.house_sts_occupants') }}
      service: notify.group_notify

      
