homeassistant:
  customize:
  
binary_sensor:
#Define times of day for the house, early, morning, afternoon, evening and night
  - platform: tod
    name: early_morning
    after: '05:30'
    before: sunrise

  - platform: tod
    name: morning
    after: sunrise
    before: '12:00'

  - platform: tod
    name: afternoon
    after: '12:00'
    before: sunset
    before_offset: '-00:30'

  - platform: tod
    name: evening
    after: sunset
    after_offset: '-00:30'
    before: '23:59'

  - platform: tod
    name: night
    after: '23:59'
    before: '05:30'

template:
  - binary_sensor:
      - name: house_time_workday_combine
        state: >
          {{ is_state('binary_sensor.workday_raw', 'on') }}
  - binary_sensor:
      - name: work_wakeup_time
        state: >
          {{ is_state('binary_sensor.early_morning', 'on') }}
          
  - binary_sensor:
      - name: house_wake_for_work
        state: >
          {{ is_state('binary_sensor.house_time_workday_combine', 'on') 
             and is_state('binary_sensor.work_wakeup_time', 'on')  }}  

  - binary_sensor:
      - name: house_weekend_wakeup
        state: >
          {{ is_state('binary_sensor.workday_raw', 'off') 
             and is_state('binary_sensor.morning', 'on')  }} 
  - binary_sensor:
      - name: house_wakeup
        state: >
          {{ is_state('binary_sensor.house_wake_for_work', 'on') 
             or is_state('binary_sensor.house_weekend_wakeup', 'on')  }} 


  - binary_sensor:
      - name: house_wakeup_vacation_morning
        state: >
          {{ is_state('binary_sensor.early_morning', 'on') 
             and is_state('binary_sensor.house_sts_vacation', 'on')  }}
             

  - binary_sensor:
      - name: house_wakeup_vacation_evening
        state: >
          {{ is_state('binary_sensor.evening', 'on') 
             and is_state('binary_sensor.house_sts_vacation', 'on')  }}
  
automation:
  - id: 'house_wakeup'
    alias: house_wakeup
    initial_state: 'off'
    trigger:
      - platform: state
        entity_id: binary_sensor.house_wakeup
        to: 'on'
    action:
      - service: script.turn_on
        target:
          entity_id:
            - script.hvac_run_stop_uni
            - script.house_wakeup
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.house_sts_xmas_lights
                state: 'on'
            sequence:
              - service: script.turn_on
                target:
                  entity_id: script.xmas_light

  - id: 'house_evening_mode'
    alias: house_evening_mode
    initial_state: 'off'
    trigger:
      - platform: state
        entity_id: binary_sensor.evening
        to: 'on'
    action:
      - service: script.turn_on
        target:
          entity_id:
            - script.hvac_run_stop_uni
            - script.house_evening
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.house_sts_independence_day
                state: 'on'
            sequence:
              - service: script.turn_on
                target:
                  entity_id: script.independence_day
          - conditions:
              - condition: state
                entity_id: binary_sensor.house_sts_xmas_lights
                state: 'on'
            sequence:
              - service: script.turn_on
                target:
                  entity_id: script.xmas_light
          - conditions:
              - condition: state
                entity_id: binary_sensor.house_sts_halloween
                state: 'on'
            sequence:
              - service: script.turn_on
                target:
                  entity_id: script.halloween_light


                  

  - id: house_night_mode
    alias: house_night_mode
    initial_state: 'off'
    trigger:
      - platform: state
        entity_id: binary_sensor.night
        to: 'on'
    action:
      - service: cover.close_cover
        target:
          entity_id: cover.garage_door
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.house_sts_vacation
                state: 'on'
            sequence:
              - service: alarm_control_panel.alarm_arm_away
                data:
                  entity_id: alarm_control_panel.alarm_panel
                  code: !secret alarmcode
        default:
          - service: alarm_control_panel.alarm_arm_home
            data:
              entity_id: alarm_control_panel.alarm_panel
              code: !secret alarmcode
      - service: script.turn_on
        target:
          entity_id:
            - script.hvac_run_setpoint
            - script.house_night

  - id: 'ext_lights_off'
    alias: ext_lights_off
    initial_state: 'off'
    trigger:
      - platform: state
        entity_id: binary_sensor.morning
        to: 'on'
    action:
      - service: script.turn_on
        target:
          entity_id: script.ext_lights_off


