- platform: amcrest

- platform: generic
  name: speedtest
  still_image_url: 'https://127.0.0.1:3000/d/cYqIkiIZk/internet-speed?orgId=1&from=now-48h&to=now'
  username: !secret grafana_user
  password: !secret grafana_pass
